In [1]:
import csv
import pandas as pd

# Dataset merge and prep for analysis

Checking and renaming the datasets to merge them into one combined dataset and get it ready for (IAA) analysis.

Change folder (Test1, Test2, Main1, Main2...) to process other datasets as they come.

In [6]:
df1 = pd.read_excel("Main2/Main2_Tamara.xlsx")
df2 = pd.read_excel("Main2/Main2_Katja.xlsx")

In [7]:
df1 = df1.drop(columns=['Annotation values', 'Chair'])
df2 = df2.drop(columns='Annotation values')

In [8]:
df1.rename(columns={'Text':'text', 'Annotation': 'tag_tamara', 'Comments': 'comments_tamara','Flag':'flagged_tamara', 'Chair':'chair'}, inplace=True)
df1.head()

,ID,text,tag_tamara,comments_tamara,flagged_tamara
0,ParlaMint-SI_2013-10-21-SDZ6-Redna-18.u63,Hvala. Besedo dajem gospodu Samu Omerzelu.,P_Neutral,Procedural,NaN
1,ParlaMint-SI_2010-12-23-SDZ5-Izredna-36.u69,Hvala lepa. Končali smo s predstavitvijo stali...,N_Neutral,Could be negative,NaN
2,ParlaMint-SI_2020-10-15-SDZ8-Izredna-46.u33,"Glejte, gospa [[…]] [[oglašanje iz dvorane]]",N_Neutral,We don't know what this is but negative.,NaN
3,ParlaMint-SI_2010-11-17-SDZ5-Redna-22.u106,"Hvala lepa. Glasujemo. Prekinjam. Prosim, gosp...",P_Neutral,Procedural,NaN
4,ParlaMint-SI_2005-10-26-SDZ4-Redna-10.u151,Hvala lepa. In še kot zadnjega vabim k besedi ...,P_Neutral,Procedural,NaN

In [10]:
df2.rename(columns={'Text':'text', 'Annotation': 'tag_katja', 'Comments': 'comments_katja','Flag':'flagged_katja', 'Chair':'chair'}, inplace=True)
df2.head()

,ID,text,tag_katja,comments_katja,flagged_katja,chair
0,ParlaMint-SI_2013-10-21-SDZ6-Redna-18.u63,Hvala. Besedo dajem gospodu Samu Omerzelu.,P_Neutral,NaN,NaN,True
1,ParlaMint-SI_2010-12-23-SDZ5-Izredna-36.u69,Hvala lepa. Končali smo s predstavitvijo stali...,N_Neutral,NaN,NaN,True
2,ParlaMint-SI_2020-10-15-SDZ8-Izredna-46.u33,"Glejte, gospa [[…]] [[oglašanje iz dvorane]]",P_Neutral,NaN,NaN,True
3,ParlaMint-SI_2010-11-17-SDZ5-Redna-22.u106,"Hvala lepa. Glasujemo. Prekinjam. Prosim, gosp...",P_Neutral,NaN,NaN,True
4,ParlaMint-SI_2005-10-26-SDZ4-Redna-10.u151,Hvala lepa. In še kot zadnjega vabim k besedi ...,P_Neutral,NaN,NaN,True

In [11]:
merged_df = pd.merge(df1, df2, on=['ID', 'text'])
merged_df.head()

,ID,text,tag_tamara,comments_tamara,flagged_tamara,tag_katja,comments_katja,flagged_katja,chair
0,ParlaMint-SI_2013-10-21-SDZ6-Redna-18.u63,Hvala. Besedo dajem gospodu Samu Omerzelu.,P_Neutral,Procedural,NaN,P_Neutral,NaN,NaN,True
1,ParlaMint-SI_2010-12-23-SDZ5-Izredna-36.u69,Hvala lepa. Končali smo s predstavitvijo stali...,N_Neutral,Could be negative,NaN,N_Neutral,NaN,NaN,True
2,ParlaMint-SI_2020-10-15-SDZ8-Izredna-46.u33,"Glejte, gospa [[…]] [[oglašanje iz dvorane]]",N_Neutral,We don't know what this is but negative.,NaN,P_Neutral,NaN,NaN,True
3,ParlaMint-SI_2010-11-17-SDZ5-Redna-22.u106,"Hvala lepa. Glasujemo. Prekinjam. Prosim, gosp...",P_Neutral,Procedural,NaN,P_Neutral,NaN,NaN,True
4,ParlaMint-SI_2005-10-26-SDZ4-Redna-10.u151,Hvala lepa. In še kot zadnjega vabim k besedi ...,P_Neutral,Procedural,NaN,P_Neutral,NaN,NaN,True

In [12]:
order = ['ID', 'text', 'tag_tamara', 'tag_katja', 'comments_tamara', 'comments_katja', 'flagged_tamara', 'flagged_katja', 'chair']

In [13]:
merged_df = merged_df[order]
merged_df['final_tag'] = ''
merged_df.head()

,ID,text,tag_tamara,tag_katja,comments_tamara,comments_katja,flagged_tamara,flagged_katja,chair,final_tag
0,ParlaMint-SI_2013-10-21-SDZ6-Redna-18.u63,Hvala. Besedo dajem gospodu Samu Omerzelu.,P_Neutral,P_Neutral,Procedural,NaN,NaN,NaN,True,
1,ParlaMint-SI_2010-12-23-SDZ5-Izredna-36.u69,Hvala lepa. Končali smo s predstavitvijo stali...,N_Neutral,N_Neutral,Could be negative,NaN,NaN,NaN,True,
2,ParlaMint-SI_2020-10-15-SDZ8-Izredna-46.u33,"Glejte, gospa [[…]] [[oglašanje iz dvorane]]",N_Neutral,P_Neutral,We don't know what this is but negative.,NaN,NaN,NaN,True,
3,ParlaMint-SI_2010-11-17-SDZ5-Redna-22.u106,"Hvala lepa. Glasujemo. Prekinjam. Prosim, gosp...",P_Neutral,P_Neutral,Procedural,NaN,NaN,NaN,True,
4,ParlaMint-SI_2005-10-26-SDZ4-Redna-10.u151,Hvala lepa. In še kot zadnjega vabim k besedi ...,P_Neutral,P_Neutral,Procedural,NaN,NaN,NaN,True,

In [14]:
merged_df.to_csv("Main2/Main2_combined.csv", encoding ='utf-8', index=False)