In [1]:
import csv
import pandas as pd

# Dataset merge and prep for analysis

Checking and renaming the datasets to merge them into one combined dataset and get it ready for (IAA) analysis.

Change folder (Test1, Test2, Main1, Main2...) to process other datasets as they come.

In [3]:
df1 = pd.read_excel("Main3/Main3_Tamara.xlsx")
df2 = pd.read_excel("Main3/Main3_Katja.xlsx")

In [4]:
df1 = df1.drop(columns=['Annotation values', 'Chair'])
df2 = df2.drop(columns='Annotation values')

In [5]:
df1.rename(columns={'Text':'text', 'Annotation': 'tag_tamara', 'Comments': 'comments_tamara','Flag':'flagged_tamara', 'Chair':'chair'}, inplace=True)
df1.head()

,ID,text,tag_tamara,comments_tamara,flagged_tamara
0,ParlaMint-SI_2013-03-04-SDZ6-Redna-11.u10,"Spoštovani predsednik Vlade, spoštovana minist...",Negative,"Based on the first part, in connection with th...",NaN
1,ParlaMint-SI_2017-03-21-SDZ7-Redna-28.u162,Dragi poslanke in poslanci! Danes ne bomo govo...,Negative,"Negative theme, negative sentiment, dissapoint...",NaN
2,ParlaMint-SI_2010-11-16-SDZ5-Izredna-33.u1,Spoštovane kolegice poslanke in kolegi poslanc...,P_Neutral,Procedural,NaN
3,ParlaMint-SI_2010-01-28-SDZ5-Redna-13.u172,"Hvala lepa za besedo, gospod podpredsednik. Sp...",M_Positive,"A little diss to the goverment, but overall po...",NaN
4,ParlaMint-SI_2021-09-21-SDZ8-Redna-25.u92,"Hvala za besedo, gospa podpredsednica. Gospe p...",M_Negative,"Very conflicting, but the sentiment is mostly ...",NaN

In [6]:
df2.rename(columns={'Text':'text', 'Annotation': 'tag_katja', 'Comments': 'comments_katja','Flag':'flagged_katja', 'Chair':'chair'}, inplace=True)
df2.head()

,ID,text,tag_katja,comments_katja,flagged_katja,chair
0,ParlaMint-SI_2013-03-04-SDZ6-Redna-11.u10,"Spoštovani predsednik Vlade, spoštovana minist...",Negative,While the tone is not especially strong as wit...,NaN,False
1,ParlaMint-SI_2017-03-21-SDZ7-Redna-28.u162,Dragi poslanke in poslanci! Danes ne bomo govo...,Negative,First part explaining why the current state is...,NaN,False
2,ParlaMint-SI_2010-11-16-SDZ5-Izredna-33.u1,Spoštovane kolegice poslanke in kolegi poslanc...,P_Neutral,NaN,NaN,True
3,ParlaMint-SI_2010-01-28-SDZ5-Redna-13.u172,"Hvala lepa za besedo, gospod podpredsednik. Sp...",M_Negative,The very first two sentences seem supportive a...,1.0,False
4,ParlaMint-SI_2021-09-21-SDZ8-Redna-25.u92,"Hvala za besedo, gospa podpredsednica. Gospe p...",M_Negative,"Negative topic, but the speaker and their PS s...",1.0,False

In [7]:
merged_df = pd.merge(df1, df2, on=['ID', 'text'])
merged_df.head()

,ID,text,tag_tamara,comments_tamara,flagged_tamara,tag_katja,comments_katja,flagged_katja,chair
0,ParlaMint-SI_2013-03-04-SDZ6-Redna-11.u10,"Spoštovani predsednik Vlade, spoštovana minist...",Negative,"Based on the first part, in connection with th...",NaN,Negative,While the tone is not especially strong as wit...,NaN,False
1,ParlaMint-SI_2017-03-21-SDZ7-Redna-28.u162,Dragi poslanke in poslanci! Danes ne bomo govo...,Negative,"Negative theme, negative sentiment, dissapoint...",NaN,Negative,First part explaining why the current state is...,NaN,False
2,ParlaMint-SI_2010-11-16-SDZ5-Izredna-33.u1,Spoštovane kolegice poslanke in kolegi poslanc...,P_Neutral,Procedural,NaN,P_Neutral,NaN,NaN,True
3,ParlaMint-SI_2010-01-28-SDZ5-Redna-13.u172,"Hvala lepa za besedo, gospod podpredsednik. Sp...",M_Positive,"A little diss to the goverment, but overall po...",NaN,M_Negative,The very first two sentences seem supportive a...,1.0,False
4,ParlaMint-SI_2021-09-21-SDZ8-Redna-25.u92,"Hvala za besedo, gospa podpredsednica. Gospe p...",M_Negative,"Very conflicting, but the sentiment is mostly ...",NaN,M_Negative,"Negative topic, but the speaker and their PS s...",1.0,False

In [8]:
order = ['ID', 'text', 'tag_tamara', 'tag_katja', 'comments_tamara', 'comments_katja', 'flagged_tamara', 'flagged_katja', 'chair']

In [9]:
merged_df = merged_df[order]
merged_df['final_tag'] = ''
merged_df.head()

,ID,text,tag_tamara,tag_katja,comments_tamara,comments_katja,flagged_tamara,flagged_katja,chair,final_tag
0,ParlaMint-SI_2013-03-04-SDZ6-Redna-11.u10,"Spoštovani predsednik Vlade, spoštovana minist...",Negative,Negative,"Based on the first part, in connection with th...",While the tone is not especially strong as wit...,NaN,NaN,False,
1,ParlaMint-SI_2017-03-21-SDZ7-Redna-28.u162,Dragi poslanke in poslanci! Danes ne bomo govo...,Negative,Negative,"Negative theme, negative sentiment, dissapoint...",First part explaining why the current state is...,NaN,NaN,False,
2,ParlaMint-SI_2010-11-16-SDZ5-Izredna-33.u1,Spoštovane kolegice poslanke in kolegi poslanc...,P_Neutral,P_Neutral,Procedural,NaN,NaN,NaN,True,
3,ParlaMint-SI_2010-01-28-SDZ5-Redna-13.u172,"Hvala lepa za besedo, gospod podpredsednik. Sp...",M_Positive,M_Negative,"A little diss to the goverment, but overall po...",The very first two sentences seem supportive a...,NaN,1.0,False,
4,ParlaMint-SI_2021-09-21-SDZ8-Redna-25.u92,"Hvala za besedo, gospa podpredsednica. Gospe p...",M_Negative,M_Negative,"Very conflicting, but the sentiment is mostly ...","Negative topic, but the speaker and their PS s...",NaN,1.0,False,

In [11]:
merged_df.to_csv("Main3/Main3_combined.csv", encoding ='utf-8', index=False)