In [18]:
import csv
import pandas as pd

# Dataset merge and prep for analysis

Checking and renaming the datasets to merge them into one combined dataset and get it ready for (IAA) analysis.

Change folder (Test1, Test2, Main1, Main2...) to process other datasets as they come.

In [27]:
df1 = pd.read_excel("Main4/Main4_Tamara.xlsx")
df2 = pd.read_excel("Main4/Main4_Katja.xlsx")

In [28]:
df1 = df1.drop(columns=['Annotation values', 'Chair'])
df2 = df2.drop(columns='Annotation values')

In [29]:
df1.rename(columns={'Text':'text', 'Annotation': 'tag_tamara', 'Comments': 'comments_tamara','Flag':'flagged_tamara', 'Chair':'chair'}, inplace=True)
df1.head()
#len(df1)

,ID,text,tag_tamara,comments_tamara,flagged_tamara
0,ParlaMint-SI_2013-11-22-SDZ6-Redna-19.u93,"Hvala lepa tudi vam. Gospod Mihael Prevc, nasl...",P_Neutral,Procedural,NaN
1,ParlaMint-SI_2015-01-26-SDZ7-Redna-04.u152,"Hvala lepa za besedo. Spoštovane ministrice, m...",M_Negative,"Divided, valid questions.",NaN
2,ParlaMint-SI_2006-11-29-SDZ4-Redna-22.u165,"Kolega Slavko Gaber, v temu trenutku vam lahko...",P_Neutral,Procedural. I guess could be N_Neutral but its...,NaN
3,ParlaMint-SI_2001-03-01-SDZ3-Redna-03.u116,"Moram replicirati. Kolega Moge - ne moram, amp...",M_Positive,"Clealry a defensive response, but positive.",NaN
4,ParlaMint-SI_2021-12-16-SDZ8-Redna-28.u22,"Hvala za besedo, podpredsednica. Lep pozdrav v...",Positive,"Support, but also positive parts presented.",NaN

In [30]:
df2.rename(columns={'Text':'text', 'Annotation': 'tag_katja', 'Comments': 'comments_katja','Flag':'flagged_katja', 'Chair':'chair'}, inplace=True)
#len(df2)
df2.head()

,ID,text,tag_katja,comments_katja,flagged_katja,chair
0,ParlaMint-SI_2013-11-22-SDZ6-Redna-19.u93,"Hvala lepa tudi vam. Gospod Mihael Prevc, nasl...",P_Neutral,NaN,NaN,True
1,ParlaMint-SI_2015-01-26-SDZ7-Redna-04.u152,"Hvala lepa za besedo. Spoštovane ministrice, m...",M_Negative,"First two sentences seem to be positive, howev...",1.0,False
2,ParlaMint-SI_2006-11-29-SDZ4-Redna-22.u165,"Kolega Slavko Gaber, v temu trenutku vam lahko...",P_Neutral,NaN,NaN,True
3,ParlaMint-SI_2001-03-01-SDZ3-Redna-03.u116,"Moram replicirati. Kolega Moge - ne moram, amp...",Negative,Speaker presents arguments on why the proposal...,NaN,False
4,ParlaMint-SI_2021-12-16-SDZ8-Redna-28.u22,"Hvala za besedo, podpredsednica. Lep pozdrav v...",Positive,At the end there is a slight negative connotat...,NaN,False

In [31]:
merged_df = pd.merge(df1, df2, on=['ID', 'text'])
len(merged_df)
merged_df.head()

,ID,text,tag_tamara,comments_tamara,flagged_tamara,tag_katja,comments_katja,flagged_katja,chair
0,ParlaMint-SI_2013-11-22-SDZ6-Redna-19.u93,"Hvala lepa tudi vam. Gospod Mihael Prevc, nasl...",P_Neutral,Procedural,NaN,P_Neutral,NaN,NaN,True
1,ParlaMint-SI_2015-01-26-SDZ7-Redna-04.u152,"Hvala lepa za besedo. Spoštovane ministrice, m...",M_Negative,"Divided, valid questions.",NaN,M_Negative,"First two sentences seem to be positive, howev...",1.0,False
2,ParlaMint-SI_2006-11-29-SDZ4-Redna-22.u165,"Kolega Slavko Gaber, v temu trenutku vam lahko...",P_Neutral,Procedural. I guess could be N_Neutral but its...,NaN,P_Neutral,NaN,NaN,True
3,ParlaMint-SI_2001-03-01-SDZ3-Redna-03.u116,"Moram replicirati. Kolega Moge - ne moram, amp...",M_Positive,"Clealry a defensive response, but positive.",NaN,Negative,Speaker presents arguments on why the proposal...,NaN,False
4,ParlaMint-SI_2021-12-16-SDZ8-Redna-28.u22,"Hvala za besedo, podpredsednica. Lep pozdrav v...",Positive,"Support, but also positive parts presented.",NaN,Positive,At the end there is a slight negative connotat...,NaN,False

In [32]:
order = ['ID', 'text', 'tag_tamara', 'tag_katja', 'comments_tamara', 'comments_katja', 'flagged_tamara', 'flagged_katja', 'chair']

In [33]:
merged_df = merged_df[order]
merged_df['final_tag'] = ''
merged_df.head()

,ID,text,tag_tamara,tag_katja,comments_tamara,comments_katja,flagged_tamara,flagged_katja,chair,final_tag
0,ParlaMint-SI_2013-11-22-SDZ6-Redna-19.u93,"Hvala lepa tudi vam. Gospod Mihael Prevc, nasl...",P_Neutral,P_Neutral,Procedural,NaN,NaN,NaN,True,
1,ParlaMint-SI_2015-01-26-SDZ7-Redna-04.u152,"Hvala lepa za besedo. Spoštovane ministrice, m...",M_Negative,M_Negative,"Divided, valid questions.","First two sentences seem to be positive, howev...",NaN,1.0,False,
2,ParlaMint-SI_2006-11-29-SDZ4-Redna-22.u165,"Kolega Slavko Gaber, v temu trenutku vam lahko...",P_Neutral,P_Neutral,Procedural. I guess could be N_Neutral but its...,NaN,NaN,NaN,True,
3,ParlaMint-SI_2001-03-01-SDZ3-Redna-03.u116,"Moram replicirati. Kolega Moge - ne moram, amp...",M_Positive,Negative,"Clealry a defensive response, but positive.",Speaker presents arguments on why the proposal...,NaN,NaN,False,
4,ParlaMint-SI_2021-12-16-SDZ8-Redna-28.u22,"Hvala za besedo, podpredsednica. Lep pozdrav v...",Positive,Positive,"Support, but also positive parts presented.",At the end there is a slight negative connotat...,NaN,NaN,False,

In [34]:
merged_df.to_csv("Main4/Main4_combined.csv", encoding ='utf-8', index=False)