In [39]:
import csv
import pandas as pd

In [40]:
# Open all of the datasets from individual annotation phases and merge together
main1 = pd.read_csv("./Main1/Main1_combined.csv", delimiter=",", encoding="utf-8")
main2 = pd.read_csv("./Main2/Main2_combined.csv", delimiter=",", encoding="utf-8")
main3 = pd.read_csv("./Main3/Main3_combined.csv", delimiter=",", encoding="utf-8")
main4 = pd.read_csv("./Main4/Main4_combined.csv", delimiter=",", encoding="utf-8")
main5 = pd.read_csv("./Main5/Main5_combined.csv", delimiter=",", encoding="utf-8")

In [41]:
df = pd.concat([main1, main2, main3, main4, main5], ignore_index=True)
df

,ID,text,tag_tamara,tag_katja,comments_tamara,comments_katja,flagged_tamara,flagged_katja,chair,final_tag
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,"Ni replike na repliko. Gospa ministrica, potem...",N_Neutral,N_Neutral,"Procedural, but he is denying her the ability ...","Procedural, however still has relatively stron...",NaN,NaN,True,NaN
1,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,P_Neutral,P_Neutral,Procedural.,NaN,NaN,NaN,True,NaN
2,ParlaMint-SI_2011-06-21-SDZ5-Redna-29.u178,"Hvala lepa. V bistvu se strinjam z vami, gospo...",Positive,Positive,Speaker is stating positive changes and support.,"Speech seems to be fairly positive, as the spe...",NaN,NaN,False,NaN
3,ParlaMint-SI_2020-09-21-SDZ8-Redna-20.u276,"Hvala, podpredsednik. Hvala tudi za vprašanje,...",Negative,Negative,"Negative opinion of the topic, the work done, ...",Could also be Mixed sentiment due to the last ...,NaN,True,False,NaN
4,ParlaMint-SI_2009-11-18-SDZ5-Redna-11.u120,Besedo ima gospod Silven Majhenič.,P_Neutral,P_Neutral,Procedural,NaN,NaN,NaN,True,NaN
...,...,...,...,...,...,...,...,...,...,...
995,ParlaMint-SI_2015-05-13-SDZ7-Izredna-13.u1,Spoštovani kolegice poslanke in kolegi poslanc...,P_Neutral,P_Neutral,Procedural,NaN,NaN,NaN,True,NaN
996,ParlaMint-SI_2001-10-05-SDZ3-Redna-08.u73,"O amandmaju k 26. členu nismo glasovali, ker s...",P_Neutral,N_Neutral,Procedural,NaN,NaN,NaN,False,NaN
997,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.u95,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",P_Neutral,P_Neutral,Procedural,NaN,NaN,NaN,True,NaN
998,ParlaMint-SI_2009-03-27-SDZ5-Redna-04.u199,Hvala lepa. Besedo ima mag. Branko Grims. Prosim.,P_Neutral,P_Neutral,Procedural,NaN,NaN,NaN,True,NaN
999,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.u17,Hvala lepa. Zadnji bo stališče Poslanske skupi...,P_Neutral,P_Neutral,Procedural,NaN,NaN,NaN,True,NaN

In [42]:
#Full dataset with all annotations.
df.to_csv('../Datasets/Annotations.csv')

## Cohen's Kappa 

### CK - 6-level, full annotations

In [43]:
from sklearn.metrics import cohen_kappa_score
annotator1 = df['tag_tamara']
annotator2 = df['tag_katja']
cohen_kappa_score(annotator1, annotator2)

np.float64(0.7246235253665854)

### 6-level, non-procedural only

In [44]:
non_procedural = df[df['chair'] == False]
procedural = df[df['chair'] == True]

annotator1_non = non_procedural['tag_tamara']
annotator2_non = non_procedural['tag_katja']
cohen_kappa_score(annotator1_non, annotator2_non)

np.float64(0.5718861880535142)

### 3-level, full annotations

In [45]:
df.loc[(df['tag_tamara'] == 'Negative') | (df['tag_tamara'] == 'M_Negative'), 'sent_tamara'] = 'Negative'
df.loc[(df['tag_tamara'] == 'Positive') | (df['tag_tamara'] == 'M_Positive'), 'sent_tamara'] = 'Positive'
df.loc[(df['tag_tamara'] == 'P_Neutral') | (df['tag_tamara'] == 'N_Neutral'), 'sent_tamara'] = 'Neutral'

In [46]:
df.loc[(df['tag_katja'] == 'Negative') | (df['tag_katja'] == 'M_Negative'), 'sent_katja'] = 'Negative'
df.loc[(df['tag_katja'] == 'Positive') | (df['tag_katja'] == 'M_Positive'), 'sent_katja'] = 'Positive'
df.loc[(df['tag_katja'] == 'P_Neutral') | (df['tag_katja'] == 'N_Neutral'), 'sent_katja'] = 'Neutral'

In [48]:
annotator1 = df['sent_tamara']
annotator2 = df['sent_katja']
cohen_kappa_score(annotator1, annotator2)

np.float64(0.8529471690558322)

### 3-level non-procedural Kappa score

In [49]:
df_non = df[df['chair'] != True]

In [50]:
df_non.loc[(df_non['tag_tamara'] == 'Negative') | (df_non['tag_tamara'] == 'M_Negative'), 'sent_tamara'] = 'Negative'
df_non.loc[(df_non['tag_tamara'] == 'Positive') | (df_non['tag_tamara'] == 'M_Positive'), 'sent_tamara'] = 'Positive'
df_non.loc[(df_non['tag_tamara'] == 'P_Neutral') | (df_non['tag_tamara'] == 'N_Neutral'), 'sent_tamara'] = 'Neutral'

In [51]:
df_non.loc[(df_non['tag_katja'] == 'Negative') | (df_non['tag_katja'] == 'M_Negative'), 'sent_katja'] = 'Negative'
df_non.loc[(df_non['tag_katja'] == 'Positive') | (df_non['tag_katja'] == 'M_Positive'), 'sent_katja'] = 'Positive'
df_non.loc[(df_non['tag_katja'] == 'P_Neutral') | (df_non['tag_katja'] == 'N_Neutral'), 'sent_katja'] = 'Neutral'

In [52]:
df_non

,ID,text,tag_tamara,tag_katja,comments_tamara,comments_katja,flagged_tamara,flagged_katja,chair,final_tag,sent_tamara,sent_katja
2,ParlaMint-SI_2011-06-21-SDZ5-Redna-29.u178,"Hvala lepa. V bistvu se strinjam z vami, gospo...",Positive,Positive,Speaker is stating positive changes and support.,"Speech seems to be fairly positive, as the spe...",NaN,NaN,False,NaN,Positive,Positive
3,ParlaMint-SI_2020-09-21-SDZ8-Redna-20.u276,"Hvala, podpredsednik. Hvala tudi za vprašanje,...",Negative,Negative,"Negative opinion of the topic, the work done, ...",Could also be Mixed sentiment due to the last ...,NaN,True,False,NaN,Negative,Negative
6,ParlaMint-SI_2021-10-18-SDZ8-Redna-26.u273,"Kompliment na koncu je nepotreben, ker imava r...",Negative,Negative,A tiny bit combative towards the opponent.,NaN,NaN,NaN,False,NaN,Negative,Negative
10,ParlaMint-SI_2016-07-11-SDZ7-Redna-21.u2,Spoštovani poslanke in poslanci! Aprila tega l...,P_Neutral,P_Neutral,A request for something.,Speaker calls for action and acceptance of the...,NaN,True,False,NaN,Neutral,Neutral
13,ParlaMint-SI_2004-03-25-SDZ3-Redna-35.u233,"Hvala lepa, gospod predsedujoči. Ta program - ...",Negative,Negative,"Very clear negative, spiteful sentiment.",Hahahahahahaha,NaN,NaN,False,NaN,Negative,Negative
...,...,...,...,...,...,...,...,...,...,...,...,...
990,ParlaMint-SI_2015-11-18-SDZ7-Redna-13.u40,"Hvala lepa za besedo, spoštovani predsednik. S...",P_Neutral,P_Neutral,Procedural and just facts.,NaN,NaN,NaN,False,NaN,Neutral,Neutral
991,ParlaMint-SI_2021-03-04-SDZ8-Izredna-64.u150,Najlepša hvala. Da zaključim na hitro. Oznaka ...,M_Negative,Negative,A bit ironic. Could be just N.,NaN,1.0,NaN,False,NaN,Negative,Negative
993,ParlaMint-SI_2020-11-16-SDZ8-Izredna-48.u284,"Hvala za besedo, gospod podpredsednik. Hvala t...",N_Neutral,Negative,"Just questionns, but negative theme.",NaN,NaN,NaN,False,NaN,Neutral,Negative
994,ParlaMint-SI_2014-03-03-SDZ6-Redna-22.u242,"Hvala za besedo, predsedujoča. Pozdrav vsem pr...",M_Negative,M_Negative,Could also be Negative.,Could also be Negative,1.0,NaN,False,NaN,Negative,Negative
996,ParlaMint-SI_2001-10-05-SDZ3-Redna-08.u73,"O amandmaju k 26. členu nismo glasovali, ker s...",P_Neutral,N_Neutral,Procedural,NaN,NaN,NaN,False,NaN,Neutral,Neutral

In [53]:
annotator1 = df_non['sent_tamara']
annotator2 = df_non['sent_katja']
cohen_kappa_score(annotator1, annotator2)

np.float64(0.7446384039900249)

## Krippendorfs Alpha

### 6-level full

In [54]:
import krippendorff
import numpy as np

In [55]:
columns_to_keep = ['tag_tamara', 'tag_katja']
alpha = df[columns_to_keep]
alpha

    tag_tamara  tag_katja
0    N_Neutral  N_Neutral
1    P_Neutral  P_Neutral
2     Positive   Positive
3     Negative   Negative
4    P_Neutral  P_Neutral
..         ...        ...
995  P_Neutral  P_Neutral
996  P_Neutral  N_Neutral
997  P_Neutral  P_Neutral
998  P_Neutral  P_Neutral
999  P_Neutral  P_Neutral

[1000 rows x 2 columns]

In [56]:
alpha = alpha.dropna()
len(df)

1000

In [57]:
unique_labels = pd.unique(alpha[['tag_tamara', 'tag_katja']].values.ravel())

# Create a mapping of labels to consistent numeric codes
label_to_code = {label: idx for idx, label in enumerate(unique_labels)}

# Map the labels to numeric codes for both annotators
alpha['tag_tamara_codes'] = df['tag_tamara'].map(label_to_code)
alpha['tag_katja_codes'] = df['tag_katja'].map(label_to_code)
alpha

    tag_tamara  tag_katja  tag_tamara_codes  tag_katja_codes
0    N_Neutral  N_Neutral                 0                0
1    P_Neutral  P_Neutral                 1                1
2     Positive   Positive                 2                2
3     Negative   Negative                 3                3
4    P_Neutral  P_Neutral                 1                1
..         ...        ...               ...              ...
995  P_Neutral  P_Neutral                 1                1
996  P_Neutral  N_Neutral                 1                0
997  P_Neutral  P_Neutral                 1                1
998  P_Neutral  P_Neutral                 1                1
999  P_Neutral  P_Neutral                 1                1

[1000 rows x 4 columns]

In [58]:
data_array = alpha[['tag_tamara_codes', 'tag_katja_codes']].to_numpy().T
alpha_calc = krippendorff.alpha(reliability_data=data_array, level_of_measurement='nominal')
print(f"Krippendorff's alpha (nominal): {alpha_calc}")

Krippendorff's alpha (nominal): 0.7243739511257948

### non procedural 6-level

In [59]:
columns_keep = ['tag_tamara', 'tag_katja']

alpha_non = df_non[columns_keep]
alpha_non

     tag_tamara   tag_katja
2      Positive    Positive
3      Negative    Negative
6      Negative    Negative
10    P_Neutral   P_Neutral
13     Negative    Negative
..          ...         ...
990   P_Neutral   P_Neutral
991  M_Negative    Negative
993   N_Neutral    Negative
994  M_Negative  M_Negative
996   P_Neutral   N_Neutral

[480 rows x 2 columns]

In [60]:
labels_non = pd.unique(alpha_non[['tag_tamara', 'tag_katja']].values.ravel())

# Create a mapping of labels to consistent numeric codes
code_non = {label: idx for idx, label in enumerate(labels_non)}

# Map the labels to numeric codes for both annotators
alpha_non['tag_tamara_codes'] = df_non['tag_tamara'].map(code_non)
alpha_non['tag_katja_codes'] = df_non['tag_katja'].map(code_non)
alpha_non

/var/folders/l_/t5l44v1s7d9168_x8bm5ly0h0000gn/T/ipykernel_2944/2740411005.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  alpha_non['tag_tamara_codes'] = df_non['tag_tamara'].map(code_non)
/var/folders/l_/t5l44v1s7d9168_x8bm5ly0h0000gn/T/ipykernel_2944/2740411005.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  alpha_non['tag_katja_codes'] = df_non['tag_katja'].map(code_non)

     tag_tamara   tag_katja  tag_tamara_codes  tag_katja_codes
2      Positive    Positive                 0                0
3      Negative    Negative                 1                1
6      Negative    Negative                 1                1
10    P_Neutral   P_Neutral                 2                2
13     Negative    Negative                 1                1
..          ...         ...               ...              ...
990   P_Neutral   P_Neutral                 2                2
991  M_Negative    Negative                 5                1
993   N_Neutral    Negative                 4                1
994  M_Negative  M_Negative                 5                5
996   P_Neutral   N_Neutral                 2                4

[480 rows x 4 columns]

In [61]:
data_array_non = alpha_non[['tag_tamara_codes', 'tag_katja_codes']].to_numpy().T
alpha_non_calc = krippendorff.alpha(reliability_data=data_array_non, level_of_measurement='nominal')
print(f"Krippendorff's alpha (nominal): {alpha_non_calc}")

Krippendorff's alpha (nominal): 0.5708671962890717

### 3-level all annotations

In [62]:
columns_sent = ['sent_tamara', 'sent_katja']
sent = df[columns_sent]
sent

    sent_tamara sent_katja
0       Neutral    Neutral
1       Neutral    Neutral
2      Positive   Positive
3      Negative   Negative
4       Neutral    Neutral
..          ...        ...
995     Neutral    Neutral
996     Neutral    Neutral
997     Neutral    Neutral
998     Neutral    Neutral
999     Neutral    Neutral

[1000 rows x 2 columns]

In [63]:
sent_labels = pd.unique(sent[['sent_tamara', 'sent_katja']].values.ravel())

# Create a mapping of labels to consistent numeric codes
code_sent = {label: idx for idx, label in enumerate(sent_labels)}

# Map the labels to numeric codes for both annotators
sent['sent_tamara_codes'] = df['sent_tamara'].map(code_sent)
sent['sent_katja_codes'] = df['sent_katja'].map(code_sent)
sent

/var/folders/l_/t5l44v1s7d9168_x8bm5ly0h0000gn/T/ipykernel_2944/2663344781.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sent['sent_tamara_codes'] = df['sent_tamara'].map(code_sent)
/var/folders/l_/t5l44v1s7d9168_x8bm5ly0h0000gn/T/ipykernel_2944/2663344781.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sent['sent_katja_codes'] = df['sent_katja'].map(code_sent)

    sent_tamara sent_katja  sent_tamara_codes  sent_katja_codes
0       Neutral    Neutral                  0                 0
1       Neutral    Neutral                  0                 0
2      Positive   Positive                  1                 1
3      Negative   Negative                  2                 2
4       Neutral    Neutral                  0                 0
..          ...        ...                ...               ...
995     Neutral    Neutral                  0                 0
996     Neutral    Neutral                  0                 0
997     Neutral    Neutral                  0                 0
998     Neutral    Neutral                  0                 0
999     Neutral    Neutral                  0                 0

[1000 rows x 4 columns]

In [64]:
data_sent = sent[['sent_tamara_codes', 'sent_katja_codes']].to_numpy().T
alpha_sent = krippendorff.alpha(reliability_data=data_sent, level_of_measurement='nominal')
print(f"Krippendorff's alpha (nominal): {alpha_sent}")

Krippendorff's alpha (nominal): 0.8529056360891271

### 3-level non procedural

In [65]:
columns_sent = ['sent_tamara', 'sent_katja']
sent_non = df_non[columns_sent]
sent_non

    sent_tamara sent_katja
2      Positive   Positive
3      Negative   Negative
6      Negative   Negative
10      Neutral    Neutral
13     Negative   Negative
..          ...        ...
990     Neutral    Neutral
991    Negative   Negative
993     Neutral   Negative
994    Negative   Negative
996     Neutral    Neutral

[480 rows x 2 columns]

In [66]:
sent_labels_non = pd.unique(sent_non[['sent_tamara', 'sent_katja']].values.ravel())

# Create a mapping of labels to consistent numeric codes
code_sent_non = {label: idx for idx, label in enumerate(sent_labels_non)}

# Map the labels to numeric codes for both annotators
sent_non['sent_tamara_codes'] = df_non['sent_tamara'].map(code_sent_non)
sent_non['sent_katja_codes'] = df['sent_katja'].map(code_sent_non)
sent_non

/var/folders/l_/t5l44v1s7d9168_x8bm5ly0h0000gn/T/ipykernel_2944/1619895236.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sent_non['sent_tamara_codes'] = df_non['sent_tamara'].map(code_sent_non)
/var/folders/l_/t5l44v1s7d9168_x8bm5ly0h0000gn/T/ipykernel_2944/1619895236.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sent_non['sent_katja_codes'] = df['sent_katja'].map(code_sent_non)

    sent_tamara sent_katja  sent_tamara_codes  sent_katja_codes
2      Positive   Positive                  0                 0
3      Negative   Negative                  1                 1
6      Negative   Negative                  1                 1
10      Neutral    Neutral                  2                 2
13     Negative   Negative                  1                 1
..          ...        ...                ...               ...
990     Neutral    Neutral                  2                 2
991    Negative   Negative                  1                 1
993     Neutral   Negative                  2                 1
994    Negative   Negative                  1                 1
996     Neutral    Neutral                  2                 2

[480 rows x 4 columns]

In [67]:
data_sent_non = sent_non[['sent_tamara_codes', 'sent_katja_codes']].to_numpy().T
alpha_sent_non = krippendorff.alpha(reliability_data=data_sent_non, level_of_measurement='nominal')
print(f"Krippendorff's alpha (nominal): {alpha_sent_non}")

Krippendorff's alpha (nominal): 0.7446369430991728

## Aggregation rates

### 6-level

In [70]:
#Add new column 'agreement' with value True if there was agreement between the annotators (i.e., if both annotators used the same label).
df['agreement'] = df['tag_tamara'] == df['tag_katja']
agreement = df[df['agreement'] == True]
len_agreement = len(agreement)
len_agreement

819

In [71]:
agreement_percentage = (len_agreement / len(df)) * 100
agreement_percentage

81.89999999999999

### 6-level non procedural

In [73]:
non = df[df['chair'] == False]
non.head()
len(non)

480

In [74]:
non_agreement = non[non['agreement'] == True]
non_agreement.head()
len(non_agreement)

338

In [75]:
non_agree_percent = (len(non_agreement) / len(non)) * 100
non_agree_percent

70.41666666666667

### 3-level full annotations

In [78]:
#Add new column, but on 'sent' columns (3-level data)
df['agreement'] = df['sent_tamara'] == df['sent_katja']
agreement_level = df[df['agreement'] == True]
len(agreement_level)

917

In [79]:
agreement_percent = (len(agreement_level) / len(df)) * 100
agreement_percent

91.7

### 3-level nonprocedural

In [81]:
non_3level = df[df['chair'] == False]
len(non_3level)

480

In [82]:
non_3level_agree = non_3level[non_3level['agreement'] == True]
len(non_3level_agree)

416

In [83]:
df_speeches_ACC = (len(non_3level_agree) / len(non_3level)) * 100
df_speeches_ACC

86.66666666666667