In [1]:
import csv
import pandas as pd

# Dataset merge and prep for analysis

Checking and renaming the datasets to merge them into one combined dataset and get it ready for (IAA) analysis.

Change folder (Test1, Test2, Main1, Main2...) to process other datasets as they come.

In [2]:
df1 = pd.read_csv("Main5/Main5_Tamara.csv")
df2 = pd.read_csv("Main5/Main5_Katja.csv")

In [3]:
df1 = df1.drop(columns=['Annotation values', 'Chair'])
df2 = df2.drop(columns='Annotation values')

In [4]:
df1.rename(columns={'Text':'text', 'Annotation': 'tag_tamara', 'Comments': 'comments_tamara','Flag':'flagged_tamara', 'Chair':'chair'}, inplace=True)
df1.head()
#len(df1)

,ID,text,tag_tamara,comments_tamara,flagged_tamara
0,ParlaMint-SI_2010-04-22-SDZ5-Redna-16.u265,"Hvala lepa. Besedo ima gospod Jožef Jerovšek, ...",P_Neutral,Procedural,NaN
1,ParlaMint-SI_2003-05-28-SDZ3-Redna-26.u129,"Poglejte, v vaši obrazložitvi okoli 26. člena,...",M_Positive,"A bit loaded at first, but relises his mistake.",NaN
2,ParlaMint-SI_2019-11-21-SDZ8-Redna-13.u243,"Hvala lepa, predsedujoči, za besedo. Jaz bi že...",Positive,Support.,NaN
3,ParlaMint-SI_2016-10-18-SDZ7-Redna-23.u99,"Hvala lepa. Predlagateljica gospa Jelka Godec,...",P_Neutral,Procedural,NaN
4,ParlaMint-SI_2014-12-04-SDZ7-Izredna-07.u72,Hvala lepa. Gospod Jožef Horvat bo predstavil ...,P_Neutral,Procedural,NaN

In [5]:
df2.rename(columns={'Text':'text', 'Annotation': 'tag_katja', 'Comments': 'comments_katja','Flag':'flagged_katja', 'Chair':'chair'}, inplace=True)
#len(df2)
df2.head()

,ID,text,tag_katja,comments_katja,flagged_katja,chair
0,ParlaMint-SI_2010-04-22-SDZ5-Redna-16.u265,"Hvala lepa. Besedo ima gospod Jožef Jerovšek, ...",P_Neutral,NaN,NaN,True
1,ParlaMint-SI_2003-05-28-SDZ3-Redna-26.u129,"Poglejte, v vaši obrazložitvi okoli 26. člena,...",Negative,Sarcastic and negative,NaN,False
2,ParlaMint-SI_2019-11-21-SDZ8-Redna-13.u243,"Hvala lepa, predsedujoči, za besedo. Jaz bi že...",Positive,NaN,NaN,False
3,ParlaMint-SI_2016-10-18-SDZ7-Redna-23.u99,"Hvala lepa. Predlagateljica gospa Jelka Godec,...",P_Neutral,NaN,NaN,True
4,ParlaMint-SI_2014-12-04-SDZ7-Izredna-07.u72,Hvala lepa. Gospod Jožef Horvat bo predstavil ...,P_Neutral,NaN,NaN,True

In [6]:
merged_df = pd.merge(df1, df2, on=['ID', 'text'])
len(merged_df)
merged_df.head()

,ID,text,tag_tamara,comments_tamara,flagged_tamara,tag_katja,comments_katja,flagged_katja,chair
0,ParlaMint-SI_2010-04-22-SDZ5-Redna-16.u265,"Hvala lepa. Besedo ima gospod Jožef Jerovšek, ...",P_Neutral,Procedural,NaN,P_Neutral,NaN,NaN,True
1,ParlaMint-SI_2003-05-28-SDZ3-Redna-26.u129,"Poglejte, v vaši obrazložitvi okoli 26. člena,...",M_Positive,"A bit loaded at first, but relises his mistake.",NaN,Negative,Sarcastic and negative,NaN,False
2,ParlaMint-SI_2019-11-21-SDZ8-Redna-13.u243,"Hvala lepa, predsedujoči, za besedo. Jaz bi že...",Positive,Support.,NaN,Positive,NaN,NaN,False
3,ParlaMint-SI_2016-10-18-SDZ7-Redna-23.u99,"Hvala lepa. Predlagateljica gospa Jelka Godec,...",P_Neutral,Procedural,NaN,P_Neutral,NaN,NaN,True
4,ParlaMint-SI_2014-12-04-SDZ7-Izredna-07.u72,Hvala lepa. Gospod Jožef Horvat bo predstavil ...,P_Neutral,Procedural,NaN,P_Neutral,NaN,NaN,True

In [7]:
order = ['ID', 'text', 'tag_tamara', 'tag_katja', 'comments_tamara', 'comments_katja', 'flagged_tamara', 'flagged_katja', 'chair']

In [8]:
merged_df = merged_df[order]
merged_df['final_tag'] = ''
merged_df.head()

,ID,text,tag_tamara,tag_katja,comments_tamara,comments_katja,flagged_tamara,flagged_katja,chair,final_tag
0,ParlaMint-SI_2010-04-22-SDZ5-Redna-16.u265,"Hvala lepa. Besedo ima gospod Jožef Jerovšek, ...",P_Neutral,P_Neutral,Procedural,NaN,NaN,NaN,True,
1,ParlaMint-SI_2003-05-28-SDZ3-Redna-26.u129,"Poglejte, v vaši obrazložitvi okoli 26. člena,...",M_Positive,Negative,"A bit loaded at first, but relises his mistake.",Sarcastic and negative,NaN,NaN,False,
2,ParlaMint-SI_2019-11-21-SDZ8-Redna-13.u243,"Hvala lepa, predsedujoči, za besedo. Jaz bi že...",Positive,Positive,Support.,NaN,NaN,NaN,False,
3,ParlaMint-SI_2016-10-18-SDZ7-Redna-23.u99,"Hvala lepa. Predlagateljica gospa Jelka Godec,...",P_Neutral,P_Neutral,Procedural,NaN,NaN,NaN,True,
4,ParlaMint-SI_2014-12-04-SDZ7-Izredna-07.u72,Hvala lepa. Gospod Jožef Horvat bo predstavil ...,P_Neutral,P_Neutral,Procedural,NaN,NaN,NaN,True,

In [11]:
merged_df.to_csv("Main5/Main5_combined.csv", encoding ='utf-8', index=False)