In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../Datasets/Development_data.csv', encoding='utf-8')
df.head()

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.1,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.2,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.3,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg382.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg383.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",True,P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...

# Sentence sentiment score aggregation - mean and median

Testing different aggregation methods (average, mean, etc), as well as investigating some key characteristics of the dataset (e.g., dispersion of the sentence sentiment scores within the utterance).

In [3]:
aggregation = df.groupby('ID')['annotation_sent'].agg(
    count='count',
    mean ='mean', 
    median='median',
    min='min', 
    max='max', 
    std='std',
).reset_index()

In [4]:
df = pd.merge(df, aggregation, on='ID', how='left')
df.head()

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,count,mean,median,min,max,std
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.1,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881,2.636969,2.240412,3.639261,0.720951
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.2,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881,2.636969,2.240412,3.639261,0.720951
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.3,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881,2.636969,2.240412,3.639261,0.720951
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg382.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.491818,3.340636,3.050227,4.084590,0.533497
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg383.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",True,P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.491818,3.340636,3.050227,4.084590,0.533497

In [5]:
#Checking the highest data dispersion by sorting the values by standard deviation score 
# count = df.sort_values(by = 'std', ascending=False)
#count.head()

In [6]:
df['diff_mean'] = abs(df['annotation_utt_score'] - df['mean'])
df['diff_median'] = abs(df['annotation_utt_score'] - df['median'])

df.head()

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,count,mean,median,min,max,std,diff_mean,diff_median
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.1,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881,2.636969,2.240412,3.639261,0.720951,0.838881,0.636969
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.2,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881,2.636969,2.240412,3.639261,0.720951,0.838881,0.636969
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.3,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881,2.636969,2.240412,3.639261,0.720951,0.838881,0.636969
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg382.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.491818,3.340636,3.050227,4.084590,0.533497,0.491818,0.340636
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg383.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",True,P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.491818,3.340636,3.050227,4.084590,0.533497,0.491818,0.340636

In [7]:
average_max = df.sort_values(by = 'diff_mean', ascending=False)
average_max.head(5)

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,count,mean,median,min,max,std,diff_mean,diff_median
7964,ParlaMint-SI_2021-02-02-SDZ8-Izredna-57.u240,ParlaMint-SI_2021-02-02-SDZ8-Izredna-57.seg736.1,"Predlagam, da se držimo zakona, kolega Reberšek.","Predlagam, da se držimo zakona, kolega Reberšek.","I suggest we stick to the law, Comrade Reberšek.",True,Negative,0.0,3.812022,{'Text_ID': 'ParlaMint-SI-en_2021-02-02-SDZ8-I...,1,3.812022,3.812022,3.812022,3.812022,NaN,3.812022,3.812022
1972,ParlaMint-SI_2009-07-10-SDZ5-Redna-08.u230,ParlaMint-SI_2009-07-10-SDZ5-Redna-08.seg683.2,Hvala lepa za besedo. Poslanci DeSUS predlagan...,Poslanci DeSUS predlagani rešitvi načeloma ne ...,"Members of the DeSUS do not, in principle, obj...",False,Negative,0.0,4.212517,{'Text_ID': 'ParlaMint-SI-en_2009-07-10-SDZ5-R...,5,3.352120,3.914229,2.023306,4.479039,1.181295,3.352120,3.914229
1971,ParlaMint-SI_2009-07-10-SDZ5-Redna-08.u230,ParlaMint-SI_2009-07-10-SDZ5-Redna-08.seg683.1,Hvala lepa za besedo. Poslanci DeSUS predlagan...,Hvala lepa za besedo.,Thank you so much for saying that.,False,Negative,0.0,3.914229,{'Text_ID': 'ParlaMint-SI-en_2009-07-10-SDZ5-R...,5,3.352120,3.914229,2.023306,4.479039,1.181295,3.352120,3.914229
1973,ParlaMint-SI_2009-07-10-SDZ5-Redna-08.u230,ParlaMint-SI_2009-07-10-SDZ5-Redna-08.seg683.3,Hvala lepa za besedo. Poslanci DeSUS predlagan...,"Glede na to, da je k ureditvi tega vprašanja p...",In view of the fact that the Government has al...,False,Negative,0.0,2.131510,{'Text_ID': 'ParlaMint-SI-en_2009-07-10-SDZ5-R...,5,3.352120,3.914229,2.023306,4.479039,1.181295,3.352120,3.914229
1974,ParlaMint-SI_2009-07-10-SDZ5-Redna-08.u230,ParlaMint-SI_2009-07-10-SDZ5-Redna-08.seg683.4,Hvala lepa za besedo. Poslanci DeSUS predlagan...,"Prepričani smo, da bo vladni predlog celovitej...",We are confident that the government proposal ...,False,Negative,0.0,4.479039,{'Text_ID': 'ParlaMint-SI-en_2009-07-10-SDZ5-R...,5,3.352120,3.914229,2.023306,4.479039,1.181295,3.352120,3.914229

In [8]:
median_max = df.sort_values(by ='diff_median', ascending=False)
median_max.head(5)

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,count,mean,median,min,max,std,diff_mean,diff_median
2749,ParlaMint-SI_2008-04-24-SDZ4-Redna-38.u232,ParlaMint-SI_2008-04-24-SDZ4-Redna-38.seg710.3,"Hvala lepa. Če se ne motim, je amandma, ki ga ...",Hvala lepa.,Thank you very much.,False,Negative,0.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2008-04-24-SDZ4-R...,3,2.893164,4.084590,0.510310,4.084590,2.063612,2.893164,4.084590
2748,ParlaMint-SI_2008-04-24-SDZ4-Redna-38.u232,ParlaMint-SI_2008-04-24-SDZ4-Redna-38.seg710.2,"Hvala lepa. Če se ne motim, je amandma, ki ga ...","Če se ne motim, je amandma, ki ga je Poslanska...","If I am not mistaken, the amendment tabled by ...",False,Negative,0.0,0.510310,{'Text_ID': 'ParlaMint-SI-en_2008-04-24-SDZ4-R...,3,2.893164,4.084590,0.510310,4.084590,2.063612,2.893164,4.084590
2747,ParlaMint-SI_2008-04-24-SDZ4-Redna-38.u232,ParlaMint-SI_2008-04-24-SDZ4-Redna-38.seg710.1,"Hvala lepa. Če se ne motim, je amandma, ki ga ...",Hvala lepa.,Thank you very much.,False,Negative,0.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2008-04-24-SDZ4-R...,3,2.893164,4.084590,0.510310,4.084590,2.063612,2.893164,4.084590
1975,ParlaMint-SI_2009-07-10-SDZ5-Redna-08.u230,ParlaMint-SI_2009-07-10-SDZ5-Redna-08.seg684.1,Hvala lepa za besedo. Poslanci DeSUS predlagan...,Zaradi navedenega bomo poslanci DeSUS podprli ...,"For this reason, Members of the DeSUS will sup...",False,Negative,0.0,2.023306,{'Text_ID': 'ParlaMint-SI-en_2009-07-10-SDZ5-R...,5,3.352120,3.914229,2.023306,4.479039,1.181295,3.352120,3.914229
1973,ParlaMint-SI_2009-07-10-SDZ5-Redna-08.u230,ParlaMint-SI_2009-07-10-SDZ5-Redna-08.seg683.3,Hvala lepa za besedo. Poslanci DeSUS predlagan...,"Glede na to, da je k ureditvi tega vprašanja p...",In view of the fact that the Government has al...,False,Negative,0.0,2.131510,{'Text_ID': 'ParlaMint-SI-en_2009-07-10-SDZ5-R...,5,3.352120,3.914229,2.023306,4.479039,1.181295,3.352120,3.914229

In [9]:
mean_diff = df['diff_mean'].mean()
median_diff = df['diff_median'].mean()

print(f"Average difference with mean: {mean_diff}")
print(f"Average difference with median: {median_diff}")

Average difference with mean: 1.4313146918812052
Average difference with median: 1.3735544539784275

In [10]:
df.to_csv('../Datasets/Aggregation_testing.csv', encoding='utf-8', index=False)

## Calculating differents weights and weighted average

The weights assigned determined by the following indicators:
<!-- This is currently just a test with contexts that could be important when considering sentiment in whole utterances -->
- the *position* of the sentence (e.g., if the sentence appears at the end of the utterance)
- the *length* of the sentences (the longer the sentence, the higher the weight?)
- lower weights for the *procedural* sentences (maybe based on the “Chair” value for the utterance to signify high possibility of procedural language in sentences).
    - e.g. *if chair = True & (value ≠ Neutral_P |  value ≠ Neutral_N ) → lower weights set*

In [11]:
df['position'] = df.groupby('ID').cumcount() + 1
#df['position_weight'] = df.groupby('ID')['position'].transform(lambda x: x.apply(lambda y: 1.5 if y == x.max() else 1 ))
df.head(3)

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,count,mean,median,min,max,std,diff_mean,diff_median,position
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.1,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881,2.636969,2.240412,3.639261,0.720951,0.838881,0.636969,1
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.2,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881,2.636969,2.240412,3.639261,0.720951,0.838881,0.636969,2
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.3,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881,2.636969,2.240412,3.639261,0.720951,0.838881,0.636969,3

In [12]:
df['position_max'] = df.groupby('ID')['position'].transform('max')
df.head()

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,count,mean,median,min,max,std,diff_mean,diff_median,position,position_max
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.1,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881,2.636969,2.240412,3.639261,0.720951,0.838881,0.636969,1,3
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.2,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881,2.636969,2.240412,3.639261,0.720951,0.838881,0.636969,2,3
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.3,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881,2.636969,2.240412,3.639261,0.720951,0.838881,0.636969,3,3
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg382.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.491818,3.340636,3.050227,4.084590,0.533497,0.491818,0.340636,1,3
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg383.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",True,P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.491818,3.340636,3.050227,4.084590,0.533497,0.491818,0.340636,2,3

In [13]:
def position_chair(row):
    chair = row['chair']
    position = row['position']
    max_position = row['position_max']
    if chair != True and position == max_position:
        return 1.5
    return 1

df['weight'] = df.apply(position_chair, axis=1)
df.drop(columns=['position_max'], inplace=True)
df.head(10)

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,count,mean,median,min,max,std,diff_mean,diff_median,position,weight
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.1,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881,2.636969,2.240412,3.639261,0.720951,0.838881,0.636969,1,1.0
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.2,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881,2.636969,2.240412,3.639261,0.720951,0.838881,0.636969,2,1.0
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.3,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881,2.636969,2.240412,3.639261,0.720951,0.838881,0.636969,3,1.0
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg382.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.491818,3.340636,3.050227,4.084590,0.533497,0.491818,0.340636,1,1.0
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg383.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",True,P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.491818,3.340636,3.050227,4.084590,0.533497,0.491818,0.340636,2,1.0
5,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg383.2,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,"Pripravi naj se Jože Tanko, za njim France Cuk...","Get Joze Tanko ready, behind him, France Tsukati.",True,P_Neutral,3.0,3.050227,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.491818,3.340636,3.050227,4.084590,0.533497,0.491818,0.340636,3,1.0
6,ParlaMint-SI_2011-06-21-SDZ5-Redna-29.u178,ParlaMint-SI_2011-06-21-SDZ5-Redna-29.seg631.1,"Hvala lepa. V bistvu se strinjam z vami, gospo...",Hvala lepa.,Thank you very much.,False,Positive,5.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-21-SDZ5-R...,15,3.235311,3.166192,2.148438,4.510695,0.757523,1.764689,1.833808,1,1.0
7,ParlaMint-SI_2011-06-21-SDZ5-Redna-29.u178,ParlaMint-SI_2011-06-21-SDZ5-Redna-29.seg632.1,"Hvala lepa. V bistvu se strinjam z vami, gospo...","V bistvu se strinjam z vami, gospod Gorenak.","In fact, I agree with you, Mr. Gorenak.",False,Positive,5.0,4.434103,{'Text_ID': 'ParlaMint-SI-en_2011-06-21-SDZ5-R...,15,3.235311,3.166192,2.148438,4.510695,0.757523,1.764689,1.833808,2,1.0
8,ParlaMint-SI_2011-06-21-SDZ5-Redna-29.u178,ParlaMint-SI_2011-06-21-SDZ5-Redna-29.seg632.2,"Hvala lepa. V bistvu se strinjam z vami, gospo...","Mislim, da nekateri ukrepi v preteklosti niso ...",I think that some of the measures in the past ...,False,Positive,5.0,2.148438,{'Text_ID': 'ParlaMint-SI-en_2011-06-21-SDZ5-R...,15,3.235311,3.166192,2.148438,4.510695,0.757523,1.764689,1.833808,3,1.0
9,ParlaMint-SI_2011-06-21-SDZ5-Redna-29.u178,ParlaMint-SI_2011-06-21-SDZ5-Redna-29.seg633.1,"Hvala lepa. V bistvu se strinjam z vami, gospo...",Naše ministrstvo je namreč zaprosilo vse perso...,Our ministry has requested all the personal co...,False,Positive,5.0,2.482481,{'Text_ID': 'ParlaMint-SI-en_2011-06-21-SDZ5-R...,15,3.235311,3.166192,2.148438,4.510695,0.757523,1.764689,1.833808,4,1.0

In [14]:
df['weighted_score'] = df['annotation_sent'] * df['weight']
df['weighted_average'] = df.groupby('ID')['weighted_score'].transform('sum') / df.groupby('ID')['weight'].transform('sum')
df.head()

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,...,median,min,max,std,diff_mean,diff_median,position,weight,weighted_score,weighted_average
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.1,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,...,2.636969,2.240412,3.639261,0.720951,0.838881,0.636969,1,1.0,2.240412,2.838881
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.2,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,...,2.636969,2.240412,3.639261,0.720951,0.838881,0.636969,2,1.0,2.636969,2.838881
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.3,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,...,2.636969,2.240412,3.639261,0.720951,0.838881,0.636969,3,1.0,3.639261,2.838881
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg382.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,...,3.340636,3.050227,4.084590,0.533497,0.491818,0.340636,1,1.0,4.084590,3.491818
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg383.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",True,P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,...,3.340636,3.050227,4.084590,0.533497,0.491818,0.340636,2,1.0,3.340636,3.491818

In [15]:
df['diff_weight'] = abs(df['annotation_utt_score'] - df['weighted_average'])
df

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,...,min,max,std,diff_mean,diff_median,position,weight,weighted_score,weighted_average,diff_weight
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.1,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,...,2.240412,3.639261,0.720951,0.838881,0.636969,1,1.0,2.240412,2.838881,0.838881
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.2,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,...,2.240412,3.639261,0.720951,0.838881,0.636969,2,1.0,2.636969,2.838881,0.838881
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.3,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,...,2.240412,3.639261,0.720951,0.838881,0.636969,3,1.0,3.639261,2.838881,0.838881
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg382.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,...,3.050227,4.084590,0.533497,0.491818,0.340636,1,1.0,4.084590,3.491818,0.491818
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg383.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",True,P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,...,3.050227,4.084590,0.533497,0.491818,0.340636,2,1.0,3.340636,3.491818,0.491818
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9063,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.seg242.2,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...","Da se ne bi še kdo zmotil, obrazložitve glasu ...","Not to be mistaken, the explanation of the voi...",True,P_Neutral,3.0,1.817976,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,...,1.817976,4.017726,0.929625,0.084250,0.250649,2,1.0,1.817976,3.084250,0.084250
9064,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.seg242.3,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Svoje stališče oziroma obrazložitev glasu bo g...,"Mr Grimes, please, will explain his position o...",True,P_Neutral,3.0,3.074007,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,...,1.817976,4.017726,0.929625,0.084250,0.250649,3,1.0,3.074007,3.084250,0.084250
9065,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.seg242.4,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Izvolite.,Here you go.,True,P_Neutral,3.0,3.427290,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,...,1.817976,4.017726,0.929625,0.084250,0.250649,4,1.0,3.427290,3.084250,0.084250
9066,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.u17,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.seg63.1,Hvala lepa. Zadnji bo stališče Poslanske skupi...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2022-03-21-SDZ8-R...,...,2.962716,4.084590,0.793285,0.523653,0.523653,1,1.0,4.084590,3.523653,0.523653
9067,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.u17,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.seg64.1,Hvala lepa. Zadnji bo stališče Poslanske skupi...,Zadnji bo stališče Poslanske skupine SD predst...,The last position of the SD Group will be pres...,True,P_Neutral,3.0,2.962716,{'Text_ID': 'ParlaMint-SI-en_2022-03-21-SDZ8-R...,...,2.962716,4.084590,0.793285,0.523653,0.523653,2,1.0,2.962716,3.523653,0.523653

In [16]:
weight_diff = df['diff_weight'].mean()

print(f"Average difference with chair/position mean: {weight_diff}")
# Worse method so far

Average difference with mean: 1.441645085925033

## Length-based aggregation

In [17]:
df['length'] = df['text_sent'].apply(lambda x: len(x.split()))

In [18]:
aggregated_scores = (
    df.groupby("ID")
    .apply(lambda x: (x["annotation_sent"] * x["length"]).sum() / x["length"].sum())
    .reset_index(name="length_aggregated_score")
)

/var/folders/l_/t5l44v1s7d9168_x8bm5ly0h0000gn/T/ipykernel_3544/4206475692.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby("ID")

In [19]:
df = df.merge(
    aggregated_scores,
    on="ID"
)

df.head()

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,...,std,diff_mean,diff_median,position,weight,weighted_score,weighted_average,diff_weight,length,length_aggregated_score
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.1,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,...,0.720951,0.838881,0.636969,1,1.0,2.240412,2.838881,0.838881,4,2.808230
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.2,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,...,0.720951,0.838881,0.636969,2,1.0,2.636969,2.838881,0.838881,11,2.808230
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.3,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,...,0.720951,0.838881,0.636969,3,1.0,3.639261,2.838881,0.838881,5,2.808230
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg382.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,...,0.533497,0.491818,0.340636,1,1.0,4.084590,3.491818,0.491818,2,3.265585
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg383.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",True,P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,...,0.533497,0.491818,0.340636,2,1.0,3.340636,3.491818,0.491818,4,3.265585

In [20]:
df['diff_length'] = abs(df['annotation_utt_score'] - df['length_aggregated_score'])
length_avg = df['diff_length'].mean()
print("Average difference with length weights :", length_avg)

Average difference with mean : 1.2528991783037535

## Checking the methods

In [21]:
methods = ['ID', 'sent_id', 'annotation_utt_score', 'annotation_sent', 'diff_mean', 'diff_median', 'diff_weight', 'diff_length']
df_methods = df[methods]
df_methods

,ID,sent_id,annotation_utt_score,annotation_sent,diff_mean,diff_median,diff_weight,diff_length
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.1,2.0,2.240412,0.838881,0.636969,0.838881,0.808230
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.2,2.0,2.636969,0.838881,0.636969,0.838881,0.808230
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.3,2.0,3.639261,0.838881,0.636969,0.838881,0.808230
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg382.1,3.0,4.084590,0.491818,0.340636,0.491818,0.265585
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg383.1,3.0,3.340636,0.491818,0.340636,0.491818,0.265585
...,...,...,...,...,...,...,...,...
9063,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.seg242.2,3.0,1.817976,0.084250,0.250649,0.084250,0.509167
9064,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.seg242.3,3.0,3.074007,0.084250,0.250649,0.084250,0.509167
9065,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.seg242.4,3.0,3.427290,0.084250,0.250649,0.084250,0.509167
9066,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.u17,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.seg63.1,3.0,4.084590,0.523653,0.523653,0.523653,0.149695
9067,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.u17,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.seg64.1,3.0,2.962716,0.523653,0.523653,0.523653,0.149695

In [ ]:
print(f"Average difference with mean: {mean_diff}")
print(f"Average difference with median: {median_diff}")
print(f"Average difference with chair/position weights: {weight_diff}")
print("Average difference with length weights :", length_avg)

## Dataset

In [22]:
order = ['ID', 'sent_id', 'text_utt', 'text_sent', 'text_en', 'metadata', 'chair', 'annotation_utt', 'annotation_utt_score', 'annotation_sent', 'count', 'min', 'max', 'std', 'mean', 'median']
df = df[order]
df

,ID,sent_id,text_utt,text_sent,text_en,metadata,chair,annotation_utt,annotation_utt_score,annotation_sent,count,min,max,std,mean,median
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.1,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,True,N_Neutral,2.0,2.240412,3,2.240412,3.639261,0.720951,2.838881,2.636969
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.2,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,True,N_Neutral,2.0,2.636969,3,2.240412,3.639261,0.720951,2.838881,2.636969
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.3,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,True,N_Neutral,2.0,3.639261,3,2.240412,3.639261,0.720951,2.838881,2.636969
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg382.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,True,P_Neutral,3.0,4.084590,3,3.050227,4.084590,0.533497,3.491818,3.340636
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg383.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,True,P_Neutral,3.0,3.340636,3,3.050227,4.084590,0.533497,3.491818,3.340636
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9063,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.seg242.2,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...","Da se ne bi še kdo zmotil, obrazložitve glasu ...","Not to be mistaken, the explanation of the voi...",{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,True,P_Neutral,3.0,1.817976,4,1.817976,4.017726,0.929625,3.084250,3.250649
9064,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.seg242.3,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Svoje stališče oziroma obrazložitev glasu bo g...,"Mr Grimes, please, will explain his position o...",{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,True,P_Neutral,3.0,3.074007,4,1.817976,4.017726,0.929625,3.084250,3.250649
9065,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.seg242.4,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Izvolite.,Here you go.,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,True,P_Neutral,3.0,3.427290,4,1.817976,4.017726,0.929625,3.084250,3.250649
9066,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.u17,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.seg63.1,Hvala lepa. Zadnji bo stališče Poslanske skupi...,Hvala lepa.,Thank you very much.,{'Text_ID': 'ParlaMint-SI-en_2022-03-21-SDZ8-R...,True,P_Neutral,3.0,4.084590,2,2.962716,4.084590,0.793285,3.523653,3.523653
9067,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.u17,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.seg64.1,Hvala lepa. Zadnji bo stališče Poslanske skupi...,Zadnji bo stališče Poslanske skupine SD predst...,The last position of the SD Group will be pres...,{'Text_ID': 'ParlaMint-SI-en_2022-03-21-SDZ8-R...,True,P_Neutral,3.0,2.962716,2,2.962716,4.084590,0.793285,3.523653,3.523653