In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../Datasets/Development_data.csv', encoding='utf-8')
df

,ID,sent_id,text_utt,text_sent,text_en,annotation_utt,annotation_utt_score,annotation_sent,metadata
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.1,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.2,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.3,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg382.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg383.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...
...,...,...,...,...,...,...,...,...,...
9063,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.seg242.2,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...","Da se ne bi še kdo zmotil, obrazložitve glasu ...","Not to be mistaken, the explanation of the voi...",P_Neutral,3.0,1.817976,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...
9064,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.seg242.3,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Svoje stališče oziroma obrazložitev glasu bo g...,"Mr Grimes, please, will explain his position o...",P_Neutral,3.0,3.074007,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...
9065,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.seg242.4,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Izvolite.,Here you go.,P_Neutral,3.0,3.427290,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...
9066,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.u17,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.seg63.1,Hvala lepa. Zadnji bo stališče Poslanske skupi...,Hvala lepa.,Thank you very much.,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2022-03-21-SDZ8-R...
9067,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.u17,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.seg64.1,Hvala lepa. Zadnji bo stališče Poslanske skupi...,Zadnji bo stališče Poslanske skupine SD predst...,The last position of the SD Group will be pres...,P_Neutral,3.0,2.962716,{'Text_ID': 'ParlaMint-SI-en_2022-03-21-SDZ8-R...

In [3]:
sent_mean = df.groupby('ID')['annotation_sent'].mean().reset_index()

In [4]:
sent_avg = sent_mean.rename(columns={'annotation_sent':'avg_annotation'})

In [5]:
sent_avg.reset_index(drop=True, inplace=True)

In [6]:
df = pd.merge(df, sent_avg, on='ID', how='left')
df

,ID,sent_id,text_utt,text_sent,text_en,annotation_utt,annotation_utt_score,annotation_sent,metadata,avg_annotation
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.1,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,2.838881
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.2,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,2.838881
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.3,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,2.838881
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg382.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3.491818
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg383.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3.491818
...,...,...,...,...,...,...,...,...,...,...
9063,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.seg242.2,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...","Da se ne bi še kdo zmotil, obrazložitve glasu ...","Not to be mistaken, the explanation of the voi...",P_Neutral,3.0,1.817976,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,3.084250
9064,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.seg242.3,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Svoje stališče oziroma obrazložitev glasu bo g...,"Mr Grimes, please, will explain his position o...",P_Neutral,3.0,3.074007,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,3.084250
9065,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.seg242.4,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Izvolite.,Here you go.,P_Neutral,3.0,3.427290,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,3.084250
9066,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.u17,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.seg63.1,Hvala lepa. Zadnji bo stališče Poslanske skupi...,Hvala lepa.,Thank you very much.,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2022-03-21-SDZ8-R...,3.523653
9067,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.u17,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.seg64.1,Hvala lepa. Zadnji bo stališče Poslanske skupi...,Zadnji bo stališče Poslanske skupine SD predst...,The last position of the SD Group will be pres...,P_Neutral,3.0,2.962716,{'Text_ID': 'ParlaMint-SI-en_2022-03-21-SDZ8-R...,3.523653

In [9]:
df.to_csv('../Datasets/Aggregation_testing.csv', encoding='utf-8', index=False)