In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../Datasets/Development_data.csv', encoding='utf-8')
df.head()

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.1,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.2,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.3,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg382.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg383.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",True,P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...

# Sentence sentiment score aggregation

Testing different aggregation methods (average, mean, etc), as well as investigating some key characteristics of the dataset (e.g., dispersion of the sentence sentiment scores within the utterance). 

## Mean and median

In [3]:
aggregation = df.groupby('ID')['annotation_sent'].agg(
    count='count',
    mean ='mean', 
    median='median',
    min='min', 
    max='max', 
    std='std',
).reset_index()

In [4]:
df = pd.merge(df, aggregation, on='ID', how='left')
df.head()

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,count,mean,median,min,max,std
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.1,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881,2.636969,2.240412,3.639261,0.720951
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.2,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881,2.636969,2.240412,3.639261,0.720951
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.3,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881,2.636969,2.240412,3.639261,0.720951
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg382.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.491818,3.340636,3.050227,4.084590,0.533497
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg383.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",True,P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.491818,3.340636,3.050227,4.084590,0.533497

In [5]:
#Checking the highest data dispersion by sorting the values by standard deviation score 
# count = df.sort_values(by = 'std', ascending=False)
#count.head()

In [6]:
df['diff_mean'] = abs(df['annotation_utt_score'] - df['mean'])
df['diff_median'] = abs(df['annotation_utt_score'] - df['median'])

df.head()

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,count,mean,median,min,max,std,diff_mean,diff_median
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.1,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881,2.636969,2.240412,3.639261,0.720951,0.838881,0.636969
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.2,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881,2.636969,2.240412,3.639261,0.720951,0.838881,0.636969
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.3,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881,2.636969,2.240412,3.639261,0.720951,0.838881,0.636969
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg382.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.491818,3.340636,3.050227,4.084590,0.533497,0.491818,0.340636
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg383.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",True,P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.491818,3.340636,3.050227,4.084590,0.533497,0.491818,0.340636

In [7]:
average_max = df.sort_values(by = 'diff_mean', ascending=False)
average_max.head(5)

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,count,mean,median,min,max,std,diff_mean,diff_median
7964,ParlaMint-SI_2021-02-02-SDZ8-Izredna-57.u240,ParlaMint-SI_2021-02-02-SDZ8-Izredna-57.seg736.1,"Predlagam, da se držimo zakona, kolega Reberšek.","Predlagam, da se držimo zakona, kolega Reberšek.","I suggest we stick to the law, Comrade Reberšek.",True,Negative,0.0,3.812022,{'Text_ID': 'ParlaMint-SI-en_2021-02-02-SDZ8-I...,1,3.812022,3.812022,3.812022,3.812022,NaN,3.812022,3.812022
1972,ParlaMint-SI_2009-07-10-SDZ5-Redna-08.u230,ParlaMint-SI_2009-07-10-SDZ5-Redna-08.seg683.2,Hvala lepa za besedo. Poslanci DeSUS predlagan...,Poslanci DeSUS predlagani rešitvi načeloma ne ...,"Members of the DeSUS do not, in principle, obj...",False,Negative,0.0,4.212517,{'Text_ID': 'ParlaMint-SI-en_2009-07-10-SDZ5-R...,5,3.352120,3.914229,2.023306,4.479039,1.181295,3.352120,3.914229
1971,ParlaMint-SI_2009-07-10-SDZ5-Redna-08.u230,ParlaMint-SI_2009-07-10-SDZ5-Redna-08.seg683.1,Hvala lepa za besedo. Poslanci DeSUS predlagan...,Hvala lepa za besedo.,Thank you so much for saying that.,False,Negative,0.0,3.914229,{'Text_ID': 'ParlaMint-SI-en_2009-07-10-SDZ5-R...,5,3.352120,3.914229,2.023306,4.479039,1.181295,3.352120,3.914229
1973,ParlaMint-SI_2009-07-10-SDZ5-Redna-08.u230,ParlaMint-SI_2009-07-10-SDZ5-Redna-08.seg683.3,Hvala lepa za besedo. Poslanci DeSUS predlagan...,"Glede na to, da je k ureditvi tega vprašanja p...",In view of the fact that the Government has al...,False,Negative,0.0,2.131510,{'Text_ID': 'ParlaMint-SI-en_2009-07-10-SDZ5-R...,5,3.352120,3.914229,2.023306,4.479039,1.181295,3.352120,3.914229
1974,ParlaMint-SI_2009-07-10-SDZ5-Redna-08.u230,ParlaMint-SI_2009-07-10-SDZ5-Redna-08.seg683.4,Hvala lepa za besedo. Poslanci DeSUS predlagan...,"Prepričani smo, da bo vladni predlog celovitej...",We are confident that the government proposal ...,False,Negative,0.0,4.479039,{'Text_ID': 'ParlaMint-SI-en_2009-07-10-SDZ5-R...,5,3.352120,3.914229,2.023306,4.479039,1.181295,3.352120,3.914229

In [8]:
median_max = df.sort_values(by ='diff_median', ascending=False)
median_max.head(5)

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,count,mean,median,min,max,std,diff_mean,diff_median
2749,ParlaMint-SI_2008-04-24-SDZ4-Redna-38.u232,ParlaMint-SI_2008-04-24-SDZ4-Redna-38.seg710.3,"Hvala lepa. Če se ne motim, je amandma, ki ga ...",Hvala lepa.,Thank you very much.,False,Negative,0.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2008-04-24-SDZ4-R...,3,2.893164,4.084590,0.510310,4.084590,2.063612,2.893164,4.084590
2748,ParlaMint-SI_2008-04-24-SDZ4-Redna-38.u232,ParlaMint-SI_2008-04-24-SDZ4-Redna-38.seg710.2,"Hvala lepa. Če se ne motim, je amandma, ki ga ...","Če se ne motim, je amandma, ki ga je Poslanska...","If I am not mistaken, the amendment tabled by ...",False,Negative,0.0,0.510310,{'Text_ID': 'ParlaMint-SI-en_2008-04-24-SDZ4-R...,3,2.893164,4.084590,0.510310,4.084590,2.063612,2.893164,4.084590
2747,ParlaMint-SI_2008-04-24-SDZ4-Redna-38.u232,ParlaMint-SI_2008-04-24-SDZ4-Redna-38.seg710.1,"Hvala lepa. Če se ne motim, je amandma, ki ga ...",Hvala lepa.,Thank you very much.,False,Negative,0.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2008-04-24-SDZ4-R...,3,2.893164,4.084590,0.510310,4.084590,2.063612,2.893164,4.084590
1975,ParlaMint-SI_2009-07-10-SDZ5-Redna-08.u230,ParlaMint-SI_2009-07-10-SDZ5-Redna-08.seg684.1,Hvala lepa za besedo. Poslanci DeSUS predlagan...,Zaradi navedenega bomo poslanci DeSUS podprli ...,"For this reason, Members of the DeSUS will sup...",False,Negative,0.0,2.023306,{'Text_ID': 'ParlaMint-SI-en_2009-07-10-SDZ5-R...,5,3.352120,3.914229,2.023306,4.479039,1.181295,3.352120,3.914229
1973,ParlaMint-SI_2009-07-10-SDZ5-Redna-08.u230,ParlaMint-SI_2009-07-10-SDZ5-Redna-08.seg683.3,Hvala lepa za besedo. Poslanci DeSUS predlagan...,"Glede na to, da je k ureditvi tega vprašanja p...",In view of the fact that the Government has al...,False,Negative,0.0,2.131510,{'Text_ID': 'ParlaMint-SI-en_2009-07-10-SDZ5-R...,5,3.352120,3.914229,2.023306,4.479039,1.181295,3.352120,3.914229

In [9]:
mean_diff = df['diff_mean'].mean()
median_diff = df['diff_median'].mean()

print(f"Average difference with mean: {mean_diff}")
print(f"Average difference with median: {median_diff}")

Average difference with mean: 1.4313146918812052
Average difference with median: 1.3735544539784275

# Calculating differents weights and weighted average

The weights assigned determined by the following indicators:
<!-- This is currently just a test with contexts that could be important when considering sentiment in whole utterances -->
- the *position* of the sentence (e.g., if the sentence appears at the end of the utterance)
- the *length* of the sentences (the longer the sentence, the higher the weight?)
- the *intensity of the sentiment* - utilising the sentence sentiment scores to produce weighted sentiment score (using absolute values), to boost the extremities in the speeches. 

## Position

In [10]:
df['position'] = df.groupby('ID').cumcount() + 1
df['position_max'] = df.groupby('ID')['position'].transform('max')
df.head()

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,count,mean,median,min,max,std,diff_mean,diff_median,position,position_max
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.1,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881,2.636969,2.240412,3.639261,0.720951,0.838881,0.636969,1,3
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.2,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881,2.636969,2.240412,3.639261,0.720951,0.838881,0.636969,2,3
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.3,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881,2.636969,2.240412,3.639261,0.720951,0.838881,0.636969,3,3
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg382.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.491818,3.340636,3.050227,4.084590,0.533497,0.491818,0.340636,1,3
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg383.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",True,P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.491818,3.340636,3.050227,4.084590,0.533497,0.491818,0.340636,2,3

In [11]:
df['position_score'] = df['annotation_sent'] * df['position']
position_avg = df.groupby('ID').apply(lambda x: x['position_score'].sum() / x['position'].sum()).reset_index(name='position_avg')
position_avg

/var/folders/l_/t5l44v1s7d9168_x8bm5ly0h0000gn/T/ipykernel_2507/1953713876.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  position_avg = df.groupby('ID').apply(lambda x: x['position_score'].sum() / x['position'].sum()).reset_index(name='position_avg')

                                               ID  position_avg
0      ParlaMint-SI_2000-12-20-SDZ3-Izredna-03.u9      2.878105
1    ParlaMint-SI_2000-12-21-SDZ3-Izredna-03.u120      3.267794
2       ParlaMint-SI_2001-01-30-SDZ3-Redna-02.u20      3.100404
3       ParlaMint-SI_2001-01-31-SDZ3-Redna-02.u12      2.438669
4      ParlaMint-SI_2001-02-01-SDZ3-Redna-02.u131      3.149381
..                                            ...           ...
795   ParlaMint-SI_2022-03-09-SDZ8-Izredna-97.u53      2.755340
796  ParlaMint-SI_2022-03-11-SDZ8-Izredna-98.u104      4.235925
797    ParlaMint-SI_2022-03-18-SDZ8-Redna-30.u164      1.456928
798     ParlaMint-SI_2022-03-21-SDZ8-Redna-30.u17      3.336674
799  ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.u230      3.483756

[800 rows x 2 columns]

In [12]:
df = df.merge(position_avg, on='ID')
df.head()

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,...,median,min,max,std,diff_mean,diff_median,position,position_max,position_score,position_avg
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.1,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,...,2.636969,2.240412,3.639261,0.720951,0.838881,0.636969,1,3,2.240412,3.072022
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.2,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,...,2.636969,2.240412,3.639261,0.720951,0.838881,0.636969,2,3,5.273937,3.072022
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.3,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,...,2.636969,2.240412,3.639261,0.720951,0.838881,0.636969,3,3,10.917783,3.072022
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg382.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,...,3.340636,3.050227,4.084590,0.533497,0.491818,0.340636,1,3,4.084590,3.319424
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg383.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",True,P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,...,3.340636,3.050227,4.084590,0.533497,0.491818,0.340636,2,3,6.681272,3.319424

In [13]:
df['diff_position'] = abs(df['annotation_utt_score'] - df['position_avg'])
position_avg = df['diff_position'].mean()
print("Average difference with intensity weights:", position_avg)

Average difference with intensity weights: 1.396118850558041

## Sentence length

In [14]:
df['length'] = df['text_sent'].apply(lambda x: len(x.split()))

In [15]:
aggregated_scores = (
    df.groupby("ID")
    .apply(lambda x: (x["annotation_sent"] * x["length"]).sum() / x["length"].sum())
    .reset_index(name="length_avg")
)

/var/folders/l_/t5l44v1s7d9168_x8bm5ly0h0000gn/T/ipykernel_2507/336945171.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby("ID")

In [16]:
df = df.merge(
    aggregated_scores,
    on="ID"
)

df.head()

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,...,std,diff_mean,diff_median,position,position_max,position_score,position_avg,diff_position,length,length_avg
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.1,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,...,0.720951,0.838881,0.636969,1,3,2.240412,3.072022,1.072022,4,2.808230
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.2,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,...,0.720951,0.838881,0.636969,2,3,5.273937,3.072022,1.072022,11,2.808230
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.3,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,...,0.720951,0.838881,0.636969,3,3,10.917783,3.072022,1.072022,5,2.808230
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg382.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,...,0.533497,0.491818,0.340636,1,3,4.084590,3.319424,0.319424,2,3.265585
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg383.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",True,P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,...,0.533497,0.491818,0.340636,2,3,6.681272,3.319424,0.319424,4,3.265585

In [17]:
df['diff_length'] = abs(df['annotation_utt_score'] - df['length_avg'])
length_avg = df['diff_length'].mean()
print("Average difference with length weights:", length_avg)

Average difference with length weights: 1.2528991783037535

## Sentiment intensity weighted average

In [18]:
count_df = df.sort_values(by = 'annotation_sent', ascending=True)
count_df.head()

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,...,diff_mean,diff_median,position,position_max,position_score,position_avg,diff_position,length,length_avg,diff_length
4696,ParlaMint-SI_2021-05-26-SDZ8-Izredna-75.u43,ParlaMint-SI_2021-05-26-SDZ8-Izredna-75.seg160.1,Hvala lepa in lep pozdrav! V nedeljo je bila o...,", začneš naprtovat opozicijskim strankam, da d...",You start pushing opposition parties to act un...,False,Negative,0.0,-0.125449,{'Text_ID': 'ParlaMint-SI-en_2021-05-26-SDZ8-I...,...,1.157187,0.611312,76,87,-9.534138,1.014366,1.014366,14,0.720837,0.720837
6444,ParlaMint-SI_2011-01-11-SDZ5-Izredna-38.u24,ParlaMint-SI_2011-01-11-SDZ5-Izredna-38.seg89.18,"Hvala lepa. Mislim, da se sedaj že tretje leto...","Iz te spirale ni mogoče uiti, treba se bo posl...","This spiral cannot be escaped, the Greek scrip...",False,Negative,0.0,-0.071610,{'Text_ID': 'ParlaMint-SI-en_2011-01-11-SDZ5-I...,...,1.213037,0.666621,19,20,-1.360582,1.065833,1.065833,56,0.953998,0.953998
4546,ParlaMint-SI_2009-12-18-SDZ5-Redna-12.u302,ParlaMint-SI_2009-12-18-SDZ5-Redna-12.seg765.17,"Hvala lepa, gospod predsednik. Zavedati se je ...","Treba je pač ""nafutrati"" lačno, požrešno vladn...","It's just that it's supposed to be a hungry, g...",False,Negative,0.0,-0.066441,{'Text_ID': 'ParlaMint-SI-en_2009-12-18-SDZ5-R...,...,1.019391,0.303641,17,17,-1.129503,0.762097,0.762097,8,1.006667,1.006667
9025,ParlaMint-SI_2021-03-04-SDZ8-Izredna-64.u150,ParlaMint-SI_2021-03-04-SDZ8-Izredna-64.seg566.1,Najlepša hvala. Da zaključim na hitro. Oznaka ...,"Pričakujem dopolnjen načrt, ampak glede na ign...","I expect a complementary plan, but given the i...",False,Negative,0.0,-0.059675,{'Text_ID': 'ParlaMint-SI-en_2021-03-04-SDZ8-I...,...,2.222924,2.064153,21,23,-1.253170,2.355704,2.355704,22,1.904730,1.904730
6781,ParlaMint-SI_2011-09-19-SDZ5-Redna-31.u115,ParlaMint-SI_2011-09-19-SDZ5-Redna-31.seg347.2,"Hvala lepa, gospod podpredsednik. Ministra za ...","Žal moram reči, da je tudi ta civilna iniciati...","Unfortunately, I must say that this civil init...",False,Negative,0.0,-0.054815,{'Text_ID': 'ParlaMint-SI-en_2011-09-19-SDZ5-R...,...,2.059891,2.222700,13,13,-0.712595,1.688602,1.688602,22,1.786034,1.786034

In [19]:
df['intensity'] = df['annotation_sent'].abs()
df['intensity_score'] = df['annotation_sent'] * df['intensity']
df.head()

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,...,position,position_max,position_score,position_avg,diff_position,length,length_avg,diff_length,intensity,intensity_score
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.1,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,...,1,3,2.240412,3.072022,1.072022,4,2.808230,0.808230,2.240412,5.019447
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.2,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,...,2,3,5.273937,3.072022,1.072022,11,2.808230,0.808230,2.636969,6.953603
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.3,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,...,3,3,10.917783,3.072022,1.072022,5,2.808230,0.808230,3.639261,13.244221
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg382.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,...,1,3,4.084590,3.319424,0.319424,2,3.265585,0.265585,4.084590,16.683879
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg383.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",True,P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,...,2,3,6.681272,3.319424,0.319424,4,3.265585,0.265585,3.340636,11.159847

In [20]:
intensity_avg = df.groupby('ID').apply(lambda x: x['intensity_score'].sum() / x['intensity'].sum()).reset_index(name='intensity_avg')
intensity_avg

/var/folders/l_/t5l44v1s7d9168_x8bm5ly0h0000gn/T/ipykernel_2507/757930734.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  intensity_avg = df.groupby('ID').apply(lambda x: x['intensity_score'].sum() / x['intensity'].sum()).reset_index(name='intensity_avg')

                                               ID  intensity_avg
0      ParlaMint-SI_2000-12-20-SDZ3-Izredna-03.u9       3.210041
1    ParlaMint-SI_2000-12-21-SDZ3-Izredna-03.u120       3.557580
2       ParlaMint-SI_2001-01-30-SDZ3-Redna-02.u20       3.228269
3       ParlaMint-SI_2001-01-31-SDZ3-Redna-02.u12       3.018776
4      ParlaMint-SI_2001-02-01-SDZ3-Redna-02.u131       3.244134
..                                            ...            ...
795   ParlaMint-SI_2022-03-09-SDZ8-Izredna-97.u53       3.007187
796  ParlaMint-SI_2022-03-11-SDZ8-Izredna-98.u104       4.235925
797    ParlaMint-SI_2022-03-18-SDZ8-Redna-30.u164       2.424919
798     ParlaMint-SI_2022-03-21-SDZ8-Redna-30.u17       3.612950
799  ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.u230       3.619523

[800 rows x 2 columns]

In [21]:
df = df.merge(intensity_avg, on='ID')
df.head()

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,...,position_max,position_score,position_avg,diff_position,length,length_avg,diff_length,intensity,intensity_score,intensity_avg
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.1,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,...,3,2.240412,3.072022,1.072022,4,2.808230,0.808230,2.240412,5.019447,2.960941
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.2,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,...,3,5.273937,3.072022,1.072022,11,2.808230,0.808230,2.636969,6.953603,2.960941
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.3,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,...,3,10.917783,3.072022,1.072022,5,2.808230,0.808230,3.639261,13.244221,2.960941
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg382.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,...,3,4.084590,3.319424,0.319424,2,3.265585,0.265585,4.084590,16.683879,3.546158
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg383.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",True,P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,...,3,6.681272,3.319424,0.319424,4,3.265585,0.265585,3.340636,11.159847,3.546158

In [22]:
df['diff_intensity'] = abs(df['annotation_utt_score'] - df['intensity_avg'])
intensity_avg = df['diff_intensity'].mean()
print("Average difference with intensity weights:", intensity_avg)

Average difference with intensity weights: 1.928731267604106

## Checking the methods

In [23]:
methods = ['ID', 'sent_id', 'annotation_utt_score', 'annotation_sent', 'mean', 'median', 'position_avg', 'length_avg', 'intensity_avg', 'diff_mean', 'diff_median', 'diff_position', 'diff_length', 'diff_intensity']
df_methods = df[methods]
df_methods

,ID,sent_id,annotation_utt_score,annotation_sent,mean,median,position_avg,length_avg,intensity_avg,diff_mean,diff_median,diff_position,diff_length,diff_intensity
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.1,2.0,2.240412,2.838881,2.636969,3.072022,2.808230,2.960941,0.838881,0.636969,1.072022,0.808230,0.960941
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.2,2.0,2.636969,2.838881,2.636969,3.072022,2.808230,2.960941,0.838881,0.636969,1.072022,0.808230,0.960941
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.3,2.0,3.639261,2.838881,2.636969,3.072022,2.808230,2.960941,0.838881,0.636969,1.072022,0.808230,0.960941
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg382.1,3.0,4.084590,3.491818,3.340636,3.319424,3.265585,3.546158,0.491818,0.340636,0.319424,0.265585,0.546158
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg383.1,3.0,3.340636,3.491818,3.340636,3.319424,3.265585,3.546158,0.491818,0.340636,0.319424,0.265585,0.546158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9063,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.seg242.2,3.0,1.817976,3.084250,3.250649,3.058486,2.490833,3.294399,0.084250,0.250649,0.058486,0.509167,0.294399
9064,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.seg242.3,3.0,3.074007,3.084250,3.250649,3.058486,2.490833,3.294399,0.084250,0.250649,0.058486,0.509167,0.294399
9065,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.seg242.4,3.0,3.427290,3.084250,3.250649,3.058486,2.490833,3.294399,0.084250,0.250649,0.058486,0.509167,0.294399
9066,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.u17,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.seg63.1,3.0,4.084590,3.523653,3.523653,3.336674,3.149695,3.612950,0.523653,0.523653,0.336674,0.149695,0.612950
9067,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.u17,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.seg64.1,3.0,2.962716,3.523653,3.523653,3.336674,3.149695,3.612950,0.523653,0.523653,0.336674,0.149695,0.612950

In [24]:
#Length weights seem to be the best method to aggregate the scores

print(f"Average difference with mean: {mean_diff}")
print(f"Average difference with median: {median_diff}")
print("Average difference with position weights:", position_avg)
print("Average difference with length weights :", length_avg)
print("Average difference with intensity weights:", intensity_avg)

Average difference with mean: 1.4313146918812052
Average difference with median: 1.3735544539784275
Average difference with position weights: 1.396118850558041
Average difference with length weights : 1.2528991783037535
Average difference with intensity weights: 1.928731267604106

In [25]:
df_methods.to_csv('../Datasets/Aggregation_methods.csv', encoding='utf-8', index=False)

## Dataset

In [26]:
order = ['ID', 'sent_id', 'text_utt', 'text_sent', 'text_en', 'metadata', 'chair', 'annotation_utt', 'annotation_utt_score', 'annotation_sent', 
         'min', 'max', 'std', 'position', 'length', 'count', 
         'mean', 'median', 'position_avg', 'length_avg', 'intensity_avg', 
         'diff_mean', 'diff_median', 'diff_position', 'diff_length', 'diff_intensity']
df_data = df[order]
df_data

,ID,sent_id,text_utt,text_sent,text_en,metadata,chair,annotation_utt,annotation_utt_score,annotation_sent,...,mean,median,position_avg,length_avg,intensity_avg,diff_mean,diff_median,diff_position,diff_length,diff_intensity
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.1,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,True,N_Neutral,2.0,2.240412,...,2.838881,2.636969,3.072022,2.808230,2.960941,0.838881,0.636969,1.072022,0.808230,0.960941
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.2,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,True,N_Neutral,2.0,2.636969,...,2.838881,2.636969,3.072022,2.808230,2.960941,0.838881,0.636969,1.072022,0.808230,0.960941
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.seg398.3,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,True,N_Neutral,2.0,3.639261,...,2.838881,2.636969,3.072022,2.808230,2.960941,0.838881,0.636969,1.072022,0.808230,0.960941
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg382.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,True,P_Neutral,3.0,4.084590,...,3.491818,3.340636,3.319424,3.265585,3.546158,0.491818,0.340636,0.319424,0.265585,0.546158
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.seg383.1,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,True,P_Neutral,3.0,3.340636,...,3.491818,3.340636,3.319424,3.265585,3.546158,0.491818,0.340636,0.319424,0.265585,0.546158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9063,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.seg242.2,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...","Da se ne bi še kdo zmotil, obrazložitve glasu ...","Not to be mistaken, the explanation of the voi...",{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,True,P_Neutral,3.0,1.817976,...,3.084250,3.250649,3.058486,2.490833,3.294399,0.084250,0.250649,0.058486,0.509167,0.294399
9064,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.seg242.3,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Svoje stališče oziroma obrazložitev glasu bo g...,"Mr Grimes, please, will explain his position o...",{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,True,P_Neutral,3.0,3.074007,...,3.084250,3.250649,3.058486,2.490833,3.294399,0.084250,0.250649,0.058486,0.509167,0.294399
9065,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.seg242.4,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Izvolite.,Here you go.,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,True,P_Neutral,3.0,3.427290,...,3.084250,3.250649,3.058486,2.490833,3.294399,0.084250,0.250649,0.058486,0.509167,0.294399
9066,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.u17,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.seg63.1,Hvala lepa. Zadnji bo stališče Poslanske skupi...,Hvala lepa.,Thank you very much.,{'Text_ID': 'ParlaMint-SI-en_2022-03-21-SDZ8-R...,True,P_Neutral,3.0,4.084590,...,3.523653,3.523653,3.336674,3.149695,3.612950,0.523653,0.523653,0.336674,0.149695,0.612950
9067,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.u17,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.seg64.1,Hvala lepa. Zadnji bo stališče Poslanske skupi...,Zadnji bo stališče Poslanske skupine SD predst...,The last position of the SD Group will be pres...,{'Text_ID': 'ParlaMint-SI-en_2022-03-21-SDZ8-R...,True,P_Neutral,3.0,2.962716,...,3.523653,3.523653,3.336674,3.149695,3.612950,0.523653,0.523653,0.336674,0.149695,0.612950

In [27]:
df_data.to_csv('../Datasets/Aggregation_testing.csv', encoding='utf-8', index=False)

In [28]:
with open('../Datasets/Aggregation_testing.jsonl', 'w', encoding='utf-8') as f:
    df_data.to_json(f, orient='records', lines=True, force_ascii=False)