## Testing additional length-based metrics

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../Datasets/Development_data.csv', encoding='utf-8')
df

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.seg3...,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.seg3...,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",True,P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...
...,...,...,...,...,...,...,...,...,...,...
9063,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...","Da se ne bi še kdo zmotil, obrazložitve glasu ...","Not to be mistaken, the explanation of the voi...",True,P_Neutral,3.0,1.817976,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...
9064,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Svoje stališče oziroma obrazložitev glasu bo g...,"Mr Grimes, please, will explain his position o...",True,P_Neutral,3.0,3.074007,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...
9065,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Izvolite.,Here you go.,True,P_Neutral,3.0,3.427290,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...
9066,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.ana.u17,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.ana.seg63.1,Hvala lepa. Zadnji bo stališče Poslanske skupi...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2022-03-21-SDZ8-R...
9067,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.ana.u17,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.ana.seg64.1,Hvala lepa. Zadnji bo stališče Poslanske skupi...,Zadnji bo stališče Poslanske skupine SD predst...,The last position of the SD Group will be pres...,True,P_Neutral,3.0,2.962716,{'Text_ID': 'ParlaMint-SI-en_2022-03-21-SDZ8-R...

Removing one- and two-sentence utterances to not influence the aggregation calculations

In [3]:
sentence_count = df.groupby('ID').size()

one_sentence = (sentence_count == 1).sum()
two_sentence = (sentence_count == 2).sum()

print('No. of one-sentence utterances: ', one_sentence)
print('No. of one-sentence utterances: ', two_sentence)

No. of one-sentence utterances:  107
No. of one-sentence utterances:  145

In [4]:
filtered_df = df[df["ID"].isin(sentence_count[sentence_count >= 3].index)]
filtered_df

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.seg3...,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.seg3...,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",True,P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...
...,...,...,...,...,...,...,...,...,...,...
9060,ParlaMint-SI_2014-03-03-SDZ6-Redna-22.ana.u242,ParlaMint-SI_2014-03-03-SDZ6-Redna-22.ana.seg8...,"Hvala za besedo, predsedujoča. Pozdrav vsem pr...",Hvala.,Thank you.,False,M_Negative,1.0,4.510695,{'Text_ID': 'ParlaMint-SI-en_2014-03-03-SDZ6-R...
9062,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...","Hvala, gospodu Kovačiču.","Thank you, Mr. Kovacich.",True,P_Neutral,3.0,4.017726,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...
9063,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...","Da se ne bi še kdo zmotil, obrazložitve glasu ...","Not to be mistaken, the explanation of the voi...",True,P_Neutral,3.0,1.817976,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...
9064,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Svoje stališče oziroma obrazložitev glasu bo g...,"Mr Grimes, please, will explain his position o...",True,P_Neutral,3.0,3.074007,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...
9065,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Izvolite.,Here you go.,True,P_Neutral,3.0,3.427290,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...

In [5]:
check = filtered_df['ID'].unique()
len(check)

548

### Sentence-count based avg

In [6]:
filtered_df['count'] = filtered_df.groupby('ID')['sent_id'].transform('count')
filtered_df

/var/folders/l_/t5l44v1s7d9168_x8bm5ly0h0000gn/T/ipykernel_2338/796650816.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['count'] = filtered_df.groupby('ID')['sent_id'].transform('count')

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,count
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.seg3...,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.seg3...,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",True,P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3
...,...,...,...,...,...,...,...,...,...,...,...
9060,ParlaMint-SI_2014-03-03-SDZ6-Redna-22.ana.u242,ParlaMint-SI_2014-03-03-SDZ6-Redna-22.ana.seg8...,"Hvala za besedo, predsedujoča. Pozdrav vsem pr...",Hvala.,Thank you.,False,M_Negative,1.0,4.510695,{'Text_ID': 'ParlaMint-SI-en_2014-03-03-SDZ6-R...,15
9062,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...","Hvala, gospodu Kovačiču.","Thank you, Mr. Kovacich.",True,P_Neutral,3.0,4.017726,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4
9063,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...","Da se ne bi še kdo zmotil, obrazložitve glasu ...","Not to be mistaken, the explanation of the voi...",True,P_Neutral,3.0,1.817976,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4
9064,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Svoje stališče oziroma obrazložitev glasu bo g...,"Mr Grimes, please, will explain his position o...",True,P_Neutral,3.0,3.074007,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4
9065,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Izvolite.,Here you go.,True,P_Neutral,3.0,3.427290,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4

In [7]:
filtered_df["annotation_sent"] = filtered_df["annotation_sent"].clip(0, 5)
filtered_df.sort_values(by="annotation_sent")

/var/folders/l_/t5l44v1s7d9168_x8bm5ly0h0000gn/T/ipykernel_2338/2834037207.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df["annotation_sent"] = filtered_df["annotation_sent"].clip(0, 5)

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,count
7815,ParlaMint-SI_2013-11-13-SDZ6-Izredna-47.ana.u207,ParlaMint-SI_2013-11-13-SDZ6-Izredna-47.ana.se...,"Pa naj razume, kdor lahko. 30 evrov, zdaj bo s...","Za ta zakon je značilno, da ima vsa stroka, ki...",This law is characterized by the argument that...,False,Negative,0.0,0.0,{'Text_ID': 'ParlaMint-SI-en_2013-11-13-SDZ6-I...,15
2856,ParlaMint-SI_2016-02-22-SDZ7-Izredna-28.ana.u60,ParlaMint-SI_2016-02-22-SDZ7-Izredna-28.ana.se...,"Hvala. Moram reči, da je bilo tole prav zanimi...","In podobno se dogaja tudi v Grčiji, kjer imamo...","And the same is true in Greece, where we have ...",False,Negative,0.0,0.0,{'Text_ID': 'ParlaMint-SI-en_2016-02-22-SDZ7-I...,260
398,ParlaMint-SI_2009-09-24-SDZ5-Redna-09.ana.u173,ParlaMint-SI_2009-09-24-SDZ5-Redna-09.ana.seg6...,"Hvala za besedo, gospod predsedujoči. Očitno s...","Glavni poveljnik pa kriminalizira sindikate, k...","However, the Chief Commander criminalises unio...",False,Negative,0.0,0.0,{'Text_ID': 'ParlaMint-SI-en_2009-09-24-SDZ5-R...,53
5869,ParlaMint-SI_2020-04-28-SDZ8-Izredna-35.ana.u58,ParlaMint-SI_2020-04-28-SDZ8-Izredna-35.ana.se...,"Hvala še enkrat. Kot sem prej povedal, mi name...",Joc Pečečnik je stopil pred slovenske novinarj...,Joc Pečečnik stood in front of Slovenian journ...,False,Negative,0.0,0.0,{'Text_ID': 'ParlaMint-SI-en_2020-04-28-SDZ8-I...,46
2016,ParlaMint-SI_2019-03-25-SDZ8-Redna-06.ana.u38,ParlaMint-SI_2019-03-25-SDZ8-Redna-06.ana.seg1...,"Dajem postopkovni predlog, da Državni zbor opr...","In ko pravim, da je revščina sramota, to ni sr...","And when I say that poverty is a disgrace, it ...",False,Negative,0.0,0.0,{'Text_ID': 'ParlaMint-SI-en_2019-03-25-SDZ8-R...,9
...,...,...,...,...,...,...,...,...,...,...,...
7432,ParlaMint-SI_2001-05-03-SDZ3-Izredna-07.ana.u16,ParlaMint-SI_2001-05-03-SDZ3-Izredna-07.ana.se...,Hvala za besedo gospod predsednik. Spoštovane ...,To je dodatni argument za umerjeno in strokovn...,This is an additional argument for a moderate ...,False,M_Negative,1.0,5.0,{'Text_ID': 'ParlaMint-SI-en_2001-05-03-SDZ3-I...,44
382,ParlaMint-SI_2009-09-24-SDZ5-Redna-09.ana.u173,ParlaMint-SI_2009-09-24-SDZ5-Redna-09.ana.seg6...,"Hvala za besedo, gospod predsedujoči. Očitno s...",Smo za to!,We're up for it!,False,Negative,0.0,5.0,{'Text_ID': 'ParlaMint-SI-en_2009-09-24-SDZ5-R...,53
384,ParlaMint-SI_2009-09-24-SDZ5-Redna-09.ana.u173,ParlaMint-SI_2009-09-24-SDZ5-Redna-09.ana.seg6...,"Hvala za besedo, gospod predsedujoči. Očitno s...",Smo za to!,We're up for it!,False,Negative,0.0,5.0,{'Text_ID': 'ParlaMint-SI-en_2009-09-24-SDZ5-R...,53
1746,ParlaMint-SI_2001-06-29-SDZ3-Redna-07.ana.u120,ParlaMint-SI_2001-06-29-SDZ3-Redna-07.ana.seg2...,"Predsedujoči, hvala lepa za besedo. Brez dvoma...",In jaz bi tudi tak zakon podprl.,And I would support such a marriage.,False,Negative,0.0,5.0,{'Text_ID': 'ParlaMint-SI-en_2001-06-29-SDZ3-R...,29
1333,ParlaMint-SI_2016-01-20-SDZ7-Izredna-27.ana.u126,ParlaMint-SI_2016-01-20-SDZ7-Izredna-27.ana.se...,"Hvala, gospod predsednik. Čestitam ministrici ...",Ponavljam dobronamerni predlog.,I repeat my well-intentioned proposal.,False,M_Negative,1.0,5.0,{'Text_ID': 'ParlaMint-SI-en_2016-01-20-SDZ7-I...,37

In [8]:
count_avg = (
    filtered_df.groupby('ID')
    .apply(lambda x: (x['annotation_sent'] * x['count']).sum() / x['count'].sum())
    .reset_index(name='count_avg')
)

filtered_df = filtered_df.merge(count_avg, on='ID')

/var/folders/l_/t5l44v1s7d9168_x8bm5ly0h0000gn/T/ipykernel_2338/1514152142.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  filtered_df.groupby('ID')

In [9]:
filtered_df

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,count,count_avg
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.838881
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.seg3...,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.491818
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.seg3...,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",True,P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.491818
...,...,...,...,...,...,...,...,...,...,...,...,...
8666,ParlaMint-SI_2014-03-03-SDZ6-Redna-22.ana.u242,ParlaMint-SI_2014-03-03-SDZ6-Redna-22.ana.seg8...,"Hvala za besedo, predsedujoča. Pozdrav vsem pr...",Hvala.,Thank you.,False,M_Negative,1.0,4.510695,{'Text_ID': 'ParlaMint-SI-en_2014-03-03-SDZ6-R...,15,3.167355
8667,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...","Hvala, gospodu Kovačiču.","Thank you, Mr. Kovacich.",True,P_Neutral,3.0,4.017726,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4,3.084250
8668,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...","Da se ne bi še kdo zmotil, obrazložitve glasu ...","Not to be mistaken, the explanation of the voi...",True,P_Neutral,3.0,1.817976,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4,3.084250
8669,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Svoje stališče oziroma obrazložitev glasu bo g...,"Mr Grimes, please, will explain his position o...",True,P_Neutral,3.0,3.074007,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4,3.084250
8670,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Izvolite.,Here you go.,True,P_Neutral,3.0,3.427290,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4,3.084250

In [10]:
filtered_df["count_avg"] = filtered_df["count_avg"].round(2)
filtered_df

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,count,count_avg
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.84
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.84
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.84
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.seg3...,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.49
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.seg3...,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",True,P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.49
...,...,...,...,...,...,...,...,...,...,...,...,...
8666,ParlaMint-SI_2014-03-03-SDZ6-Redna-22.ana.u242,ParlaMint-SI_2014-03-03-SDZ6-Redna-22.ana.seg8...,"Hvala za besedo, predsedujoča. Pozdrav vsem pr...",Hvala.,Thank you.,False,M_Negative,1.0,4.510695,{'Text_ID': 'ParlaMint-SI-en_2014-03-03-SDZ6-R...,15,3.17
8667,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...","Hvala, gospodu Kovačiču.","Thank you, Mr. Kovacich.",True,P_Neutral,3.0,4.017726,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4,3.08
8668,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...","Da se ne bi še kdo zmotil, obrazložitve glasu ...","Not to be mistaken, the explanation of the voi...",True,P_Neutral,3.0,1.817976,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4,3.08
8669,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Svoje stališče oziroma obrazložitev glasu bo g...,"Mr Grimes, please, will explain his position o...",True,P_Neutral,3.0,3.074007,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4,3.08
8670,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Izvolite.,Here you go.,True,P_Neutral,3.0,3.427290,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4,3.08

In [11]:
count_avg_mae = (filtered_df["annotation_utt_score"] - filtered_df["count_avg"]).abs().mean()
print(f"MAE: {count_avg_mae}")

MAE: 1.464150616999193

### Word-based length avg

In [12]:
filtered_df["length"] = filtered_df["text_sent"].apply(lambda x: len(x.split()))

# Compute the sentence-length-weighted average for each utterance
length_weighted_avg = (
    filtered_df.groupby("ID")
    .apply(lambda group: (group["annotation_sent"] * group["length"]).sum() / group["length"].sum())
    .reset_index(name="length_avg")
)

# Add the length_avg back to the filtered DataFrame
filtered_df = filtered_df.merge(length_weighted_avg, on="ID")
filtered_df

/var/folders/l_/t5l44v1s7d9168_x8bm5ly0h0000gn/T/ipykernel_2338/350406913.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  filtered_df.groupby("ID")

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,count,count_avg,length,length_avg
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.84,4,2.808230
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.84,11,2.808230
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.84,5,2.808230
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.seg3...,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.49,2,3.265585
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.seg3...,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",True,P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.49,4,3.265585
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8666,ParlaMint-SI_2014-03-03-SDZ6-Redna-22.ana.u242,ParlaMint-SI_2014-03-03-SDZ6-Redna-22.ana.seg8...,"Hvala za besedo, predsedujoča. Pozdrav vsem pr...",Hvala.,Thank you.,False,M_Negative,1.0,4.510695,{'Text_ID': 'ParlaMint-SI-en_2014-03-03-SDZ6-R...,15,3.17,1,3.024682
8667,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...","Hvala, gospodu Kovačiču.","Thank you, Mr. Kovacich.",True,P_Neutral,3.0,4.017726,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4,3.08,3,2.490833
8668,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...","Da se ne bi še kdo zmotil, obrazložitve glasu ...","Not to be mistaken, the explanation of the voi...",True,P_Neutral,3.0,1.817976,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4,3.08,16,2.490833
8669,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Svoje stališče oziroma obrazložitev glasu bo g...,"Mr Grimes, please, will explain his position o...",True,P_Neutral,3.0,3.074007,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4,3.08,9,2.490833
8670,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Izvolite.,Here you go.,True,P_Neutral,3.0,3.427290,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4,3.08,1,2.490833

In [13]:
filtered_df["length_avg"] = filtered_df["length_avg"].round(2)
filtered_df

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,count,count_avg,length,length_avg
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.84,4,2.81
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.84,11,2.81
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.84,5,2.81
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.seg3...,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.49,2,3.27
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.seg3...,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",True,P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.49,4,3.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8666,ParlaMint-SI_2014-03-03-SDZ6-Redna-22.ana.u242,ParlaMint-SI_2014-03-03-SDZ6-Redna-22.ana.seg8...,"Hvala za besedo, predsedujoča. Pozdrav vsem pr...",Hvala.,Thank you.,False,M_Negative,1.0,4.510695,{'Text_ID': 'ParlaMint-SI-en_2014-03-03-SDZ6-R...,15,3.17,1,3.02
8667,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...","Hvala, gospodu Kovačiču.","Thank you, Mr. Kovacich.",True,P_Neutral,3.0,4.017726,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4,3.08,3,2.49
8668,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...","Da se ne bi še kdo zmotil, obrazložitve glasu ...","Not to be mistaken, the explanation of the voi...",True,P_Neutral,3.0,1.817976,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4,3.08,16,2.49
8669,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Svoje stališče oziroma obrazložitev glasu bo g...,"Mr Grimes, please, will explain his position o...",True,P_Neutral,3.0,3.074007,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4,3.08,9,2.49
8670,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Izvolite.,Here you go.,True,P_Neutral,3.0,3.427290,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4,3.08,1,2.49

In [14]:
mae = (filtered_df["annotation_utt_score"] - filtered_df["length_avg"]).abs().mean()
print(f"MAE: {mae}")

MAE: 1.2844539268827124

### Character-based length avg

In [ ]:
filtered_df.head()

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,count,count_avg,length,length_avg
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.84,4,2.81
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.84,11,2.81
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.84,5,2.81
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.seg3...,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.49,2,3.27
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.seg3...,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",True,P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.49,4,3.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8666,ParlaMint-SI_2014-03-03-SDZ6-Redna-22.ana.u242,ParlaMint-SI_2014-03-03-SDZ6-Redna-22.ana.seg8...,"Hvala za besedo, predsedujoča. Pozdrav vsem pr...",Hvala.,Thank you.,False,M_Negative,1.0,4.510695,{'Text_ID': 'ParlaMint-SI-en_2014-03-03-SDZ6-R...,15,3.17,1,3.02
8667,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...","Hvala, gospodu Kovačiču.","Thank you, Mr. Kovacich.",True,P_Neutral,3.0,4.017726,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4,3.08,3,2.49
8668,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...","Da se ne bi še kdo zmotil, obrazložitve glasu ...","Not to be mistaken, the explanation of the voi...",True,P_Neutral,3.0,1.817976,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4,3.08,16,2.49
8669,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Svoje stališče oziroma obrazložitev glasu bo g...,"Mr Grimes, please, will explain his position o...",True,P_Neutral,3.0,3.074007,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4,3.08,9,2.49
8670,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Izvolite.,Here you go.,True,P_Neutral,3.0,3.427290,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4,3.08,1,2.49

In [17]:
filtered_df["char_length"] = filtered_df["text_sent"].apply(len)
filtered_df.head()

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,count,count_avg,length,length_avg,char_length
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.84,4,2.81,22
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.84,11,2.81,71
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.84,5,2.81,29
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.seg3...,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.49,2,3.27,11
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.seg3...,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",True,P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.49,4,3.27,26

In [18]:
char_avg = (
    filtered_df.groupby('ID')
    .apply(lambda x: (x["annotation_sent"] * x["char_length"]).sum() / x["char_length"].sum())
    .reset_index(name='char_avg')
)

filtered_df = filtered_df.merge(char_avg, on='ID')
filtered_df

/var/folders/l_/t5l44v1s7d9168_x8bm5ly0h0000gn/T/ipykernel_2338/112784802.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  filtered_df.groupby('ID')

,ID,sent_id,text_utt,text_sent,text_en,chair,annotation_utt,annotation_utt_score,annotation_sent,metadata,count,count_avg,length,length_avg,char_length,char_avg
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...",Ni replike na repliko.,There's no replica to the replica.,True,N_Neutral,2.0,2.240412,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.84,4,2.81,22,2.803708
1,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...","Gospa ministrica, potem se boste lahko javili,...","Madam Minister, you'll be able to come forward...",True,N_Neutral,2.0,2.636969,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.84,11,2.81,71,2.803708
2,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.u90,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.ana.se...,"Ni replike na repliko. Gospa ministrica, potem...",Besedo pa ima gospod Gorenak.,Mr. Gorenak has the floor.,True,N_Neutral,2.0,3.639261,{'Text_ID': 'ParlaMint-SI-en_2010-09-07-SDZ5-I...,3,2.84,5,2.81,29,2.803708
3,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.seg3...,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Hvala lepa.,Thank you very much.,True,P_Neutral,3.0,4.084590,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.49,2,3.27,11,3.265325
4,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.u107,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.ana.seg3...,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,Besedo ima Silva Črnugelj.,"The word is ""silva blackugelj.""",True,P_Neutral,3.0,3.340636,{'Text_ID': 'ParlaMint-SI-en_2011-06-16-SDZ5-R...,3,3.49,4,3.27,26,3.265325
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8666,ParlaMint-SI_2014-03-03-SDZ6-Redna-22.ana.u242,ParlaMint-SI_2014-03-03-SDZ6-Redna-22.ana.seg8...,"Hvala za besedo, predsedujoča. Pozdrav vsem pr...",Hvala.,Thank you.,False,M_Negative,1.0,4.510695,{'Text_ID': 'ParlaMint-SI-en_2014-03-03-SDZ6-R...,15,3.17,1,3.02,6,3.017512
8667,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...","Hvala, gospodu Kovačiču.","Thank you, Mr. Kovacich.",True,P_Neutral,3.0,4.017726,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4,3.08,3,2.49,24,2.634149
8668,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...","Da se ne bi še kdo zmotil, obrazložitve glasu ...","Not to be mistaken, the explanation of the voi...",True,P_Neutral,3.0,1.817976,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4,3.08,16,2.49,85,2.634149
8669,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Svoje stališče oziroma obrazložitev glasu bo g...,"Mr Grimes, please, will explain his position o...",True,P_Neutral,3.0,3.074007,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4,3.08,9,2.49,66,2.634149
8670,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.u95,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.ana.se...,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",Izvolite.,Here you go.,True,P_Neutral,3.0,3.427290,{'Text_ID': 'ParlaMint-SI-en_2005-02-01-SDZ4-I...,4,3.08,1,2.49,9,2.634149

In [19]:
filtered_df["char_avg"] = filtered_df["char_avg"].round(2)

In [20]:
mae = (filtered_df["annotation_utt_score"] - filtered_df["char_avg"]).abs().mean()

print(f"Mean Absolute Error (MAE): {mae}")

Mean Absolute Error (MAE): 1.287458193979933