In [1]:
import pandas as pd
import csv

In [2]:
def process_chunk(df_chunk):
    print(df_chunk.head())
def process_jsonl(file_path, chunksize=1000):
    df_list=[]
    for df_chunk in pd.read_json(file_path, lines=True, chunksize=chunksize):
        df_list.append(df_chunk)
    
    full_df = pd.concat(df_list, ignore_index=True)
    return full_df

file_path = '../../ParlaSent-SI/ParlaMint-SI.meta.jsonl'
df = process_jsonl(file_path, chunksize=1000)
df.head()

,sent_id,text,logit,newdoc id,text_en,metadata
0,ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.ana.se...,Spoštovane kolegice poslanke in kolegi poslanc...,4.052144,ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.ana.u1,"Dear fellow Members and fellow Members, ladies...",{'Text_ID': 'ParlaMint-SI-en_2022-04-06-SDZ8-I...
1,ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.ana.se...,Začenjam z nadaljevanjem 99. izredne seje Drža...,3.223034,ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.ana.u1,I'm starting with the 99th Extraordinary Meeti...,{'Text_ID': 'ParlaMint-SI-en_2022-04-06-SDZ8-I...
2,ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.ana.se...,"Obveščen sem, da se današnje seje ne morejo ud...",1.778516,ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.ana.u1,I am informed that today's meeting cannot be a...,{'Text_ID': 'ParlaMint-SI-en_2022-04-06-SDZ8-I...
3,ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.ana.se...,Vse prisotne lepo pozdravljam!,4.814360,ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.ana.u1,I say hello to everyone who's here!,{'Text_ID': 'ParlaMint-SI-en_2022-04-06-SDZ8-I...
4,ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.ana.se...,Prehajamo na 10.,3.219104,ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.ana.u1,We're moving on to 10.,{'Text_ID': 'ParlaMint-SI-en_2022-04-06-SDZ8-I...

In [3]:
df = df.drop(columns={'text_en', 'metadata'})
df = df.rename(columns={'logit':'annotations', 'newdoc id':'utt_id'})
df.head()

,sent_id,text,annotations,utt_id
0,ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.ana.se...,Spoštovane kolegice poslanke in kolegi poslanc...,4.052144,ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.ana.u1
1,ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.ana.se...,Začenjam z nadaljevanjem 99. izredne seje Drža...,3.223034,ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.ana.u1
2,ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.ana.se...,"Obveščen sem, da se današnje seje ne morejo ud...",1.778516,ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.ana.u1
3,ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.ana.se...,Vse prisotne lepo pozdravljam!,4.814360,ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.ana.u1
4,ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.ana.se...,Prehajamo na 10.,3.219104,ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.ana.u1

In [4]:
#Dataset for next step: calcuation of the aggregations of the whole ParlaMint-SI
#Added to gitignore, as file is too large.
df.to_csv('../Datasets/SI_sent_development.csv', index=False)

In [5]:
#Removing additional data to fit the dataset format: id + sent_annotations
df_data = df.drop(columns={'text', 'utt_id'})
df_data.head()

                                             sent_id  annotations
0  ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.ana.se...     4.052144
1  ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.ana.se...     3.223034
2  ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.ana.se...     1.778516
3  ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.ana.se...     4.814360
4  ParlaMint-SI_2022-04-06-SDZ8-Izredna-99.ana.se...     3.219104

In [6]:
df_data.to_csv('../Datasets/ParlaMint-SI_sent.tsv', sep='\t', index=False, encoding='utf-8')
#Added to gitignore, as file is too large.