In [1]:
import pandas as pd
import csv
import os

In [2]:
excel_file = 'SI_annotation.xlsx'
output_directory = '.'
xls = pd.ExcelFile(excel_file)

In [3]:
dataframes = []

for sheet_name in xls.sheet_names:
    df = pd.read_excel(xls, sheet_name=sheet_name)
    csv_file = os.path.join(output_directory, f'{sheet_name}.csv')
    df.to_csv(csv_file, index=False, encoding='utf-8')
    dataframes.append(df)
    print(f"Sheet {sheet_name} exported to {csv_file}")

Sheet pilot1 exported to ./pilot1.csv
Sheet pilot2 exported to ./pilot2.csv
Sheet pilot3 exported to ./pilot3.csv
Sheet pilot4 exported to ./pilot4.csv
Sheet pilot5 exported to ./pilot5.csv
Sheet pilot6 exported to ./pilot6.csv
Sheet main1 exported to ./main1.csv
Sheet main2 exported to ./main2.csv

In [4]:
merged_df = pd.concat(dataframes, ignore_index=True)
merged_df

,id,text,timestamp_tamara,flagged_tamara,comment_tamara,tag_tamara,timestamp_anze,flagged_anze,comment_anze,tag_anze,timestamp_katja,flagged_katja,comment_katja,tag_katja,rev_tamara,rev_anze,rev_katja,final_tag,Unnamed: 13,disagreement6
0,1,"Tako kot sem uvodoma povedal, še vedno mislim,...",2023-02-23 10:08:33,NaN,NaN,P_Neutral,2023-02-23 10:05:56,NaN,It is posible to see documents,P_Neutral,1677143150,NaN,"Statement, but expresses positive hope",P_Neutral,NaN,NaN,NaN,P_Neutral,NaN,NaN
1,2,"Manj ko je beguncev, večji je odpor pred temi ...",2023-02-23 10:09:11,NaN,No direct opinion by the speaker.,N_Neutral,2023-02-23 10:06:26,NaN,NaN,Negative,1677143163,NaN,NaN,Negative,No direct opinion by the speaker.,"Opinion not expressed directly, but implied","Opinion not expressed directly, but implied",Negative,NaN,NaN
2,3,"Drugo vprašanje, ki ste ga izpostavili, je vpr...",2023-02-23 10:09:34,NaN,NaN,P_Neutral,2023-02-23 10:07:22,NaN,NaN,Positive,1677143249,NaN,"Neutral, factual statement",NaN,No direct opinion by the speaker.,Positive topic (socialni dialog),"Neutral, factual statement, not direct opinion",P_Neutral,NaN,NaN
3,4,Če se lahko tako izrazim; »pravica« biti deleg...,2023-02-23 10:10:37,NaN,Sarcasm.,N_Neutral,2023-02-23 10:09:08,NaN,Positive thinking,P_Neutral,1677143451,NaN,Slight sarcasm,N_Neutral,Sarcasm,Because position will be formed,"Sarcasm, otherwise neutral",N_Neutral(S),NaN,NaN
4,5,"Seveda, kjerkoli zavrtajo v Prekmurju, tam pri...",2023-02-23 10:10:57,NaN,Sarcasm.,N_Neutral,2023-02-23 10:10:21,NaN,S,P_Neutral,1677143466,NaN,Sarcasm,NaN,Sarcasm,Sarcasm,Degrading connotation,N_Neutral(S),NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2595,2596,Ustavno sodišče je zavrglo pobudo državnega zb...,2023-06-15 23:58:35,NaN,statement,N_Neutral,NaT,NaN,NaN,NaN,2023-06-19 18:21:47,NaN,NaN,N_Neutral,NaN,NaN,NaN,N_Neutral,NaN,0.0
2596,2597,"Sama, kot predstavnica mlajše generacije, želi...",2023-06-15 23:59:02,NaN,"positive sentiment, but not string enough to b...",P_Neutral,NaT,NaN,NaN,NaN,2023-06-19 18:22:32,1.0,NaN,N_Neutral,NaN,NaN,I have no idea what I was thinking here.,P_Neutral,NaN,1.0
2597,2598,Kakor hitro gre za vprašanje izplačila odškodn...,2023-06-15 23:59:09,NaN,NaN,Negative,NaT,NaN,NaN,NaN,2023-06-19 18:22:38,NaN,NaN,Negative,NaN,NaN,NaN,Negative,NaN,0.0
2598,2599,"Če gledamo te velike nakupovalne centre, saj v...",2023-06-15 23:59:22,NaN,statement,P_Neutral,NaT,NaN,NaN,NaN,2023-06-19 18:22:53,NaN,NaN,P_Neutral,NaN,NaN,NaN,P_Neutral,NaN,0.0
2599,2600,"To je bilo včasih, ko je bila ta vizija še pre...",2023-06-15 23:59:35,NaN,NaN,N_Neutral,NaT,NaN,NaN,NaN,2023-06-19 18:23:11,NaN,NaN,N_Neutral,NaN,NaN,NaN,N_Neutral,NaN,0.0

In [5]:
merged_df.rename(columns={
    "Unnamed: 13":"notes",
    "disagreement6":"disagreement"
}, inplace=True)

In [6]:
merged_df.head()

,id,text,timestamp_tamara,flagged_tamara,comment_tamara,tag_tamara,timestamp_anze,flagged_anze,comment_anze,tag_anze,timestamp_katja,flagged_katja,comment_katja,tag_katja,rev_tamara,rev_anze,rev_katja,final_tag,notes,disagreement
0,1,"Tako kot sem uvodoma povedal, še vedno mislim,...",2023-02-23 10:08:33,NaN,NaN,P_Neutral,2023-02-23 10:05:56,NaN,It is posible to see documents,P_Neutral,1677143150,NaN,"Statement, but expresses positive hope",P_Neutral,NaN,NaN,NaN,P_Neutral,NaN,NaN
1,2,"Manj ko je beguncev, večji je odpor pred temi ...",2023-02-23 10:09:11,NaN,No direct opinion by the speaker.,N_Neutral,2023-02-23 10:06:26,NaN,NaN,Negative,1677143163,NaN,NaN,Negative,No direct opinion by the speaker.,"Opinion not expressed directly, but implied","Opinion not expressed directly, but implied",Negative,NaN,NaN
2,3,"Drugo vprašanje, ki ste ga izpostavili, je vpr...",2023-02-23 10:09:34,NaN,NaN,P_Neutral,2023-02-23 10:07:22,NaN,NaN,Positive,1677143249,NaN,"Neutral, factual statement",NaN,No direct opinion by the speaker.,Positive topic (socialni dialog),"Neutral, factual statement, not direct opinion",P_Neutral,NaN,NaN
3,4,Če se lahko tako izrazim; »pravica« biti deleg...,2023-02-23 10:10:37,NaN,Sarcasm.,N_Neutral,2023-02-23 10:09:08,NaN,Positive thinking,P_Neutral,1677143451,NaN,Slight sarcasm,N_Neutral,Sarcasm,Because position will be formed,"Sarcasm, otherwise neutral",N_Neutral(S),NaN,NaN
4,5,"Seveda, kjerkoli zavrtajo v Prekmurju, tam pri...",2023-02-23 10:10:57,NaN,Sarcasm.,N_Neutral,2023-02-23 10:10:21,NaN,S,P_Neutral,1677143466,NaN,Sarcasm,NaN,Sarcasm,Sarcasm,Degrading connotation,N_Neutral(S),NaN,NaN

In [ ]:
merged_df.to_csv('../Datasets/annotations.csv', index=False, encoding='utf-8')