In [1]:
import pandas as pd
import csv
import krippendorff
import numpy as np

In [2]:
df = pd.read_csv('../Datasets/annotations.csv', delimiter=",", encoding='utf-8')
columns_to_keep = ['tag_tamara', 'tag_katja']
df = df[columns_to_keep]
df

     tag_tamara  tag_katja
0     P_Neutral  P_Neutral
1     N_Neutral   Negative
2     P_Neutral        NaN
3     N_Neutral  N_Neutral
4     N_Neutral        NaN
...         ...        ...
2595  N_Neutral  N_Neutral
2596  P_Neutral  N_Neutral
2597   Negative   Negative
2598  P_Neutral  P_Neutral
2599  N_Neutral  N_Neutral

[2600 rows x 2 columns]

In [3]:
df = df.dropna()
df

     tag_tamara  tag_katja
0     P_Neutral  P_Neutral
1     N_Neutral   Negative
3     N_Neutral  N_Neutral
5     N_Neutral   Negative
6     N_Neutral  N_Neutral
...         ...        ...
2595  N_Neutral  N_Neutral
2596  P_Neutral  N_Neutral
2597   Negative   Negative
2598  P_Neutral  P_Neutral
2599  N_Neutral  N_Neutral

[2487 rows x 2 columns]

In [4]:
unique_labels = pd.unique(df[['tag_tamara', 'tag_katja']].values.ravel())

# Create a mapping of labels to consistent numeric codes
label_to_code = {label: idx for idx, label in enumerate(unique_labels)}

# Map the labels to numeric codes for both annotators
df['tag_tamara_codes'] = df['tag_tamara'].map(label_to_code)
df['tag_katja_codes'] = df['tag_katja'].map(label_to_code)
df

/var/folders/ng/b52w03cd2d31sdjpmc5kyqlh0000gr/T/ipykernel_37030/2397505164.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tag_tamara_codes'] = df['tag_tamara'].map(label_to_code)
/var/folders/ng/b52w03cd2d31sdjpmc5kyqlh0000gr/T/ipykernel_37030/2397505164.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tag_katja_codes'] = df['tag_katja'].map(label_to_code)

     tag_tamara  tag_katja  tag_tamara_codes  tag_katja_codes
0     P_Neutral  P_Neutral                 0                0
1     N_Neutral   Negative                 1                2
3     N_Neutral  N_Neutral                 1                1
5     N_Neutral   Negative                 1                2
6     N_Neutral  N_Neutral                 1                1
...         ...        ...               ...              ...
2595  N_Neutral  N_Neutral                 1                1
2596  P_Neutral  N_Neutral                 0                1
2597   Negative   Negative                 2                2
2598  P_Neutral  P_Neutral                 0                0
2599  N_Neutral  N_Neutral                 1                1

[2487 rows x 4 columns]

In [5]:
data_array = df[['tag_tamara_codes', 'tag_katja_codes']].to_numpy().T
alpha = krippendorff.alpha(reliability_data=data_array, level_of_measurement='nominal')
print(f"Krippendorff's alpha (nominal): {alpha}")

Krippendorff's alpha (nominal): 0.5099808584431593