In [1]:
import csv
import random
import pandas as pd

In [2]:
meta = pd.read_csv("../ParlaMint-SI-meta.csv", encoding='utf-8', delimiter=',')
text = pd.read_csv("../ParlaMint-SI-text.csv", encoding='utf-8', delimiter='\t')

In [3]:
df = pd.merge(meta, text, on='ID', how='left')
df

,Text_ID,ID,Title,Date,Body,Term,Session,Meeting,Sitting,Agenda,...,Speaker_minister,Speaker_party,Speaker_party_name,Party_status,Party_orientation,Speaker_ID,Speaker_name,Speaker_gender,Speaker_birth,Text
0,ParlaMint-SI_2013-06-21-SDZ6-Izredna-39,ParlaMint-SI_2013-06-21-SDZ6-Izredna-39.u1,Zapisi sej Državnega zbora Republike Slovenije...,2013-06-21,Spodnji dom,6. mandat,-,Izredna,-,-,...,notMinister,SD,Socialni demokrati,Coalition,Levo sredinska,VeberJanko,"Veber, Janko",M,1960,Spoštovani kolegice poslanke in kolegi poslanc...
1,ParlaMint-SI_2013-06-21-SDZ6-Izredna-39,ParlaMint-SI_2013-06-21-SDZ6-Izredna-39.u2,Zapisi sej Državnega zbora Republike Slovenije...,2013-06-21,Spodnji dom,6. mandat,-,Izredna,-,-,...,notMinister,-,-,-,-,ČuferUroš,"Čufer, Uroš",M,-,"Spoštovani predsednik Državnega zbora, spoštov..."
2,ParlaMint-SI_2013-06-21-SDZ6-Izredna-39,ParlaMint-SI_2013-06-21-SDZ6-Izredna-39.u3,Zapisi sej Državnega zbora Republike Slovenije...,2013-06-21,Spodnji dom,6. mandat,-,Izredna,-,-,...,notMinister,SD,Socialni demokrati,Coalition,Levo sredinska,VeberJanko,"Veber, Janko",M,1960,Hvala ministru za dopolnilno obrazložitev pred...
3,ParlaMint-SI_2013-06-21-SDZ6-Izredna-39,ParlaMint-SI_2013-06-21-SDZ6-Izredna-39.u4,Zapisi sej Državnega zbora Republike Slovenije...,2013-06-21,Spodnji dom,6. mandat,-,Izredna,-,-,...,notMinister,DL,Državljanska lista,Coalition,Sredinska do desno sredinska,StarmanBojan,"Starman, Bojan",M,1950,"Hvala lepa za besedo, gospod predsednik. Lep p..."
4,ParlaMint-SI_2013-06-21-SDZ6-Izredna-39,ParlaMint-SI_2013-06-21-SDZ6-Izredna-39.u5,Zapisi sej Državnega zbora Republike Slovenije...,2013-06-21,Spodnji dom,6. mandat,-,Izredna,-,-,...,notMinister,SD,Socialni demokrati,Coalition,Levo sredinska,VeberJanko,"Veber, Janko",M,1960,Hvala tudi vam za predstavitev poročila odbora...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311349,ParlaMint-SI_2004-06-15-SDZ3-Redna-37,ParlaMint-SI_2004-06-15-SDZ3-Redna-37.u214,Zapisi sej Državnega zbora Republike Slovenije...,2004-06-15,Spodnji dom,3. mandat,-,Redna,-,-,...,notMinister,ZLSD,Združena lista socialnih demokratov,Coalition,Levo sredinska,PahorBorut,"Pahor, Borut",M,1963,"Dobro, gre za postopkovni predlog, ki je okvir..."
311350,ParlaMint-SI_2004-06-15-SDZ3-Redna-37,ParlaMint-SI_2004-06-15-SDZ3-Redna-37.u215,Zapisi sej Državnega zbora Republike Slovenije...,2004-06-15,Spodnji dom,3. mandat,-,Redna,-,-,...,notMinister,LDS,Liberalna demokracija Slovenije,Coalition,Sredinska do levo sredinska,LavrincMaksimiljan,"Lavrinc, Maksimiljan",M,1948,"65. člen, prvi odstavek poslovnika."
311351,ParlaMint-SI_2004-06-15-SDZ3-Redna-37,ParlaMint-SI_2004-06-15-SDZ3-Redna-37.u216,Zapisi sej Državnega zbora Republike Slovenije...,2004-06-15,Spodnji dom,3. mandat,-,Redna,-,-,...,notMinister,ZLSD,Združena lista socialnih demokratov,Coalition,Levo sredinska,PahorBorut,"Pahor, Borut",M,1963,Posamezne točke dnevnega reda se obravnavajo n...
311352,ParlaMint-SI_2004-06-15-SDZ3-Redna-37,ParlaMint-SI_2004-06-15-SDZ3-Redna-37.u217,Zapisi sej Državnega zbora Republike Slovenije...,2004-06-15,Spodnji dom,3. mandat,-,Redna,-,-,...,notMinister,LDS,Liberalna demokracija Slovenije,Coalition,Sredinska do levo sredinska,LavrincMaksimiljan,"Lavrinc, Maksimiljan",M,1948,"Jutri po končani 17. točki, torej v okviru gla..."
311353,ParlaMint-SI_2004-06-15-SDZ3-Redna-37,ParlaMint-SI_2004-06-15-SDZ3-Redna-37.u218,Zapisi sej Državnega zbora Republike Slovenije...,2004-06-15,Spodnji dom,3. mandat,-,Redna,-,-,...,notMinister,ZLSD,Združena lista socialnih demokratov,Coalition,Levo sredinska,PahorBorut,"Pahor, Borut",M,1963,Ali predlog razumljiv? Saj ni potrebno utemelj...

# Sampling with corpus distribution

Sample each 300th utterance in the DataFrame, to land with 1038 samples. Fruther divide into two datasets: annotation sample (1000 samples) and the dry-run sample (38 samples).
**Note**: The 1000-sample dataset in this first part of the notebook (Datasets/Sample_data.csv, Datasets/Sample.csv) is now obsolete, but is retained in the code as the Test1 sample was generated from it. 

The new dataset is sampled at the end of the notebook ("Sampling new main annotation dataset") and made available under the same name (Datasets/Sample_data.csv and Datasets/Sample.csv)

In [4]:
df_sample = df.iloc[::300, :]
df_sample

,Text_ID,ID,Title,Date,Body,Term,Session,Meeting,Sitting,Agenda,...,Speaker_minister,Speaker_party,Speaker_party_name,Party_status,Party_orientation,Speaker_ID,Speaker_name,Speaker_gender,Speaker_birth,Text
0,ParlaMint-SI_2013-06-21-SDZ6-Izredna-39,ParlaMint-SI_2013-06-21-SDZ6-Izredna-39.u1,Zapisi sej Državnega zbora Republike Slovenije...,2013-06-21,Spodnji dom,6. mandat,-,Izredna,-,-,...,notMinister,SD,Socialni demokrati,Coalition,Levo sredinska,VeberJanko,"Veber, Janko",M,1960,Spoštovani kolegice poslanke in kolegi poslanc...
300,ParlaMint-SI_2013-11-20-SDZ6-Redna-19,ParlaMint-SI_2013-11-20-SDZ6-Redna-19.u147,Zapisi sej Državnega zbora Republike Slovenije...,2013-11-20,Spodnji dom,6. mandat,-,Redna,-,-,...,notMinister,DL,Državljanska lista,Coalition,Sredinska do desno sredinska,KomarPolonca,"Komar, Polonca",F,1967,Hvala lepa. Gospod Černač v imenu predlagatelj...
600,ParlaMint-SI_2013-01-31-SDZ6-Redna-10,ParlaMint-SI_2013-01-31-SDZ6-Redna-10.u149,Zapisi sej Državnega zbora Republike Slovenije...,2013-01-31,Spodnji dom,6. mandat,-,Redna,-,-,...,notMinister,PS,Pozitivna Slovenija,Opposition,Sredinska do levo sredinska,BrunskoleRenata,"Brunskole, Renata",F,1970,"Minister, izvolite."
900,ParlaMint-SI_2013-03-05-SDZ6-Redna-11,ParlaMint-SI_2013-03-05-SDZ6-Redna-11.u43,Zapisi sej Državnega zbora Republike Slovenije...,2013-03-05,Spodnji dom,6. mandat,-,Redna,-,-,...,notMinister,PS,Pozitivna Slovenija,Opposition,Sredinska do levo sredinska,BrunskoleRenata,"Brunskole, Renata",F,1970,Hvala lepa. Besedo ima gospod Mirko Brulc.
1200,ParlaMint-SI_2013-11-27-SDZ6-Redna-19,ParlaMint-SI_2013-11-27-SDZ6-Redna-19.u183,Zapisi sej Državnega zbora Republike Slovenije...,2013-11-27,Spodnji dom,6. mandat,-,Redna,-,-,...,notMinister,PS,Pozitivna Slovenija,Coalition,Sredinska do levo sredinska,BrunskoleRenata,"Brunskole, Renata",F,1970,Hvala lepa. Poslanska skupina Pozitivna Sloven...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309900,ParlaMint-SI_2004-04-22-SDZ3-Izredna-43,ParlaMint-SI_2004-04-22-SDZ3-Izredna-43.u249,Zapisi sej Državnega zbora Republike Slovenije...,2004-04-22,Spodnji dom,3. mandat,-,Izredna,-,-,...,notMinister,NSi,Nova Slovenija – Krščanski demokrati,Opposition,Desno sredinska,SokAlojz,"Sok, Alojz",M,1959,"Ne, ne, saj razumem, da ne, da ta odlok obravn..."
310200,ParlaMint-SI_2004-03-31-SDZ3-Redna-35,ParlaMint-SI_2004-03-31-SDZ3-Redna-35.u17,Zapisi sej Državnega zbora Republike Slovenije...,2004-03-31,Spodnji dom,3. mandat,-,Redna,-,-,...,notMinister,ZLSD,Združena lista socialnih demokratov,Coalition,Levo sredinska,PahorBorut,"Pahor, Borut",M,1963,Kolega Sok.
310500,ParlaMint-SI_2004-02-10-SDZ3-Izredna-40,ParlaMint-SI_2004-02-10-SDZ3-Izredna-40.u247,Zapisi sej Državnega zbora Republike Slovenije...,2004-02-10,Spodnji dom,3. mandat,-,Izredna,-,-,...,notMinister,LDS,Liberalna demokracija Slovenije,Coalition,Sredinska do levo sredinska,AnderličAnton,"Anderlič, Anton",M,1956,Danes smo začeli z osnovno predstavitvijo neka...
310800,ParlaMint-SI_2004-02-27-SDZ3-Redna-34,ParlaMint-SI_2004-02-27-SDZ3-Redna-34.u53,Zapisi sej Državnega zbora Republike Slovenije...,2004-02-27,Spodnji dom,3. mandat,-,Redna,-,-,...,notMinister,ZLSD,Združena lista socialnih demokratov,Coalition,Levo sredinska,PahorBorut,"Pahor, Borut",M,1963,Čas poslanske skupine je potekel.
311100,ParlaMint-SI_2004-04-07-SDZ3-Izredna-42,ParlaMint-SI_2004-04-07-SDZ3-Izredna-42.u128,Zapisi sej Državnega zbora Republike Slovenije...,2004-04-07,Spodnji dom,3. mandat,-,Izredna,-,-,...,notMinister,ZLSD,Združena lista socialnih demokratov,Coalition,Levo sredinska,PahorBorut,"Pahor, Borut",M,1963,"Kot rečeno, stališča poslanskih skupin bo seda..."

In [5]:
df_1000 = df_sample.iloc[:1000, :]
df_test = df_sample.iloc[1000:, :]
#df_1000.to_csv("../Datasets/Sample_data.csv", index=False)

In [6]:
df_1000_filtered = df_1000[['ID', 'Text']]
df_test_filtered = df_test[['ID', 'Text']]

In [7]:
header_list= ['ID','Text','Annotation', 'Comments', 'Flag']

df_1000_filtered = df_1000_filtered.reindex(columns = header_list)
df_test_filtered = df_test_filtered.reindex(columns = header_list)

In [8]:
#df_1000_filtered.to_csv("../Datasets/Sample.csv", index = False)
#df_test_filtered.to_csv("../Datasets/Tests_sample.csv", index = False)

# Test 1 sample
Splitting the test run sample (38 utterances) into two for two test rounds (each 19 utterances)

In [9]:
test_data1 = df_test.iloc[:19, :]
test_data1.head()

,Text_ID,ID,Title,Date,Body,Term,Session,Meeting,Sitting,Agenda,...,Speaker_minister,Speaker_party,Speaker_party_name,Party_status,Party_orientation,Speaker_ID,Speaker_name,Speaker_gender,Speaker_birth,Text
300000,ParlaMint-SI_2004-03-23-SDZ3-Redna-35,ParlaMint-SI_2004-03-23-SDZ3-Redna-35.u243,Zapisi sej Državnega zbora Republike Slovenije...,2004-03-23,Spodnji dom,3. mandat,-,Redna,-,-,...,notMinister,-,-,-,-,BizjakIvan,"Bizjak, Ivan",M,1956,"Gospod predsednik, ker je bil k predlogu zakon..."
300300,ParlaMint-SI_2004-04-09-SDZ3-Izredna-42,ParlaMint-SI_2004-04-09-SDZ3-Izredna-42.u44,Zapisi sej Državnega zbora Republike Slovenije...,2004-04-09,Spodnji dom,3. mandat,-,Izredna,-,-,...,notMinister,NSi,Nova Slovenija – Krščanski demokrati,Opposition,Desno sredinska,DrobničJanez,"Drobnič, Janez",M,1957,"Hvala, gospod predsedujoči. Ta amandma, ki smo..."
300600,ParlaMint-SI_2004-03-24-SDZ3-Redna-35,ParlaMint-SI_2004-03-24-SDZ3-Redna-35.u165,Zapisi sej Državnega zbora Republike Slovenije...,2004-03-24,Spodnji dom,3. mandat,-,Redna,-,-,...,notMinister,LDS,Liberalna demokracija Slovenije,Coalition,Sredinska do levo sredinska,AvšičJože,"Avšič, Jože",M,1949,"Hvala. Še enkrat sem se oglasil, čeprav sem mi..."
300900,ParlaMint-SI_2004-03-25-SDZ3-Redna-35,ParlaMint-SI_2004-03-25-SDZ3-Redna-35.u167,Zapisi sej Državnega zbora Republike Slovenije...,2004-03-25,Spodnji dom,3. mandat,-,Redna,-,-,...,notMinister,LDS,Liberalna demokracija Slovenije,Coalition,Sredinska do levo sredinska,MaršičDorijan,"Maršič, Dorijan",M,1962,Spoštovane kolegice in kolegi. Ko obravnavamo ...
301200,ParlaMint-SI_2004-09-01-SDZ3-Izredna-50,ParlaMint-SI_2004-09-01-SDZ3-Izredna-50.u158,Zapisi sej Državnega zbora Republike Slovenije...,2004-09-01,Spodnji dom,3. mandat,-,Izredna,-,-,...,notMinister,LDS,Liberalna demokracija Slovenije,Coalition,Sredinska do levo sredinska,PavliničKrebsIrma,"Pavlinič Krebs, Irma",F,1963,Hvala lepa. Stališče poslanske skupine Demokra...

In [10]:
test1 = df_test_filtered.iloc[:19, :]
test1.head()

,ID,Text,Annotation,Comments,Flag
300000,ParlaMint-SI_2004-03-23-SDZ3-Redna-35.u243,"Gospod predsednik, ker je bil k predlogu zakon...",NaN,NaN,NaN
300300,ParlaMint-SI_2004-04-09-SDZ3-Izredna-42.u44,"Hvala, gospod predsedujoči. Ta amandma, ki smo...",NaN,NaN,NaN
300600,ParlaMint-SI_2004-03-24-SDZ3-Redna-35.u165,"Hvala. Še enkrat sem se oglasil, čeprav sem mi...",NaN,NaN,NaN
300900,ParlaMint-SI_2004-03-25-SDZ3-Redna-35.u167,Spoštovane kolegice in kolegi. Ko obravnavamo ...,NaN,NaN,NaN
301200,ParlaMint-SI_2004-09-01-SDZ3-Izredna-50.u158,Hvala lepa. Stališče poslanske skupine Demokra...,NaN,NaN,NaN

In [11]:
test1_procedural = test_data1[test_data1['Speaker_role'] == 'Predsedujoči']
test1_procedural = len(test1_procedural)
test1_procedural

9

In [12]:
test1.to_csv("../Datasets/Test1_sample.csv", index=False)

Test1 was used as a dataset for the first test annotation: 
AAI: 0.83 
Notes: many procedual utterances (very easy to annotate), could consider adding several additional instances (40-50) to the sample, including the chair utterances.

# Test 2 sample

In [13]:
test2 = df.iloc[::100, :]
test2.head()

,Text_ID,ID,Title,Date,Body,Term,Session,Meeting,Sitting,Agenda,...,Speaker_minister,Speaker_party,Speaker_party_name,Party_status,Party_orientation,Speaker_ID,Speaker_name,Speaker_gender,Speaker_birth,Text
0,ParlaMint-SI_2013-06-21-SDZ6-Izredna-39,ParlaMint-SI_2013-06-21-SDZ6-Izredna-39.u1,Zapisi sej Državnega zbora Republike Slovenije...,2013-06-21,Spodnji dom,6. mandat,-,Izredna,-,-,...,notMinister,SD,Socialni demokrati,Coalition,Levo sredinska,VeberJanko,"Veber, Janko",M,1960,Spoštovani kolegice poslanke in kolegi poslanc...
100,ParlaMint-SI_2013-04-26-SDZ6-Izredna-33,ParlaMint-SI_2013-04-26-SDZ6-Izredna-33.u41,Zapisi sej Državnega zbora Republike Slovenije...,2013-04-26,Spodnji dom,6. mandat,-,Izredna,-,-,...,notMinister,PS,Pozitivna Slovenija,Coalition,Sredinska do levo sredinska,BrunskoleRenata,"Brunskole, Renata",F,1970,"Hvala lepa, spoštovani gospod predsednik. Gosp..."
200,ParlaMint-SI_2013-11-20-SDZ6-Redna-19,ParlaMint-SI_2013-11-20-SDZ6-Redna-19.u47,Zapisi sej Državnega zbora Republike Slovenije...,2013-11-20,Spodnji dom,6. mandat,-,Redna,-,-,...,notMinister,DL,Državljanska lista,Coalition,Sredinska do desno sredinska,KomarPolonca,"Komar, Polonca",F,1967,"Hvala lepa. Gospod Černač, izvolite v imenu pr..."
300,ParlaMint-SI_2013-11-20-SDZ6-Redna-19,ParlaMint-SI_2013-11-20-SDZ6-Redna-19.u147,Zapisi sej Državnega zbora Republike Slovenije...,2013-11-20,Spodnji dom,6. mandat,-,Redna,-,-,...,notMinister,DL,Državljanska lista,Coalition,Sredinska do desno sredinska,KomarPolonca,"Komar, Polonca",F,1967,Hvala lepa. Gospod Černač v imenu predlagatelj...
400,ParlaMint-SI_2013-11-20-SDZ6-Redna-19,ParlaMint-SI_2013-11-20-SDZ6-Redna-19.u247,Zapisi sej Državnega zbora Republike Slovenije...,2013-11-20,Spodnji dom,6. mandat,-,Redna,-,-,...,notMinister,PS,Pozitivna Slovenija,Coalition,Sredinska do levo sredinska,MöderndorferJankoJani,"Möderndorfer, Jani",M,1965,Bom zelo kratek. Tam za mizo smo imeli vodje p...

In [14]:
test2 = test2.iloc[:50, :]
test2_procedural = test2[test2['Speaker_role'] == 'Predsedujoči']
test2_procedural.head()

,Text_ID,ID,Title,Date,Body,Term,Session,Meeting,Sitting,Agenda,...,Speaker_minister,Speaker_party,Speaker_party_name,Party_status,Party_orientation,Speaker_ID,Speaker_name,Speaker_gender,Speaker_birth,Text
0,ParlaMint-SI_2013-06-21-SDZ6-Izredna-39,ParlaMint-SI_2013-06-21-SDZ6-Izredna-39.u1,Zapisi sej Državnega zbora Republike Slovenije...,2013-06-21,Spodnji dom,6. mandat,-,Izredna,-,-,...,notMinister,SD,Socialni demokrati,Coalition,Levo sredinska,VeberJanko,"Veber, Janko",M,1960,Spoštovani kolegice poslanke in kolegi poslanc...
200,ParlaMint-SI_2013-11-20-SDZ6-Redna-19,ParlaMint-SI_2013-11-20-SDZ6-Redna-19.u47,Zapisi sej Državnega zbora Republike Slovenije...,2013-11-20,Spodnji dom,6. mandat,-,Redna,-,-,...,notMinister,DL,Državljanska lista,Coalition,Sredinska do desno sredinska,KomarPolonca,"Komar, Polonca",F,1967,"Hvala lepa. Gospod Černač, izvolite v imenu pr..."
300,ParlaMint-SI_2013-11-20-SDZ6-Redna-19,ParlaMint-SI_2013-11-20-SDZ6-Redna-19.u147,Zapisi sej Državnega zbora Republike Slovenije...,2013-11-20,Spodnji dom,6. mandat,-,Redna,-,-,...,notMinister,DL,Državljanska lista,Coalition,Sredinska do desno sredinska,KomarPolonca,"Komar, Polonca",F,1967,Hvala lepa. Gospod Černač v imenu predlagatelj...
500,ParlaMint-SI_2013-01-31-SDZ6-Redna-10,ParlaMint-SI_2013-01-31-SDZ6-Redna-10.u49,Zapisi sej Državnega zbora Republike Slovenije...,2013-01-31,Spodnji dom,6. mandat,-,Redna,-,-,...,notMinister,SLS,Slovenska ljudska stranka,Coalition,Desno sredinska,PresečnikJakob,"Presečnik, Jakob",M,1948,"Hvala lepa. Besedo ima gospa Alenka Jeraj, pri..."
600,ParlaMint-SI_2013-01-31-SDZ6-Redna-10,ParlaMint-SI_2013-01-31-SDZ6-Redna-10.u149,Zapisi sej Državnega zbora Republike Slovenije...,2013-01-31,Spodnji dom,6. mandat,-,Redna,-,-,...,notMinister,PS,Pozitivna Slovenija,Opposition,Sredinska do levo sredinska,BrunskoleRenata,"Brunskole, Renata",F,1970,"Minister, izvolite."

In [15]:
header_list= ['ID','Text','Annotation', 'Comments', 'Flag']
test2_procedural = test2_procedural.reindex(columns = header_list)
test2_procedural.head()

,ID,Text,Annotation,Comments,Flag
0,ParlaMint-SI_2013-06-21-SDZ6-Izredna-39.u1,Spoštovani kolegice poslanke in kolegi poslanc...,NaN,NaN,NaN
200,ParlaMint-SI_2013-11-20-SDZ6-Redna-19.u47,"Hvala lepa. Gospod Černač, izvolite v imenu pr...",NaN,NaN,NaN
300,ParlaMint-SI_2013-11-20-SDZ6-Redna-19.u147,Hvala lepa. Gospod Černač v imenu predlagatelj...,NaN,NaN,NaN
500,ParlaMint-SI_2013-01-31-SDZ6-Redna-10.u49,"Hvala lepa. Besedo ima gospa Alenka Jeraj, pri...",NaN,NaN,NaN
600,ParlaMint-SI_2013-01-31-SDZ6-Redna-10.u149,"Minister, izvolite.",NaN,NaN,NaN

Test 2 includes 24 instances of procedural speech, accounting for almost 50% of the test dataset, as is the case for the original dataset and all other tests.

In [16]:
test2 = test2.reindex(columns = header_list)
test2.to_csv("../Datasets/Test2_sample.csv", index=False)

# Test3 sample

In [17]:
test3 = df.iloc[::200, :]
test3 = test3.sample(n=50, random_state=42)
test3.head()

,Text_ID,ID,Title,Date,Body,Term,Session,Meeting,Sitting,Agenda,...,Speaker_minister,Speaker_party,Speaker_party_name,Party_status,Party_orientation,Speaker_ID,Speaker_name,Speaker_gender,Speaker_birth,Text
299200,ParlaMint-SI_2004-01-27-SDZ3-Redna-33,ParlaMint-SI_2004-01-27-SDZ3-Redna-33.u194,Zapisi sej Državnega zbora Republike Slovenije...,2004-01-27,Spodnji dom,3. mandat,-,Redna,-,-,...,notMinister,ZLSD,Združena lista socialnih demokratov,Coalition,Levo sredinska,PahorBorut,"Pahor, Borut",M,1963,"Magister Drobnič, ste želeli besedo? Prosim."
33600,ParlaMint-SI_2015-07-14-SDZ7-Redna-10,ParlaMint-SI_2015-07-14-SDZ7-Redna-10.u428,Zapisi sej Državnega zbora Republike Slovenije...,2015-07-14,Spodnji dom,7. mandat,-,Redna,-,-,...,notMinister,SMC,Stranka modernega centra,Coalition,Sredinska do levo sredinska,BrglezMilan,"Brglez, Milan",M,1967,"Gospa Anja Bah Žibert, imate besedo, da zahtev..."
70600,ParlaMint-SI_2008-03-05-SDZ4-Izredna-34,ParlaMint-SI_2008-03-05-SDZ4-Izredna-34.u28,Zapisi sej Državnega zbora Republike Slovenije...,2008-03-05,Spodnji dom,4. mandat,-,Izredna,-,-,...,notMinister,Zares,Zares - nova politika,-,Levo sredinska,LahovnikMatej,"Lahovnik, Matej",M,1971,Hvala lepa. No sedaj smo pravzaprav lahko vide...
93600,ParlaMint-SI_2006-05-24-SDZ4-Redna-17,ParlaMint-SI_2006-05-24-SDZ4-Redna-17.u82,Zapisi sej Državnega zbora Republike Slovenije...,2006-05-24,Spodnji dom,4. mandat,-,Redna,-,-,...,notMinister,-,-,-,-,StarinaKosemAdrijana,"Starina Kosem, Adrijana",F,-,Hvala lepa. Samo na kratko. Vlada podpira aman...
282000,ParlaMint-SI_2002-09-24-SDZ3-Redna-18,ParlaMint-SI_2002-09-24-SDZ3-Redna-18.u52,Zapisi sej Državnega zbora Republike Slovenije...,2002-09-24,Spodnji dom,3. mandat,-,Redna,-,-,...,notMinister,SDS,Socialdemokratska stranka Slovenije,-,Desna,RuparPavel,"Rupar, Pavel",M,1960,"Spoštovana predsedujoča! Gospa ministrica, kol..."

In [18]:
headers= ['ID','Text','Annotation', 'Comments', 'Flag', 'Chair']
test3['Chair'] = test3['Speaker_role'] == 'Predsedujoči'
test3.head()

,Text_ID,ID,Title,Date,Body,Term,Session,Meeting,Sitting,Agenda,...,Speaker_party,Speaker_party_name,Party_status,Party_orientation,Speaker_ID,Speaker_name,Speaker_gender,Speaker_birth,Text,Chair
299200,ParlaMint-SI_2004-01-27-SDZ3-Redna-33,ParlaMint-SI_2004-01-27-SDZ3-Redna-33.u194,Zapisi sej Državnega zbora Republike Slovenije...,2004-01-27,Spodnji dom,3. mandat,-,Redna,-,-,...,ZLSD,Združena lista socialnih demokratov,Coalition,Levo sredinska,PahorBorut,"Pahor, Borut",M,1963,"Magister Drobnič, ste želeli besedo? Prosim.",True
33600,ParlaMint-SI_2015-07-14-SDZ7-Redna-10,ParlaMint-SI_2015-07-14-SDZ7-Redna-10.u428,Zapisi sej Državnega zbora Republike Slovenije...,2015-07-14,Spodnji dom,7. mandat,-,Redna,-,-,...,SMC,Stranka modernega centra,Coalition,Sredinska do levo sredinska,BrglezMilan,"Brglez, Milan",M,1967,"Gospa Anja Bah Žibert, imate besedo, da zahtev...",True
70600,ParlaMint-SI_2008-03-05-SDZ4-Izredna-34,ParlaMint-SI_2008-03-05-SDZ4-Izredna-34.u28,Zapisi sej Državnega zbora Republike Slovenije...,2008-03-05,Spodnji dom,4. mandat,-,Izredna,-,-,...,Zares,Zares - nova politika,-,Levo sredinska,LahovnikMatej,"Lahovnik, Matej",M,1971,Hvala lepa. No sedaj smo pravzaprav lahko vide...,False
93600,ParlaMint-SI_2006-05-24-SDZ4-Redna-17,ParlaMint-SI_2006-05-24-SDZ4-Redna-17.u82,Zapisi sej Državnega zbora Republike Slovenije...,2006-05-24,Spodnji dom,4. mandat,-,Redna,-,-,...,-,-,-,-,StarinaKosemAdrijana,"Starina Kosem, Adrijana",F,-,Hvala lepa. Samo na kratko. Vlada podpira aman...,False
282000,ParlaMint-SI_2002-09-24-SDZ3-Redna-18,ParlaMint-SI_2002-09-24-SDZ3-Redna-18.u52,Zapisi sej Državnega zbora Republike Slovenije...,2002-09-24,Spodnji dom,3. mandat,-,Redna,-,-,...,SDS,Socialdemokratska stranka Slovenije,-,Desna,RuparPavel,"Rupar, Pavel",M,1960,"Spoštovana predsedujoča! Gospa ministrica, kol...",False

In [19]:
test3 = test3.reindex(columns=headers)
test3.head()

,ID,Text,Annotation,Comments,Flag,Chair
299200,ParlaMint-SI_2004-01-27-SDZ3-Redna-33.u194,"Magister Drobnič, ste želeli besedo? Prosim.",NaN,NaN,NaN,True
33600,ParlaMint-SI_2015-07-14-SDZ7-Redna-10.u428,"Gospa Anja Bah Žibert, imate besedo, da zahtev...",NaN,NaN,NaN,True
70600,ParlaMint-SI_2008-03-05-SDZ4-Izredna-34.u28,Hvala lepa. No sedaj smo pravzaprav lahko vide...,NaN,NaN,NaN,False
93600,ParlaMint-SI_2006-05-24-SDZ4-Redna-17.u82,Hvala lepa. Samo na kratko. Vlada podpira aman...,NaN,NaN,NaN,False
282000,ParlaMint-SI_2002-09-24-SDZ3-Redna-18.u52,"Spoštovana predsedujoča! Gospa ministrica, kol...",NaN,NaN,NaN,False

In [20]:
test3.to_csv("../Datasets/Test3_sample.csv", index=False)
test3.to_excel("../Datasets/Test3_sample.xlsx", index=False)

# Checking for duplicates between test datasets and the initial dataset (Sample.csv)

In [21]:
test3 = test3.drop(columns=['Chair'])

df_to_remove = pd.concat([test1, test2, test3])
df_to_remove

,ID,Text,Annotation,Comments,Flag
300000,ParlaMint-SI_2004-03-23-SDZ3-Redna-35.u243,"Gospod predsednik, ker je bil k predlogu zakon...",NaN,NaN,NaN
300300,ParlaMint-SI_2004-04-09-SDZ3-Izredna-42.u44,"Hvala, gospod predsedujoči. Ta amandma, ki smo...",NaN,NaN,NaN
300600,ParlaMint-SI_2004-03-24-SDZ3-Redna-35.u165,"Hvala. Še enkrat sem se oglasil, čeprav sem mi...",NaN,NaN,NaN
300900,ParlaMint-SI_2004-03-25-SDZ3-Redna-35.u167,Spoštovane kolegice in kolegi. Ko obravnavamo ...,NaN,NaN,NaN
301200,ParlaMint-SI_2004-09-01-SDZ3-Izredna-50.u158,Hvala lepa. Stališče poslanske skupine Demokra...,NaN,NaN,NaN
...,...,...,...,...,...
172400,ParlaMint-SI_2010-11-17-SDZ5-Redna-22.u84,"Hvala lepa. Obrazložitev glasu, Julijana Bizja...",NaN,NaN,NaN
49400,ParlaMint-SI_2012-03-22-SDZ6-Izredna-09.u31,Hvala. Končali smo predstavitev stališč poslan...,NaN,NaN,NaN
240400,ParlaMint-SI_2016-01-26-SDZ7-Redna-15.u85,Hvala lepa. Besedo ima gospod Bojan Podkrajšek.,NaN,NaN,NaN
70400,ParlaMint-SI_2008-04-01-SDZ4-Redna-37.u92,"Hvala za besedo, spoštovani gospod predsedujoč...",NaN,NaN,NaN
183600,ParlaMint-SI_2019-12-16-SDZ8-Redna-14.u156,"Hvala za dodatne odgovore in pojasnila, minist...",NaN,NaN,NaN

In [22]:
df_1000_filtered

,ID,Text,Annotation,Comments,Flag
0,ParlaMint-SI_2013-06-21-SDZ6-Izredna-39.u1,Spoštovani kolegice poslanke in kolegi poslanc...,NaN,NaN,NaN
300,ParlaMint-SI_2013-11-20-SDZ6-Redna-19.u147,Hvala lepa. Gospod Černač v imenu predlagatelj...,NaN,NaN,NaN
600,ParlaMint-SI_2013-01-31-SDZ6-Redna-10.u149,"Minister, izvolite.",NaN,NaN,NaN
900,ParlaMint-SI_2013-03-05-SDZ6-Redna-11.u43,Hvala lepa. Besedo ima gospod Mirko Brulc.,NaN,NaN,NaN
1200,ParlaMint-SI_2013-11-27-SDZ6-Redna-19.u183,Hvala lepa. Poslanska skupina Pozitivna Sloven...,NaN,NaN,NaN
...,...,...,...,...,...
298500,ParlaMint-SI_2004-07-09-SDZ3-Redna-38.u63,Hvala lepa za predstavitev poročila odbora. Ke...,NaN,NaN,NaN
298800,ParlaMint-SI_2004-05-31-SDZ3-Izredna-46.u246,Kolega Sok.,NaN,NaN,NaN
299100,ParlaMint-SI_2004-01-27-SDZ3-Redna-33.u94,"Hvala lepa, gospod podpredsednik. Predstavnice...",NaN,NaN,NaN
299400,ParlaMint-SI_2004-03-29-SDZ3-Redna-35.u152,Spoštovani prisotni! V imenu poslanske skupine...,NaN,NaN,NaN
299700,ParlaMint-SI_2004-04-05-SDZ3-Izredna-42.u67,"Tudi jaz ne bom podprl amandmaja k 4. členu, k...",NaN,NaN,NaN

### Check for duplicates in the original dataset (Sample.csv)
Checking for duplicates to remove any duplicates before main annotation.

In [23]:
df_to_remove = df_to_remove.drop_duplicates()
duplicated_rows = df_1000_filtered[df_1000_filtered .apply(tuple, axis=1).isin(df_to_remove.apply(tuple, axis=1))]
duplicated_rows

,ID,Text,Annotation,Comments,Flag
0,ParlaMint-SI_2013-06-21-SDZ6-Izredna-39.u1,Spoštovani kolegice poslanke in kolegi poslanc...,NaN,NaN,NaN
300,ParlaMint-SI_2013-11-20-SDZ6-Redna-19.u147,Hvala lepa. Gospod Černač v imenu predlagatelj...,NaN,NaN,NaN
600,ParlaMint-SI_2013-01-31-SDZ6-Redna-10.u149,"Minister, izvolite.",NaN,NaN,NaN
900,ParlaMint-SI_2013-03-05-SDZ6-Redna-11.u43,Hvala lepa. Besedo ima gospod Mirko Brulc.,NaN,NaN,NaN
1200,ParlaMint-SI_2013-11-27-SDZ6-Redna-19.u183,Hvala lepa. Poslanska skupina Pozitivna Sloven...,NaN,NaN,NaN
1500,ParlaMint-SI_2013-06-18-SDZ6-Redna-15.u165,Hvala lepa. Kot sem napovedal že v stališču po...,NaN,NaN,NaN
1800,ParlaMint-SI_2013-06-20-SDZ6-Redna-15.u60,"Povejte, prosim, kateri so zaslužni za to, da ...",NaN,NaN,NaN
2100,ParlaMint-SI_2013-04-24-SDZ6-Redna-13.u53,Hvala. Mag. Marko Pogačnik bo predstavil stali...,NaN,NaN,NaN
2400,ParlaMint-SI_2013-12-12-SDZ6-Izredna-50.u47,"Hvala lepa. Kot predlagatelj ste se javili, go...",NaN,NaN,NaN
2700,ParlaMint-SI_2013-11-14-SDZ6-Izredna-47.u195,Hvala. Besedo ima gospod Matevž Frangež. Izvol...,NaN,NaN,NaN
3000,ParlaMint-SI_2013-11-14-SDZ6-Izredna-47.u495,Res so bili koalicijski poslanci doslej bolj r...,NaN,NaN,NaN
3300,ParlaMint-SI_2013-11-14-SDZ6-Izredna-47.u795,"Želi še kdo obrazložiti glas? Ugotavljam, da n...",NaN,NaN,NaN
3600,ParlaMint-SI_2013-09-20-SDZ6-Izredna-43.u78,Hvala lepa. To vsekakor zahteva nek odziv na t...,NaN,NaN,NaN
3900,ParlaMint-SI_2013-03-27-SDZ6-Redna-12.u72,"Spoštovani gospod predsednik, hvala za besedo....",NaN,NaN,NaN
4200,ParlaMint-SI_2013-11-18-SDZ6-Redna-19.u218,Hvala. V zvezi s problematiko ravnanja z odpad...,NaN,NaN,NaN
4500,ParlaMint-SI_2013-06-17-SDZ6-Redna-15.u37,Hvala. Postopkovno zahtevo ima gospa Ljudmila ...,NaN,NaN,NaN
4800,ParlaMint-SI_2013-06-17-SDZ6-Redna-15.u337,"Hvala za dodatno vprašanje. Dejansko je res, g...",NaN,NaN,NaN
6000,ParlaMint-SI_2013-11-11-SDZ6-Izredna-47.u45,Hvala lepa. Naslednji je prijavljen k razpravi...,NaN,NaN,NaN
28200,ParlaMint-SI_2014-05-14-SDZ6-Izredna-64.u100,"[[…]]kar seveda govori o tem, da ta trend ni v...",NaN,NaN,NaN
32400,ParlaMint-SI_2022-03-14-SDZ8-Redna-30.u260,"Hvala lepa. Gospa poslanka, imate besedo za po...",NaN,NaN,NaN
33600,ParlaMint-SI_2015-07-14-SDZ7-Redna-10.u428,"Gospa Anja Bah Žibert, imate besedo, da zahtev...",NaN,NaN,NaN
48000,ParlaMint-SI_2015-04-24-SDZ7-Redna-07.u21,Prosim! [[oglašanje iz dvorane]] Prvi del pred...,NaN,NaN,NaN
52200,ParlaMint-SI_2012-12-19-SDZ6-Redna-09.u43,"Hvala lepa. Vidim, da je še želja po razpravi,...",NaN,NaN,NaN
70200,ParlaMint-SI_2008-07-11-SDZ4-Redna-41.u10,"Hvala lepa za besedo, gospod predsednik. Spošt...",NaN,NaN,NaN
70800,ParlaMint-SI_2008-03-05-SDZ4-Izredna-34.u228,Hvala gospod podpredsednik za dano možnost. Bo...,NaN,NaN,NaN
93600,ParlaMint-SI_2006-05-24-SDZ4-Redna-17.u82,Hvala lepa. Samo na kratko. Vlada podpira aman...,NaN,NaN,NaN
130200,ParlaMint-SI_2009-06-16-SDZ5-Redna-07.u389,Hvala lepa. Ta razprava je nujna predvsem zard...,NaN,NaN,NaN
171600,ParlaMint-SI_2010-04-19-SDZ5-Redna-16.u315,Hvala. Želite še besedo gospa ministrica? Ne. ...,NaN,NaN,NaN
183600,ParlaMint-SI_2019-12-16-SDZ8-Redna-14.u156,"Hvala za dodatne odgovore in pojasnila, minist...",NaN,NaN,NaN
282000,ParlaMint-SI_2002-09-24-SDZ3-Redna-18.u52,"Spoštovana predsedujoča! Gospa ministrica, kol...",NaN,NaN,NaN

### Removing identified duplicates

In [24]:
df1_remove = df_1000_filtered[~df_1000_filtered.apply(tuple, axis=1).isin(df_to_remove.apply(tuple, axis=1))]
df1_remove

,ID,Text,Annotation,Comments,Flag
5100,ParlaMint-SI_2013-12-13-SDZ6-Izredna-50.u24,"Hvala za besedo. Spoštovane kolegice, spoštova...",NaN,NaN,NaN
5400,ParlaMint-SI_2013-12-13-SDZ6-Izredna-50.u324,Hvala lepa. Besedo ima Poslanska skupina Držav...,NaN,NaN,NaN
5700,ParlaMint-SI_2013-11-22-SDZ6-Redna-19.u231,Hvala. Besedo ima gospod Jožef Jerovšek.,NaN,NaN,NaN
6300,ParlaMint-SI_2013-11-19-SDZ6-Redna-19.u157,"Hvala lepa. Gospod minister, izvolite.",NaN,NaN,NaN
6600,ParlaMint-SI_2013-11-19-SDZ6-Redna-19.u457,"Hvala lepa, gospa predsedujoča. Ta amandma bom...",NaN,NaN,NaN
...,...,...,...,...,...
298500,ParlaMint-SI_2004-07-09-SDZ3-Redna-38.u63,Hvala lepa za predstavitev poročila odbora. Ke...,NaN,NaN,NaN
298800,ParlaMint-SI_2004-05-31-SDZ3-Izredna-46.u246,Kolega Sok.,NaN,NaN,NaN
299100,ParlaMint-SI_2004-01-27-SDZ3-Redna-33.u94,"Hvala lepa, gospod podpredsednik. Predstavnice...",NaN,NaN,NaN
299400,ParlaMint-SI_2004-03-29-SDZ3-Redna-35.u152,Spoštovani prisotni! V imenu poslanske skupine...,NaN,NaN,NaN
299700,ParlaMint-SI_2004-04-05-SDZ3-Izredna-42.u67,"Tudi jaz ne bom podprl amandmaja k 4. členu, k...",NaN,NaN,NaN

# Sampling new main dataset

To facilitate a new main annotation (n=1000) dataset without duplicates from test datasets, we resampled the dataset to sample each 309th utterance.

In [25]:
df_new = df.iloc[::309]

In [26]:
# Remove the first (0) row as this will always be a duplicate.
df_new = df_new.iloc[1:1001, :]
df_new

,Text_ID,ID,Title,Date,Body,Term,Session,Meeting,Sitting,Agenda,...,Speaker_minister,Speaker_party,Speaker_party_name,Party_status,Party_orientation,Speaker_ID,Speaker_name,Speaker_gender,Speaker_birth,Text
309,ParlaMint-SI_2013-11-20-SDZ6-Redna-19,ParlaMint-SI_2013-11-20-SDZ6-Redna-19.u156,Zapisi sej Državnega zbora Republike Slovenije...,2013-11-20,Spodnji dom,6. mandat,-,Redna,-,-,...,notMinister,SDS,Slovenska demokratska stranka,Opposition,Desna,TankoJože,"Tanko, Jože",M,1956,"Hvala lepa, spoštovana predsedujoča! Mi danes ..."
618,ParlaMint-SI_2013-01-31-SDZ6-Redna-10,ParlaMint-SI_2013-01-31-SDZ6-Redna-10.u167,Zapisi sej Državnega zbora Republike Slovenije...,2013-01-31,Spodnji dom,6. mandat,-,Redna,-,-,...,notMinister,PS,Pozitivna Slovenija,Opposition,Sredinska do levo sredinska,BrunskoleRenata,"Brunskole, Renata",F,1970,"Hvala lepa. Vljudno bi prosila, da poskušamo d..."
927,ParlaMint-SI_2013-03-05-SDZ6-Redna-11,ParlaMint-SI_2013-03-05-SDZ6-Redna-11.u70,Zapisi sej Državnega zbora Republike Slovenije...,2013-03-05,Spodnji dom,6. mandat,-,Redna,-,-,...,notMinister,SDS,Slovenska demokratska stranka,Coalition,Desna,IrglEva,"Irgl, Eva",F,1976,Še enkrat hvala za besedo in lepo pozdravljeni...
1236,ParlaMint-SI_2013-11-27-SDZ6-Redna-19,ParlaMint-SI_2013-11-27-SDZ6-Redna-19.u219,Zapisi sej Državnega zbora Republike Slovenije...,2013-11-27,Spodnji dom,6. mandat,-,Redna,-,-,...,notMinister,SD,Socialni demokrati,Coalition,Levo sredinska,VeberJanko,"Veber, Janko",M,1960,Hvala. Dr. Ljubica Jelušič bo predstavila stal...
1545,ParlaMint-SI_2013-03-05-SDZ6-Izredna-29,ParlaMint-SI_2013-03-05-SDZ6-Izredna-29.u20,Zapisi sej Državnega zbora Republike Slovenije...,2013-03-05,Spodnji dom,6. mandat,-,Izredna,-,-,...,notMinister,SD,Socialni demokrati,Opposition,Levo sredinska,VeberJanko,"Veber, Janko",M,1960,Hvala tudi vam. V imenu Poslanske skupine Pozi...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307764,ParlaMint-SI_2004-05-07-SDZ3-Izredna-44,ParlaMint-SI_2004-05-07-SDZ3-Izredna-44.u103,Zapisi sej Državnega zbora Republike Slovenije...,2004-05-07,Spodnji dom,3. mandat,-,Izredna,-,-,...,notMinister,DeSUS,Demokratična stranka upokojencev Slovenije,Coalition,Sredinska do levo sredinska,PohorecValentin,"Pohorec, Valentin",M,1941,"Dr. Bajuk, mislim, da vem, kako se seja vodi, ..."
308073,ParlaMint-SI_2004-02-24-SDZ3-Redna-34,ParlaMint-SI_2004-02-24-SDZ3-Redna-34.u12,Zapisi sej Državnega zbora Republike Slovenije...,2004-02-24,Spodnji dom,3. mandat,-,Redna,-,-,...,notMinister,ZLSD,Združena lista socialnih demokratov,Coalition,Levo sredinska,PotrčMiran,"Potrč, Miran",M,1938,"Spoštovane ekscelence in visoki gostje, gospod..."
308382,ParlaMint-SI_2004-06-23-SDZ3-Izredna-47,ParlaMint-SI_2004-06-23-SDZ3-Izredna-47.u39,Zapisi sej Državnega zbora Republike Slovenije...,2004-06-23,Spodnji dom,3. mandat,-,Izredna,-,-,...,notMinister,DeSUS,Demokratična stranka upokojencev Slovenije,Coalition,Sredinska do levo sredinska,PohorecValentin,"Pohorec, Valentin",M,1941,Hvala. K besedi vabim kolegico Irmo Pavlinič K...
308691,ParlaMint-SI_2004-07-05-SDZ3-Izredna-48,ParlaMint-SI_2004-07-05-SDZ3-Izredna-48.u132,Zapisi sej Državnega zbora Republike Slovenije...,2004-07-05,Spodnji dom,3. mandat,-,Izredna,-,-,...,notMinister,SDS,Slovenska demokratska stranka,Opposition,Desna,JanšaJanez,"Janša, Ivan Janez",M,1958,"Torej, mislim, da se prvič dogaja, da predsedn..."
309000,ParlaMint-SI_2004-06-16-SDZ3-Redna-37,ParlaMint-SI_2004-06-16-SDZ3-Redna-37.u228,Zapisi sej Državnega zbora Republike Slovenije...,2004-06-16,Spodnji dom,3. mandat,-,Redna,-,-,...,notMinister,LDS,Liberalna demokracija Slovenije,Coalition,Sredinska do levo sredinska,PavliničKrebsIrma,"Pavlinič Krebs, Irma",F,1963,Hvala lepa. Prehajamo na glasovanje o predlogu...

## Check for any duplicates

Checking for any possible duplicates with the test datasets
Empty table = no duplicates :)

In [27]:
df_new = df_new.sample(frac=1, random_state=42).reset_index(drop=True)
df_new.to_csv("../Datasets/Sample_data.csv", index=False)
df_new

,Text_ID,ID,Title,Date,Body,Term,Session,Meeting,Sitting,Agenda,...,Speaker_minister,Speaker_party,Speaker_party_name,Party_status,Party_orientation,Speaker_ID,Speaker_name,Speaker_gender,Speaker_birth,Text
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,Zapisi sej Državnega zbora Republike Slovenije...,2010-09-07,Spodnji dom,5. mandat,-,Izredna,-,-,...,notMinister,SDS,Slovenska demokratska stranka,Opposition,Desna,CukjatiFrance,"Cukjati, France",M,1943,"Ni replike na repliko. Gospa ministrica, potem..."
1,ParlaMint-SI_2011-06-16-SDZ5-Redna-29,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,Zapisi sej Državnega zbora Republike Slovenije...,2011-06-16,Spodnji dom,5. mandat,-,Redna,-,-,...,notMinister,Zares,Zares - nova politika,Coalition,Levo sredinska,GantarPavel,"Gantar, Pavel",M,1949,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...
2,ParlaMint-SI_2011-06-21-SDZ5-Redna-29,ParlaMint-SI_2011-06-21-SDZ5-Redna-29.u178,Zapisi sej Državnega zbora Republike Slovenije...,2011-06-21,Spodnji dom,5. mandat,-,Redna,-,-,...,notMinister,-,-,-,-,ZalarAleš,"Zalar, Aleš",M,-,"Hvala lepa. V bistvu se strinjam z vami, gospo..."
3,ParlaMint-SI_2020-09-21-SDZ8-Redna-20,ParlaMint-SI_2020-09-21-SDZ8-Redna-20.u276,Zapisi sej Državnega zbora Republike Slovenije...,2020-09-21,Spodnji dom,8. mandat,-,Redna,-,-,...,Minister,-,-,-,-,GantarTomaž,"Gantar, Tomaž",M,1960,"Hvala, podpredsednik. Hvala tudi za vprašanje,..."
4,ParlaMint-SI_2009-11-18-SDZ5-Redna-11,ParlaMint-SI_2009-11-18-SDZ5-Redna-11.u120,Zapisi sej Državnega zbora Republike Slovenije...,2009-11-18,Spodnji dom,5. mandat,-,Redna,-,-,...,notMinister,DeSUS,Demokratična stranka upokojencev Slovenije,Coalition,Sredinska do levo sredinska,KlavoraVasja,"Klavora, Vasja",M,1936,Besedo ima gospod Silven Majhenič.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,ParlaMint-SI_2015-05-13-SDZ7-Izredna-13,ParlaMint-SI_2015-05-13-SDZ7-Izredna-13.u1,Zapisi sej Državnega zbora Republike Slovenije...,2015-05-13,Spodnji dom,7. mandat,-,Izredna,-,-,...,notMinister,SMC,Stranka modernega centra,Coalition,Sredinska do levo sredinska,BrglezMilan,"Brglez, Milan",M,1967,Spoštovani kolegice poslanke in kolegi poslanc...
996,ParlaMint-SI_2001-10-05-SDZ3-Redna-08,ParlaMint-SI_2001-10-05-SDZ3-Redna-08.u73,Zapisi sej Državnega zbora Republike Slovenije...,2001-10-05,Spodnji dom,3. mandat,-,Redna,-,-,...,notMinister,LDS,Liberalna demokracija Slovenije,Coalition,Sredinska do levo sredinska,MajnikLidija,"Majnik, Lidija",F,1953,"O amandmaju k 26. členu nismo glasovali, ker s..."
997,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.u95,Zapisi sej Državnega zbora Republike Slovenije...,2005-02-01,Spodnji dom,4. mandat,-,Izredna,-,-,...,notMinister,SDS,Slovenska demokratska stranka,Coalition,Desna,CukjatiFrance,"Cukjati, France",M,1943,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm..."
998,ParlaMint-SI_2009-03-27-SDZ5-Redna-04,ParlaMint-SI_2009-03-27-SDZ5-Redna-04.u199,Zapisi sej Državnega zbora Republike Slovenije...,2009-03-27,Spodnji dom,5. mandat,-,Redna,-,-,...,notMinister,Zares,Zares - nova politika,Coalition,Levo sredinska,GantarPavel,"Gantar, Pavel",M,1949,Hvala lepa. Besedo ima mag. Branko Grims. Prosim.
999,ParlaMint-SI_2022-03-21-SDZ8-Redna-30,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.u17,Zapisi sej Državnega zbora Republike Slovenije...,2022-03-21,Spodnji dom,8. mandat,-,Redna,-,-,...,notMinister,LMŠ,Lista Marjana Šarca,Opposition,Sredinska do levo sredinska,HeferleTina,"Heferle, Tina",F,1986,Hvala lepa. Zadnji bo stališče Poslanske skupi...

In [28]:
df_new['Chair'] = df_new['Speaker_role'] == 'Predsedujoči'
df_new

,Text_ID,ID,Title,Date,Body,Term,Session,Meeting,Sitting,Agenda,...,Speaker_party,Speaker_party_name,Party_status,Party_orientation,Speaker_ID,Speaker_name,Speaker_gender,Speaker_birth,Text,Chair
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,Zapisi sej Državnega zbora Republike Slovenije...,2010-09-07,Spodnji dom,5. mandat,-,Izredna,-,-,...,SDS,Slovenska demokratska stranka,Opposition,Desna,CukjatiFrance,"Cukjati, France",M,1943,"Ni replike na repliko. Gospa ministrica, potem...",True
1,ParlaMint-SI_2011-06-16-SDZ5-Redna-29,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,Zapisi sej Državnega zbora Republike Slovenije...,2011-06-16,Spodnji dom,5. mandat,-,Redna,-,-,...,Zares,Zares - nova politika,Coalition,Levo sredinska,GantarPavel,"Gantar, Pavel",M,1949,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,True
2,ParlaMint-SI_2011-06-21-SDZ5-Redna-29,ParlaMint-SI_2011-06-21-SDZ5-Redna-29.u178,Zapisi sej Državnega zbora Republike Slovenije...,2011-06-21,Spodnji dom,5. mandat,-,Redna,-,-,...,-,-,-,-,ZalarAleš,"Zalar, Aleš",M,-,"Hvala lepa. V bistvu se strinjam z vami, gospo...",False
3,ParlaMint-SI_2020-09-21-SDZ8-Redna-20,ParlaMint-SI_2020-09-21-SDZ8-Redna-20.u276,Zapisi sej Državnega zbora Republike Slovenije...,2020-09-21,Spodnji dom,8. mandat,-,Redna,-,-,...,-,-,-,-,GantarTomaž,"Gantar, Tomaž",M,1960,"Hvala, podpredsednik. Hvala tudi za vprašanje,...",False
4,ParlaMint-SI_2009-11-18-SDZ5-Redna-11,ParlaMint-SI_2009-11-18-SDZ5-Redna-11.u120,Zapisi sej Državnega zbora Republike Slovenije...,2009-11-18,Spodnji dom,5. mandat,-,Redna,-,-,...,DeSUS,Demokratična stranka upokojencev Slovenije,Coalition,Sredinska do levo sredinska,KlavoraVasja,"Klavora, Vasja",M,1936,Besedo ima gospod Silven Majhenič.,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,ParlaMint-SI_2015-05-13-SDZ7-Izredna-13,ParlaMint-SI_2015-05-13-SDZ7-Izredna-13.u1,Zapisi sej Državnega zbora Republike Slovenije...,2015-05-13,Spodnji dom,7. mandat,-,Izredna,-,-,...,SMC,Stranka modernega centra,Coalition,Sredinska do levo sredinska,BrglezMilan,"Brglez, Milan",M,1967,Spoštovani kolegice poslanke in kolegi poslanc...,True
996,ParlaMint-SI_2001-10-05-SDZ3-Redna-08,ParlaMint-SI_2001-10-05-SDZ3-Redna-08.u73,Zapisi sej Državnega zbora Republike Slovenije...,2001-10-05,Spodnji dom,3. mandat,-,Redna,-,-,...,LDS,Liberalna demokracija Slovenije,Coalition,Sredinska do levo sredinska,MajnikLidija,"Majnik, Lidija",F,1953,"O amandmaju k 26. členu nismo glasovali, ker s...",False
997,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.u95,Zapisi sej Državnega zbora Republike Slovenije...,2005-02-01,Spodnji dom,4. mandat,-,Izredna,-,-,...,SDS,Slovenska demokratska stranka,Coalition,Desna,CukjatiFrance,"Cukjati, France",M,1943,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",True
998,ParlaMint-SI_2009-03-27-SDZ5-Redna-04,ParlaMint-SI_2009-03-27-SDZ5-Redna-04.u199,Zapisi sej Državnega zbora Republike Slovenije...,2009-03-27,Spodnji dom,5. mandat,-,Redna,-,-,...,Zares,Zares - nova politika,Coalition,Levo sredinska,GantarPavel,"Gantar, Pavel",M,1949,Hvala lepa. Besedo ima mag. Branko Grims. Prosim.,True
999,ParlaMint-SI_2022-03-21-SDZ8-Redna-30,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.u17,Zapisi sej Državnega zbora Republike Slovenije...,2022-03-21,Spodnji dom,8. mandat,-,Redna,-,-,...,LMŠ,Lista Marjana Šarca,Opposition,Sredinska do levo sredinska,HeferleTina,"Heferle, Tina",F,1986,Hvala lepa. Zadnji bo stališče Poslanske skupi...,True

In [29]:
df_new = df_new.reindex(columns = headers)
df_new.to_csv("../Datasets/Sample.csv", index=False)
df_new

,ID,Text,Annotation,Comments,Flag,Chair
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,"Ni replike na repliko. Gospa ministrica, potem...",NaN,NaN,NaN,True
1,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,NaN,NaN,NaN,True
2,ParlaMint-SI_2011-06-21-SDZ5-Redna-29.u178,"Hvala lepa. V bistvu se strinjam z vami, gospo...",NaN,NaN,NaN,False
3,ParlaMint-SI_2020-09-21-SDZ8-Redna-20.u276,"Hvala, podpredsednik. Hvala tudi za vprašanje,...",NaN,NaN,NaN,False
4,ParlaMint-SI_2009-11-18-SDZ5-Redna-11.u120,Besedo ima gospod Silven Majhenič.,NaN,NaN,NaN,True
...,...,...,...,...,...,...
995,ParlaMint-SI_2015-05-13-SDZ7-Izredna-13.u1,Spoštovani kolegice poslanke in kolegi poslanc...,NaN,NaN,NaN,True
996,ParlaMint-SI_2001-10-05-SDZ3-Redna-08.u73,"O amandmaju k 26. členu nismo glasovali, ker s...",NaN,NaN,NaN,False
997,ParlaMint-SI_2005-02-01-SDZ4-Izredna-06.u95,"Hvala, gospodu Kovačiču. Da se ne bi še kdo zm...",NaN,NaN,NaN,True
998,ParlaMint-SI_2009-03-27-SDZ5-Redna-04.u199,Hvala lepa. Besedo ima mag. Branko Grims. Prosim.,NaN,NaN,NaN,True
999,ParlaMint-SI_2022-03-21-SDZ8-Redna-30.u17,Hvala lepa. Zadnji bo stališče Poslanske skupi...,NaN,NaN,NaN,True

In [30]:
df_check_rows = df_new[df_new.apply(tuple, axis=1).isin(df_to_remove.apply(tuple, axis=1))]
df_check_rows
#Clean, no duplicates

Empty DataFrame
Columns: [ID, Text, Annotation, Comments, Flag, Chair]
Index: []