In [1]:
import csv
import pandas as pd

# Dataset merge and prep for analysis

Checking and renaming the datasets to merge them into one combined dataset and get it ready for (IAA) analysis.

Change folder (Test1, Test2, Main1, Main2...) to process other datasets as they come.

In [2]:
df1 = pd.read_excel("Test3/Test3_Tamara.xlsx")
df2 = pd.read_excel("Test3/Test3_Katja.xlsx")

In [3]:
df1 = df1.drop(columns='Annotation_values')
df2 = df2.drop(columns='Annotation_values')

In [4]:
df1.rename(columns={'Text':'text', 'Annotation': 'tag_tamara', 'Comments': 'comments_tamara','Flag':'flagged_tamara'}, inplace=True)

In [5]:
df2.rename(columns={'Text':'text', 'Annotation': 'tag_katja', 'Comments': 'comments_katja','Flag':'flagged_katja', 'Chair':'chair'}, inplace=True)

In [6]:
merged_df = pd.merge(df1, df2, on=['ID', 'text'])
merged_df

,ID,text,tag_tamara,comments_tamara,flagged_tamara,Chair,tag_katja,comments_katja,flagged_katja,chair
0,ParlaMint-SI_2004-01-27-SDZ3-Redna-33.u194,"Magister Drobnič, ste želeli besedo? Prosim.",P_Neutral,Procedural.,NaN,True,P_Neutral,Procedural,NaN,True
1,ParlaMint-SI_2015-07-14-SDZ7-Redna-10.u428,"Gospa Anja Bah Žibert, imate besedo, da zahtev...",P_Neutral,Procedural.,NaN,True,P_Neutral,Procedural,NaN,True
2,ParlaMint-SI_2008-03-05-SDZ4-Izredna-34.u28,Hvala lepa. No sedaj smo pravzaprav lahko vide...,Negative,"Clear sentiment, negative opinion, reproachful...",NaN,False,Negative,"Very negative, attack on the minister and crit...",NaN,False
3,ParlaMint-SI_2006-05-24-SDZ4-Redna-17.u82,Hvala lepa. Samo na kratko. Vlada podpira aman...,Positive,Since the word ''podpira'' is used I would say...,1.0,False,P_Neutral,"Very neutral, procedural - support to amend th...",NaN,False
4,ParlaMint-SI_2002-09-24-SDZ3-Redna-18.u52,"Spoštovana predsedujoča! Gospa ministrica, kol...",M_Negative,A very mixed sentiment sentence. On the one ha...,1.0,False,M_Negative,Speaker takes a position of having the topic o...,1.0,False
5,ParlaMint-SI_2004-04-08-SDZ3-Izredna-42.u68,Kolegu Bevku: Pulitzerjeve pa Nobelove nagrade...,Negative,Ojoj. Clearly a very very strong negative sent...,NaN,False,Negative,Very clear negative sentiment,NaN,False
6,ParlaMint-SI_2013-09-27-SDZ6-Redna-17.u84,"Hvala lepa še enkrat za besedo, predsedujoča. ...",Negative,"This could very well be N_Negative, but strict...",1.0,False,Negative,The speaker explains the dilemas that are pres...,NaN,False
7,ParlaMint-SI_2001-02-01-SDZ3-Redna-02.u10,"Kdo bo ugotavljal, kako je ""krajevno primeren ...",Negative,"Clear negative, non supportive.",NaN,False,Negative,Very evident negative sentiment.,NaN,False
8,ParlaMint-SI_2009-09-25-SDZ5-Redna-09.u44,Hvala za besedo. Lepo pozdravljeni vsi zbrani!...,M_Positive,This one will probably need to be discussed to...,1.0,False,Negative,"Could be either fully negative, but as the fir...",1.0,False
9,ParlaMint-SI_2008-03-05-SDZ4-Izredna-34.u228,Hvala gospod podpredsednik za dano možnost. Bo...,Positive,Speaks in the name of the party and expresses ...,NaN,False,Positive,"Seemed like mocking at first glance, but toget...",NaN,False
10,ParlaMint-SI_2013-11-11-SDZ6-Izredna-47.u45,Hvala lepa. Naslednji je prijavljen k razpravi...,P_Neutral,Procedura.,NaN,True,P_Neutral,NaN,NaN,True
11,ParlaMint-SI_2005-04-22-SDZ4-Izredna-08.u54,Hvala lepa. Lepo pozdravljeni spoštovane posla...,P_Neutral,Procedural.,NaN,True,P_Neutral,NaN,NaN,True
12,ParlaMint-SI_2010-04-19-SDZ5-Redna-16.u315,Hvala. Želite še besedo gospa ministrica? Ne. ...,P_Neutral,Procedural.,NaN,True,P_Neutral,NaN,NaN,True
13,ParlaMint-SI_2004-12-16-SDZ4-Izredna-05.u159,"Spoštovani predsedujoči, spoštovani vsi prisot...",Positive,Clear support and strongly colored positive wo...,NaN,False,Positive,NaN,NaN,False
14,ParlaMint-SI_2009-06-16-SDZ5-Redna-07.u389,Hvala lepa. Ta razprava je nujna predvsem zard...,Negative,"Very negative opinion, clear disagreement.",NaN,False,Negative,NaN,NaN,False
15,ParlaMint-SI_2004-03-24-SDZ3-Redna-35.u165,"Hvala. Še enkrat sem se oglasil, čeprav sem mi...",Negative,"Very negative opinion, clear disagreement.",NaN,False,Negative,NaN,NaN,False
16,ParlaMint-SI_2001-10-24-SDZ3-Redna-09.u210,"Hvala za besedo, gospod podpredsednik. Lepo va...",Positive,"Positive words of affirmation, agreement.",NaN,False,P_Neutral,"Speech full of statments, describing the curre...",NaN,False
17,ParlaMint-SI_2008-07-11-SDZ4-Redna-41.u10,"Hvala lepa za besedo, gospod predsednik. Spošt...",Positive,Support.,NaN,False,Positive,Speaker detailing positive effects shown from ...,NaN,False
18,ParlaMint-SI_2004-09-01-SDZ3-Izredna-50.u158,Hvala lepa. Stališče poslanske skupine Demokra...,P_Neutral,Procedural.,NaN,True,P_Neutral,NaN,NaN,True
19,ParlaMint-SI_2021-12-17-SDZ8-Redna-28.u38,"Glejte, spoštovani minister, še enkrat. Prvič,...",Negative,"Clearly negative, very reproachful.",NaN,False,Negative,"Very very negative, also, interpelacija.",NaN,False
20,ParlaMint-SI_2021-09-20-SDZ8-Redna-25.u194,"Podpredsednica, hvala lepa. Spoštovani ministe...",Positive,Because of the very positive first part I'm go...,NaN,False,M_Negative,"First part very positive, but then does downhi...",NaN,False
21,ParlaMint-SI_2004-04-09-SDZ3-Izredna-42.u144,Hvala lepa. Sledi predstavitev stališč poslans...,P_Neutral,Procedural.,NaN,True,P_Neutral,NaN,NaN,True
22,ParlaMint-SI_2021-03-02-SDZ8-Izredna-63.u167,"Bom jaz vodil sejo, kolega Möderndorfer.",N_Neutral,"Procedural, but I do not think it was meant po...",NaN,True,N_Neutral,"Procedural, but seems to be abit of negative c...",NaN,True
23,ParlaMint-SI_2009-11-23-SDZ5-Redna-11.u87,Hvala lepa. Gospa Kamnarjeva je prosila za bes...,P_Neutral,Procedural.,NaN,True,P_Neutral,NaN,NaN,True
24,ParlaMint-SI_2022-03-14-SDZ8-Redna-30.u260,"Hvala lepa. Gospa poslanka, imate besedo za po...",P_Neutral,Procedural.,NaN,True,P_Neutral,NaN,NaN,True
25,ParlaMint-SI_2001-02-20-SDZ3-Redna-03.u56,"Hvala lepa. Razumel sem, da vprašanja niste na...",P_Neutral,Procedural.,NaN,True,P_Neutral,NaN,NaN,True
26,ParlaMint-SI_2015-04-24-SDZ7-Redna-07.u21,Prosim! [[oglašanje iz dvorane]] Prvi del pred...,M_Negative,A very complex sentence. I think this one is u...,1.0,True,Negative,"Overall very negative, but the first sentence ...",1.0,True
27,ParlaMint-SI_2012-01-19-SDZ6-Izredna-03.u4,"Spoštovani predsednik, kolegice, kolegi! Držav...",Positive,Support.,NaN,False,Positive,Is it fully positive??? Could also be P_Neutra...,1.0,False
28,ParlaMint-SI_2012-12-19-SDZ6-Redna-09.u43,"Hvala lepa. Vidim, da je še želja po razpravi,...",P_Neutral,Procedural.,NaN,True,P_Neutral,NaN,NaN,True
29,ParlaMint-SI_2007-11-19-SDZ4-Redna-33.u11,"Hvala. Gospod Lahovnik, ste želeli proceduraln...",P_Neutral,Procedural.,NaN,True,P_Neutral,NaN,NaN,True
30,ParlaMint-SI_2017-02-09-SDZ7-Izredna-42.u97,Hvala lepa. Besedo ima predstavnik predlagatel...,P_Neutral,Procedural.,NaN,True,P_Neutral,NaN,NaN,True
31,ParlaMint-SI_2014-06-12-SDZ6-Izredna-69.u10,"Hvala za besedo, gospod predsednik. Spoštovani...",M_Negative,Very confusing. On one hand the speaker is pos...,1.0,False,M_Negative,The sentiment seems to fluctuate in several pl...,NaN,False
32,ParlaMint-SI_2021-07-14-SDZ8-Redna-24.u171,Hvala lepa. Naslednji je na vrsti gospod Miha ...,P_Neutral,Procedural.,NaN,True,P_Neutral,NaN,NaN,True
33,ParlaMint-SI_2008-03-28-SDZ4-Redna-37.u228,"Spoštovane poslanke, spoštovani poslanci, pros...",P_Neutral,Although a bit of tension this is still just p...,NaN,True,P_Neutral,NaN,NaN,True
34,ParlaMint-SI_2007-01-31-SDZ4-Redna-24.u39,Hvala. Besedo ima gospod Bevk.,P_Neutral,Procedural.,NaN,True,P_Neutral,NaN,NaN,True
35,ParlaMint-SI_2006-03-06-SDZ4-Redna-14.u122,"Hvala lepa za besedo, spoštovani predsednik! K...",M_Positive,"Lots of negative wording, but also expresses s...",NaN,False,M_Positive,First part negative (describing the wrong deci...,NaN,False
36,ParlaMint-SI_2004-11-17-SDZ4-Izredna-02.u238,"Hvala predstavniku vlade, gospodu Cviklu. Ker ...",P_Neutral,Procedural.,NaN,True,P_Neutral,NaN,NaN,True
37,ParlaMint-SI_2019-09-25-SDZ8-Redna-11.u46,"Spoštovani predsednik, spoštovane poslanke, sp...",Positive,"Inherently positve, if we take this as facts i...",NaN,False,P_Neutral,The speaker describes the changes in the legis...,NaN,False
38,ParlaMint-SI_2003-03-24-SDZ3-Redna-24.u154,"Gospa, jaz imam dodatno vprašanje.",P_Neutral,Procedural.,NaN,False,P_Neutral,NaN,NaN,False
39,ParlaMint-SI_2010-07-16-SDZ5-Izredna-27.u27,Hvala lepa. Besedo ima gospa Melita Župevc. Pr...,P_Neutral,Procedural.,NaN,True,P_Neutral,NaN,NaN,True
40,ParlaMint-SI_2013-10-29-SDZ6-Redna-18.u166,"Hvala, gospa podpredsednica, za besedo. Kljub ...",Negative,"Negative opinion, disagreement.",NaN,False,Negative,NaN,NaN,False
41,ParlaMint-SI_2014-05-14-SDZ6-Izredna-64.u100,"[[…]]kar seveda govori o tem, da ta trend ni v...",Negative,"Disagreement, negative opinion, reproachful.",NaN,False,Negative,NaN,NaN,False
42,ParlaMint-SI_2010-05-18-SDZ5-Redna-17.u117,Hvala lepa. Stališče Poslanske skupine Zares b...,P_Neutral,Procedural.,NaN,True,P_Neutral,NaN,NaN,True
43,ParlaMint-SI_2019-05-13-SDZ8-Izredna-22.u118,Hvala lepa. Čisto kratka bom. Kolegica Anja Ba...,Negative,"Although rather mild, the sentiment is persona...",NaN,False,Negative,NaN,NaN,False
44,ParlaMint-SI_2009-07-16-SDZ5-Izredna-11.u33,Hvala lepa. V imenu predlagatelja želi najprej...,P_Neutral,Procedural.,NaN,True,P_Neutral,NaN,NaN,True
45,ParlaMint-SI_2010-11-17-SDZ5-Redna-22.u84,"Hvala lepa. Obrazložitev glasu, Julijana Bizja...",P_Neutral,Procedural.,NaN,True,P_Neutral,NaN,NaN,True
46,ParlaMint-SI_2012-03-22-SDZ6-Izredna-09.u31,Hvala. Končali smo predstavitev stališč poslan...,P_Neutral,Procedural.,NaN,True,P_Neutral,NaN,NaN,True
47,ParlaMint-SI_2016-01-26-SDZ7-Redna-15.u85,Hvala lepa. Besedo ima gospod Bojan Podkrajšek.,P_Neutral,Procedural.,NaN,True,P_Neutral,NaN,NaN,True
48,ParlaMint-SI_2008-04-01-SDZ4-Redna-37.u92,"Hvala za besedo, spoštovani gospod predsedujoč...",Negative,"Negative, opinionated, reprocheful, bad-spirit...",NaN,False,Negative,NaN,NaN,False
49,ParlaMint-SI_2019-12-16-SDZ8-Redna-14.u156,"Hvala za dodatne odgovore in pojasnila, minist...",Negative,Very hard to determine as I do not know the wa...,1.0,False,M_Negative,The speech fluctuates between sentiment on sev...,1.0,False

In [7]:
order = ['ID', 'text', 'tag_tamara', 'tag_katja', 'comments_tamara', 'comments_katja', 'flagged_tamara', 'flagged_katja', 'chair']

In [8]:
merged_df = merged_df[order]
merged_df['final_tag'] = ''
merged_df

,ID,text,tag_tamara,tag_katja,comments_tamara,comments_katja,flagged_tamara,flagged_katja,chair,final_tag
0,ParlaMint-SI_2004-01-27-SDZ3-Redna-33.u194,"Magister Drobnič, ste želeli besedo? Prosim.",P_Neutral,P_Neutral,Procedural.,Procedural,NaN,NaN,True,
1,ParlaMint-SI_2015-07-14-SDZ7-Redna-10.u428,"Gospa Anja Bah Žibert, imate besedo, da zahtev...",P_Neutral,P_Neutral,Procedural.,Procedural,NaN,NaN,True,
2,ParlaMint-SI_2008-03-05-SDZ4-Izredna-34.u28,Hvala lepa. No sedaj smo pravzaprav lahko vide...,Negative,Negative,"Clear sentiment, negative opinion, reproachful...","Very negative, attack on the minister and crit...",NaN,NaN,False,
3,ParlaMint-SI_2006-05-24-SDZ4-Redna-17.u82,Hvala lepa. Samo na kratko. Vlada podpira aman...,Positive,P_Neutral,Since the word ''podpira'' is used I would say...,"Very neutral, procedural - support to amend th...",1.0,NaN,False,
4,ParlaMint-SI_2002-09-24-SDZ3-Redna-18.u52,"Spoštovana predsedujoča! Gospa ministrica, kol...",M_Negative,M_Negative,A very mixed sentiment sentence. On the one ha...,Speaker takes a position of having the topic o...,1.0,1.0,False,
5,ParlaMint-SI_2004-04-08-SDZ3-Izredna-42.u68,Kolegu Bevku: Pulitzerjeve pa Nobelove nagrade...,Negative,Negative,Ojoj. Clearly a very very strong negative sent...,Very clear negative sentiment,NaN,NaN,False,
6,ParlaMint-SI_2013-09-27-SDZ6-Redna-17.u84,"Hvala lepa še enkrat za besedo, predsedujoča. ...",Negative,Negative,"This could very well be N_Negative, but strict...",The speaker explains the dilemas that are pres...,1.0,NaN,False,
7,ParlaMint-SI_2001-02-01-SDZ3-Redna-02.u10,"Kdo bo ugotavljal, kako je ""krajevno primeren ...",Negative,Negative,"Clear negative, non supportive.",Very evident negative sentiment.,NaN,NaN,False,
8,ParlaMint-SI_2009-09-25-SDZ5-Redna-09.u44,Hvala za besedo. Lepo pozdravljeni vsi zbrani!...,M_Positive,Negative,This one will probably need to be discussed to...,"Could be either fully negative, but as the fir...",1.0,1.0,False,
9,ParlaMint-SI_2008-03-05-SDZ4-Izredna-34.u228,Hvala gospod podpredsednik za dano možnost. Bo...,Positive,Positive,Speaks in the name of the party and expresses ...,"Seemed like mocking at first glance, but toget...",NaN,NaN,False,
10,ParlaMint-SI_2013-11-11-SDZ6-Izredna-47.u45,Hvala lepa. Naslednji je prijavljen k razpravi...,P_Neutral,P_Neutral,Procedura.,NaN,NaN,NaN,True,
11,ParlaMint-SI_2005-04-22-SDZ4-Izredna-08.u54,Hvala lepa. Lepo pozdravljeni spoštovane posla...,P_Neutral,P_Neutral,Procedural.,NaN,NaN,NaN,True,
12,ParlaMint-SI_2010-04-19-SDZ5-Redna-16.u315,Hvala. Želite še besedo gospa ministrica? Ne. ...,P_Neutral,P_Neutral,Procedural.,NaN,NaN,NaN,True,
13,ParlaMint-SI_2004-12-16-SDZ4-Izredna-05.u159,"Spoštovani predsedujoči, spoštovani vsi prisot...",Positive,Positive,Clear support and strongly colored positive wo...,NaN,NaN,NaN,False,
14,ParlaMint-SI_2009-06-16-SDZ5-Redna-07.u389,Hvala lepa. Ta razprava je nujna predvsem zard...,Negative,Negative,"Very negative opinion, clear disagreement.",NaN,NaN,NaN,False,
15,ParlaMint-SI_2004-03-24-SDZ3-Redna-35.u165,"Hvala. Še enkrat sem se oglasil, čeprav sem mi...",Negative,Negative,"Very negative opinion, clear disagreement.",NaN,NaN,NaN,False,
16,ParlaMint-SI_2001-10-24-SDZ3-Redna-09.u210,"Hvala za besedo, gospod podpredsednik. Lepo va...",Positive,P_Neutral,"Positive words of affirmation, agreement.","Speech full of statments, describing the curre...",NaN,NaN,False,
17,ParlaMint-SI_2008-07-11-SDZ4-Redna-41.u10,"Hvala lepa za besedo, gospod predsednik. Spošt...",Positive,Positive,Support.,Speaker detailing positive effects shown from ...,NaN,NaN,False,
18,ParlaMint-SI_2004-09-01-SDZ3-Izredna-50.u158,Hvala lepa. Stališče poslanske skupine Demokra...,P_Neutral,P_Neutral,Procedural.,NaN,NaN,NaN,True,
19,ParlaMint-SI_2021-12-17-SDZ8-Redna-28.u38,"Glejte, spoštovani minister, še enkrat. Prvič,...",Negative,Negative,"Clearly negative, very reproachful.","Very very negative, also, interpelacija.",NaN,NaN,False,
20,ParlaMint-SI_2021-09-20-SDZ8-Redna-25.u194,"Podpredsednica, hvala lepa. Spoštovani ministe...",Positive,M_Negative,Because of the very positive first part I'm go...,"First part very positive, but then does downhi...",NaN,NaN,False,
21,ParlaMint-SI_2004-04-09-SDZ3-Izredna-42.u144,Hvala lepa. Sledi predstavitev stališč poslans...,P_Neutral,P_Neutral,Procedural.,NaN,NaN,NaN,True,
22,ParlaMint-SI_2021-03-02-SDZ8-Izredna-63.u167,"Bom jaz vodil sejo, kolega Möderndorfer.",N_Neutral,N_Neutral,"Procedural, but I do not think it was meant po...","Procedural, but seems to be abit of negative c...",NaN,NaN,True,
23,ParlaMint-SI_2009-11-23-SDZ5-Redna-11.u87,Hvala lepa. Gospa Kamnarjeva je prosila za bes...,P_Neutral,P_Neutral,Procedural.,NaN,NaN,NaN,True,
24,ParlaMint-SI_2022-03-14-SDZ8-Redna-30.u260,"Hvala lepa. Gospa poslanka, imate besedo za po...",P_Neutral,P_Neutral,Procedural.,NaN,NaN,NaN,True,
25,ParlaMint-SI_2001-02-20-SDZ3-Redna-03.u56,"Hvala lepa. Razumel sem, da vprašanja niste na...",P_Neutral,P_Neutral,Procedural.,NaN,NaN,NaN,True,
26,ParlaMint-SI_2015-04-24-SDZ7-Redna-07.u21,Prosim! [[oglašanje iz dvorane]] Prvi del pred...,M_Negative,Negative,A very complex sentence. I think this one is u...,"Overall very negative, but the first sentence ...",1.0,1.0,True,
27,ParlaMint-SI_2012-01-19-SDZ6-Izredna-03.u4,"Spoštovani predsednik, kolegice, kolegi! Držav...",Positive,Positive,Support.,Is it fully positive??? Could also be P_Neutra...,NaN,1.0,False,
28,ParlaMint-SI_2012-12-19-SDZ6-Redna-09.u43,"Hvala lepa. Vidim, da je še želja po razpravi,...",P_Neutral,P_Neutral,Procedural.,NaN,NaN,NaN,True,
29,ParlaMint-SI_2007-11-19-SDZ4-Redna-33.u11,"Hvala. Gospod Lahovnik, ste želeli proceduraln...",P_Neutral,P_Neutral,Procedural.,NaN,NaN,NaN,True,
30,ParlaMint-SI_2017-02-09-SDZ7-Izredna-42.u97,Hvala lepa. Besedo ima predstavnik predlagatel...,P_Neutral,P_Neutral,Procedural.,NaN,NaN,NaN,True,
31,ParlaMint-SI_2014-06-12-SDZ6-Izredna-69.u10,"Hvala za besedo, gospod predsednik. Spoštovani...",M_Negative,M_Negative,Very confusing. On one hand the speaker is pos...,The sentiment seems to fluctuate in several pl...,1.0,NaN,False,
32,ParlaMint-SI_2021-07-14-SDZ8-Redna-24.u171,Hvala lepa. Naslednji je na vrsti gospod Miha ...,P_Neutral,P_Neutral,Procedural.,NaN,NaN,NaN,True,
33,ParlaMint-SI_2008-03-28-SDZ4-Redna-37.u228,"Spoštovane poslanke, spoštovani poslanci, pros...",P_Neutral,P_Neutral,Although a bit of tension this is still just p...,NaN,NaN,NaN,True,
34,ParlaMint-SI_2007-01-31-SDZ4-Redna-24.u39,Hvala. Besedo ima gospod Bevk.,P_Neutral,P_Neutral,Procedural.,NaN,NaN,NaN,True,
35,ParlaMint-SI_2006-03-06-SDZ4-Redna-14.u122,"Hvala lepa za besedo, spoštovani predsednik! K...",M_Positive,M_Positive,"Lots of negative wording, but also expresses s...",First part negative (describing the wrong deci...,NaN,NaN,False,
36,ParlaMint-SI_2004-11-17-SDZ4-Izredna-02.u238,"Hvala predstavniku vlade, gospodu Cviklu. Ker ...",P_Neutral,P_Neutral,Procedural.,NaN,NaN,NaN,True,
37,ParlaMint-SI_2019-09-25-SDZ8-Redna-11.u46,"Spoštovani predsednik, spoštovane poslanke, sp...",Positive,P_Neutral,"Inherently positve, if we take this as facts i...",The speaker describes the changes in the legis...,NaN,NaN,False,
38,ParlaMint-SI_2003-03-24-SDZ3-Redna-24.u154,"Gospa, jaz imam dodatno vprašanje.",P_Neutral,P_Neutral,Procedural.,NaN,NaN,NaN,False,
39,ParlaMint-SI_2010-07-16-SDZ5-Izredna-27.u27,Hvala lepa. Besedo ima gospa Melita Župevc. Pr...,P_Neutral,P_Neutral,Procedural.,NaN,NaN,NaN,True,
40,ParlaMint-SI_2013-10-29-SDZ6-Redna-18.u166,"Hvala, gospa podpredsednica, za besedo. Kljub ...",Negative,Negative,"Negative opinion, disagreement.",NaN,NaN,NaN,False,
41,ParlaMint-SI_2014-05-14-SDZ6-Izredna-64.u100,"[[…]]kar seveda govori o tem, da ta trend ni v...",Negative,Negative,"Disagreement, negative opinion, reproachful.",NaN,NaN,NaN,False,
42,ParlaMint-SI_2010-05-18-SDZ5-Redna-17.u117,Hvala lepa. Stališče Poslanske skupine Zares b...,P_Neutral,P_Neutral,Procedural.,NaN,NaN,NaN,True,
43,ParlaMint-SI_2019-05-13-SDZ8-Izredna-22.u118,Hvala lepa. Čisto kratka bom. Kolegica Anja Ba...,Negative,Negative,"Although rather mild, the sentiment is persona...",NaN,NaN,NaN,False,
44,ParlaMint-SI_2009-07-16-SDZ5-Izredna-11.u33,Hvala lepa. V imenu predlagatelja želi najprej...,P_Neutral,P_Neutral,Procedural.,NaN,NaN,NaN,True,
45,ParlaMint-SI_2010-11-17-SDZ5-Redna-22.u84,"Hvala lepa. Obrazložitev glasu, Julijana Bizja...",P_Neutral,P_Neutral,Procedural.,NaN,NaN,NaN,True,
46,ParlaMint-SI_2012-03-22-SDZ6-Izredna-09.u31,Hvala. Končali smo predstavitev stališč poslan...,P_Neutral,P_Neutral,Procedural.,NaN,NaN,NaN,True,
47,ParlaMint-SI_2016-01-26-SDZ7-Redna-15.u85,Hvala lepa. Besedo ima gospod Bojan Podkrajšek.,P_Neutral,P_Neutral,Procedural.,NaN,NaN,NaN,True,
48,ParlaMint-SI_2008-04-01-SDZ4-Redna-37.u92,"Hvala za besedo, spoštovani gospod predsedujoč...",Negative,Negative,"Negative, opinionated, reprocheful, bad-spirit...",NaN,NaN,NaN,False,
49,ParlaMint-SI_2019-12-16-SDZ8-Redna-14.u156,"Hvala za dodatne odgovore in pojasnila, minist...",Negative,M_Negative,Very hard to determine as I do not know the wa...,The speech fluctuates between sentiment on sev...,1.0,1.0,False,

In [10]:
merged_df.to_csv("Test3/Test3_combined.csv", encoding ='utf-8', index=False)