In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import plotly.express as px

In [2]:
df = pd.read_csv('../../Datasets/Sentiment_Analysis/CHES-SI.tsv', delimiter='\t', encoding='utf-8')
df

,country,pm_id,ches_id,year,chesversion,lrgen,lrecon,lrecon_blur,lrecon_dissent,lrecon_salience,...,seat,social_salience,sociallifestyle,spendvtax,spendvtax_salience,urban_rural,urban_salience,us,us_salience,vote
0,SI,DL,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
1,SI,DLGV,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
2,SI,DeSUS,DeSUS,2002,2020.1,3.4,3.4,-,-,-,...,4.40,-,-,-,-,-,-,-,-,5.2
3,SI,DeSUS,DeSUS,2006,2020.1,3.2,2.6,-,-,-,...,4.40,4.60,4.40,2.80,5.60,5.20,3.60,3.8,3.8,4
4,SI,DeSUS,DeSUS,2010,2020.1,4.25,3.33,-,-,-,...,7.80,3.25,5.17,2.40,7.20,4.91,3.73,-,-,7.5
5,SI,DeSUS,DeSUS,2014,2020.1,4.15,4.0,-,-,5.54,...,11.1,-,5.10,3.36,-,5.22,-,-,-,10.2
6,SI,DeSUS,DeSUS,2019,2020.1,3.77,3.29,4.71,2.57,4.67,...,5.70,-,4.29,2.53,-,4.93,-,-,-,4.93
7,SI,GAS,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
8,SI,Konkretno,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
9,SI,LDS,LDS,2002,2020.1,4.2,6.2,-,-,-,...,37.80,-,-,-,-,-,-,-,-,36.3
10,SI,LDS,LDS,2006,2020.1,3.4,3.8,-,-,-,...,25.6,7.60,2,4.20,6.20,2.80,3.80,4.60,4.20,22.8
11,SI,LDS,LDS,2010,2020.1,4.75,5.83,-,-,-,...,5.60,7.17,1,5.90,5.20,2.17,3.91,-,-,5.21
12,SI,LMŠ,LMS,2019,2020.1,4.36,4.64,5.43,3.67,6.13,...,14.8,-,3.64,4.20,-,4.87,-,-,-,12.6
13,SI,Levica,ZL,2014,2020.1,1.0,0.67,-,-,6.62,...,6.70,-,1.17,1.90,-,2.89,-,-,-,6
14,SI,Levica,Levica,2019,2020.1,0.71,0.71,1.57,1.71,5.93,...,10.2,-,.5,1.53,-,1.93,-,-,-,9.33
15,SI,Lipa,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
16,SI,NP,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
17,SI,NSi,NSI,2002,2020.1,7.0,4.8,-,-,-,...,8.90,-,-,-,-,-,-,-,-,8.6
18,SI,NSi,NSI,2006,2020.1,8.4,6.8,-,-,-,...,10,5.60,8.40,6.80,4.60,5.40,6,6,4.60,9
19,SI,NSi,NSI,2010,2020.1,7.82,6.33,-,-,-,...,0,8.25,9.17,5.38,5.62,7.91,7.45,-,-,3.4
20,SI,NSi,NSI,2014,2020.1,7.85,8.08,-,-,6.85,...,5.60,-,8.92,7.82,-,8,-,-,-,5.6
21,SI,NSi,NSI,2019,2020.1,7.5,7.36,2.57,1.86,7.33,...,8,-,8.07,7.47,-,7.13,-,-,-,7.16
22,SI,NeP,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
23,SI,PS,PS,2014,2020.1,3.38,4.15,-,-,6.69,...,0,-,3.58,4.80,-,3.22,-,-,-,3
24,SI,SAB,AB,2019,2020.1,4.21,4.36,5,2.57,6,...,5.70,-,2.79,4.07,-,3.93,-,-,-,5.11
25,SI,SD,ZLSD,2002,2020.1,3.6,4.2,-,-,-,...,12.2,-,-,-,-,-,-,-,-,12.1
26,SI,SD,ZLSD,2006,2020.1,3.6,3.4,-,-,-,...,11.1,7,2.60,3.20,6.80,3.60,4.60,4.80,4.60,10.2
27,SI,SD,SD,2010,2020.1,3.67,3.75,-,-,-,...,32.20,5,2.33,3.10,6.90,2.75,3.42,-,-,30.5
28,SI,SD,SD,2014,2020.1,3.15,3.42,-,-,6.15,...,6.70,-,2.75,3.18,-,4.11,-,-,-,6
29,SI,SD,SD,2019,2020.1,2.57,3.07,3.29,2,6.07,...,11.4,-,1.57,2.67,-,3.67,-,-,-,9.93
30,SI,SDS,SDS,2002,2020.1,6.4,4.8,-,-,-,...,15.6,-,-,-,-,-,-,-,-,15.8
31,SI,SDS,SDS,2006,2020.1,7.4,6.4,-,-,-,...,32.20,5.20,6.80,5.60,5.40,5,4.20,7,6,29.1
32,SI,SDS,SDS,2010,2020.1,6.92,5.92,-,-,-,...,31.1,5.67,7,5.64,5.80,6,5.5,-,-,29.3
33,SI,SDS,SDS,2014,2020.1,8.69,8.62,-,-,6.08,...,23.30,-,8.5,7.91,-,7.12,-,-,-,20.7
34,SI,SDS,SDS,2019,2020.1,8.64,7.5,2.43,1.29,7.47,...,28.4,-,8.43,7.73,-,6.73,-,-,-,24.92
35,SI,SKD,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
36,SI,SLS,SLS,2006,2020.1,6.4,5.0,-,-,-,...,7.80,5.20,7.20,4.20,4.60,7.20,8,4.80,3.8,6.8
37,SI,SLS,SLS,2014,2020.1,6.46,6.31,-,-,5.77,...,0,-,7.25,6.10,-,8.22,-,-,-,4
38,SI,SLS+SKD,SLS-SKD,2002,2020.1,6.8,5.0,-,-,-,...,10,-,-,-,-,-,-,-,-,9.6
39,SI,SMC,SMC,2014,2020.1,5.25,5.38,-,-,6.38,...,40,-,4.67,5,-,4.22,-,-,-,34.5
40,SI,SMC,SMC,2019,2020.1,4.79,5.14,4.86,3.71,6.33,...,11.4,-,3.5,4.80,-,3.40,-,-,-,9.75
41,SI,SMS,SMS,2002,2020.1,4.4,4.0,-,-,-,...,4.40,-,-,-,-,-,-,-,-,4.3
42,SI,SNS,SNS,2002,2020.1,3.6,4.2,-,-,-,...,4.40,-,-,-,-,-,-,-,-,4.4
43,SI,SNS,SNS,2006,2020.1,6.0,4.2,-,-,-,...,6.70,7.40,8.60,4.20,4,5.20,3.80,3,5.20,6.3
44,SI,SNS,SNS,2010,2020.1,8.0,6.0,-,-,-,...,5.60,7.5,9.25,6.12,3.44,5,3.67,-,-,5.4
45,SI,SNS,SNS,2019,2020.1,8.71,6.31,6.33,1.57,4.07,...,4.5,-,8.85,6.5,-,5.71,-,-,-,4.17
46,SI,ZL,ZL,2014,2020.1,1.0,0.67,-,-,6.62,...,6.70,-,1.17,1.90,-,2.89,-,-,-,6
47,SI,ZLSD,ZLSD,2002,2020.1,3.6,4.2,-,-,-,...,12.2,-,-,-,-,-,-,-,-,12.1
48,SI,ZLSD,ZLSD,2006,2020.1,3.6,3.4,-,-,-,...,11.1,7,2.60,3.20,6.80,3.60,4.60,4.80,4.60,10.2
49,SI,ZaAB,ZaAB,2014,2020.1,4.15,4.69,-,-,7,...,4.40,-,3.20,5.5,-,3.56,-,-,-,4.4
50,SI,ZaSLD,AB,2019,2020.1,4.21,4.36,5,2.57,6,...,5.70,-,2.79,4.07,-,3.93,-,-,-,5.11
51,SI,Zares,Zares,2010,2020.1,3.92,4.58,-,-,-,...,10,6.83,0.92,4.60,6.20,2.25,3.67,-,-,9.4

In [3]:
#Convert CHES scores to interger
exclude = ['country', 'pm_id', 'ches_id', 'chesversion']
df[df.columns.difference(exclude)] = df[df.columns.difference(exclude)].apply(pd.to_numeric, errors='coerce')
df.head()

,country,pm_id,ches_id,year,chesversion,lrgen,lrecon,lrecon_blur,lrecon_dissent,lrecon_salience,...,seat,social_salience,sociallifestyle,spendvtax,spendvtax_salience,urban_rural,urban_salience,us,us_salience,vote
0,SI,DL,-,NaN,-,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SI,DLGV,-,NaN,-,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SI,DeSUS,DeSUS,2002.0,2020.1,3.40,3.40,NaN,NaN,NaN,...,4.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.2
3,SI,DeSUS,DeSUS,2006.0,2020.1,3.20,2.60,NaN,NaN,NaN,...,4.4,4.60,4.40,2.8,5.6,5.20,3.60,3.8,3.8,4.0
4,SI,DeSUS,DeSUS,2010.0,2020.1,4.25,3.33,NaN,NaN,NaN,...,7.8,3.25,5.17,2.4,7.2,4.91,3.73,NaN,NaN,7.5

In [4]:
groups = {
    "ZL": "ZL/Levica",
    "Levica": "ZL/Levica",
    "ZaAB":"ZaAB/ZaSLD/SAB",
    "ZaSLD":"ZaAB/ZaSLD/SAB",
    "SAB" :"ZaAB/ZaSLD/SAB",
    "ZLSD":"ZLSD/SD",
    "SD":"ZLSD/SD",
    "SLS+SKD":"SLS+SKD/SLS",
    "SLS":"SLS+SKD/SLS", 
    "DLGV":"DLGV/DL", 
    "DL":"DLGV/DL",
    "SMC":"SMC/GAS/Konkretno",
    "Konkretno": "SMC/GAS/Konkretno"

}
df["grouped_party"] = df['pm_id'].replace(groups).fillna(df['pm_id'])
df = df.sort_values(by='year')
df

,country,pm_id,ches_id,year,chesversion,lrgen,lrecon,lrecon_blur,lrecon_dissent,lrecon_salience,...,social_salience,sociallifestyle,spendvtax,spendvtax_salience,urban_rural,urban_salience,us,us_salience,vote,grouped_party
2,SI,DeSUS,DeSUS,2002.0,2020.1,3.40,3.40,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.20,DeSUS
30,SI,SDS,SDS,2002.0,2020.1,6.40,4.80,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.80,SDS
17,SI,NSi,NSI,2002.0,2020.1,7.00,4.80,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.60,NSi
38,SI,SLS+SKD,SLS-SKD,2002.0,2020.1,6.80,5.00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.60,SLS+SKD/SLS
25,SI,SD,ZLSD,2002.0,2020.1,3.60,4.20,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.10,ZLSD/SD
42,SI,SNS,SNS,2002.0,2020.1,3.60,4.20,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.40,SNS
41,SI,SMS,SMS,2002.0,2020.1,4.40,4.00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.30,SMS
9,SI,LDS,LDS,2002.0,2020.1,4.20,6.20,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.30,LDS
47,SI,ZLSD,ZLSD,2002.0,2020.1,3.60,4.20,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.10,ZLSD/SD
43,SI,SNS,SNS,2006.0,2020.1,6.00,4.20,NaN,NaN,NaN,...,7.40,8.60,4.20,4.00,5.20,3.80,3.0,5.2,6.30,SNS
48,SI,ZLSD,ZLSD,2006.0,2020.1,3.60,3.40,NaN,NaN,NaN,...,7.00,2.60,3.20,6.80,3.60,4.60,4.8,4.6,10.20,ZLSD/SD
18,SI,NSi,NSI,2006.0,2020.1,8.40,6.80,NaN,NaN,NaN,...,5.60,8.40,6.80,4.60,5.40,6.00,6.0,4.6,9.00,NSi
36,SI,SLS,SLS,2006.0,2020.1,6.40,5.00,NaN,NaN,NaN,...,5.20,7.20,4.20,4.60,7.20,8.00,4.8,3.8,6.80,SLS+SKD/SLS
31,SI,SDS,SDS,2006.0,2020.1,7.40,6.40,NaN,NaN,NaN,...,5.20,6.80,5.60,5.40,5.00,4.20,7.0,6.0,29.10,SDS
3,SI,DeSUS,DeSUS,2006.0,2020.1,3.20,2.60,NaN,NaN,NaN,...,4.60,4.40,2.80,5.60,5.20,3.60,3.8,3.8,4.00,DeSUS
10,SI,LDS,LDS,2006.0,2020.1,3.40,3.80,NaN,NaN,NaN,...,7.60,2.00,4.20,6.20,2.80,3.80,4.6,4.2,22.80,LDS
26,SI,SD,ZLSD,2006.0,2020.1,3.60,3.40,NaN,NaN,NaN,...,7.00,2.60,3.20,6.80,3.60,4.60,4.8,4.6,10.20,ZLSD/SD
44,SI,SNS,SNS,2010.0,2020.1,8.00,6.00,NaN,NaN,NaN,...,7.50,9.25,6.12,3.44,5.00,3.67,NaN,NaN,5.40,SNS
32,SI,SDS,SDS,2010.0,2020.1,6.92,5.92,NaN,NaN,NaN,...,5.67,7.00,5.64,5.80,6.00,5.50,NaN,NaN,29.30,SDS
27,SI,SD,SD,2010.0,2020.1,3.67,3.75,NaN,NaN,NaN,...,5.00,2.33,3.10,6.90,2.75,3.42,NaN,NaN,30.50,ZLSD/SD
51,SI,Zares,Zares,2010.0,2020.1,3.92,4.58,NaN,NaN,NaN,...,6.83,0.92,4.60,6.20,2.25,3.67,NaN,NaN,9.40,Zares
4,SI,DeSUS,DeSUS,2010.0,2020.1,4.25,3.33,NaN,NaN,NaN,...,3.25,5.17,2.40,7.20,4.91,3.73,NaN,NaN,7.50,DeSUS
19,SI,NSi,NSI,2010.0,2020.1,7.82,6.33,NaN,NaN,NaN,...,8.25,9.17,5.38,5.62,7.91,7.45,NaN,NaN,3.40,NSi
11,SI,LDS,LDS,2010.0,2020.1,4.75,5.83,NaN,NaN,NaN,...,7.17,1.00,5.90,5.20,2.17,3.91,NaN,NaN,5.21,LDS
28,SI,SD,SD,2014.0,2020.1,3.15,3.42,NaN,NaN,6.15,...,NaN,2.75,3.18,NaN,4.11,NaN,NaN,NaN,6.00,ZLSD/SD
49,SI,ZaAB,ZaAB,2014.0,2020.1,4.15,4.69,NaN,NaN,7.00,...,NaN,3.20,5.50,NaN,3.56,NaN,NaN,NaN,4.40,ZaAB/ZaSLD/SAB
23,SI,PS,PS,2014.0,2020.1,3.38,4.15,NaN,NaN,6.69,...,NaN,3.58,4.80,NaN,3.22,NaN,NaN,NaN,3.00,PS
20,SI,NSi,NSI,2014.0,2020.1,7.85,8.08,NaN,NaN,6.85,...,NaN,8.92,7.82,NaN,8.00,NaN,NaN,NaN,5.60,NSi
33,SI,SDS,SDS,2014.0,2020.1,8.69,8.62,NaN,NaN,6.08,...,NaN,8.50,7.91,NaN,7.12,NaN,NaN,NaN,20.70,SDS
5,SI,DeSUS,DeSUS,2014.0,2020.1,4.15,4.00,NaN,NaN,5.54,...,NaN,5.10,3.36,NaN,5.22,NaN,NaN,NaN,10.20,DeSUS
37,SI,SLS,SLS,2014.0,2020.1,6.46,6.31,NaN,NaN,5.77,...,NaN,7.25,6.10,NaN,8.22,NaN,NaN,NaN,4.00,SLS+SKD/SLS
46,SI,ZL,ZL,2014.0,2020.1,1.00,0.67,NaN,NaN,6.62,...,NaN,1.17,1.90,NaN,2.89,NaN,NaN,NaN,6.00,ZL/Levica
39,SI,SMC,SMC,2014.0,2020.1,5.25,5.38,NaN,NaN,6.38,...,NaN,4.67,5.00,NaN,4.22,NaN,NaN,NaN,34.50,SMC/GAS/Konkretno
13,SI,Levica,ZL,2014.0,2020.1,1.00,0.67,NaN,NaN,6.62,...,NaN,1.17,1.90,NaN,2.89,NaN,NaN,NaN,6.00,ZL/Levica
45,SI,SNS,SNS,2019.0,2020.1,8.71,6.31,6.33,1.57,4.07,...,NaN,8.85,6.50,NaN,5.71,NaN,NaN,NaN,4.17,SNS
6,SI,DeSUS,DeSUS,2019.0,2020.1,3.77,3.29,4.71,2.57,4.67,...,NaN,4.29,2.53,NaN,4.93,NaN,NaN,NaN,4.93,DeSUS
50,SI,ZaSLD,AB,2019.0,2020.1,4.21,4.36,5.00,2.57,6.00,...,NaN,2.79,4.07,NaN,3.93,NaN,NaN,NaN,5.11,ZaAB/ZaSLD/SAB
24,SI,SAB,AB,2019.0,2020.1,4.21,4.36,5.00,2.57,6.00,...,NaN,2.79,4.07,NaN,3.93,NaN,NaN,NaN,5.11,ZaAB/ZaSLD/SAB
14,SI,Levica,Levica,2019.0,2020.1,0.71,0.71,1.57,1.71,5.93,...,NaN,0.50,1.53,NaN,1.93,NaN,NaN,NaN,9.33,ZL/Levica
34,SI,SDS,SDS,2019.0,2020.1,8.64,7.50,2.43,1.29,7.47,...,NaN,8.43,7.73,NaN,6.73,NaN,NaN,NaN,24.92,SDS
21,SI,NSi,NSI,2019.0,2020.1,7.50,7.36,2.57,1.86,7.33,...,NaN,8.07,7.47,NaN,7.13,NaN,NaN,NaN,7.16,NSi
29,SI,SD,SD,2019.0,2020.1,2.57,3.07,3.29,2.00,6.07,...,NaN,1.57,2.67,NaN,3.67,NaN,NaN,NaN,9.93,ZLSD/SD
12,SI,LMŠ,LMS,2019.0,2020.1,4.36,4.64,5.43,3.67,6.13,...,NaN,3.64,4.20,NaN,4.87,NaN,NaN,NaN,12.60,LMŠ
40,SI,SMC,SMC,2019.0,2020.1,4.79,5.14,4.86,3.71,6.33,...,NaN,3.50,4.80,NaN,3.40,NaN,NaN,NaN,9.75,SMC/GAS/Konkretno
0,SI,DL,-,NaN,-,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DLGV/DL
1,SI,DLGV,-,NaN,-,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DLGV/DL
7,SI,GAS,-,NaN,-,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GAS
8,SI,Konkretno,-,NaN,-,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SMC/GAS/Konkretno
15,SI,Lipa,-,NaN,-,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lipa
16,SI,NP,-,NaN,-,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NP
22,SI,NeP,-,NaN,-,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NeP
35,SI,SKD,-,NaN,-,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SKD

## LRGEN Scores by Party across Years

In [5]:
lrgen = df.dropna(subset=["lrgen"])
fig = px.line(lrgen, x='year', y='lrgen', color='grouped_party', 
              markers=True, title='LRGEN Scores by Parties Across Years',
              labels={'year': 'Year', 'lrgen': 'LRGEN Score', 'grouped_party': 'Party'}, color_discrete_sequence=px.colors.qualitative.Vivid,
)


fig.update_layout(
    height=650,  
    width=1000,
    xaxis=dict(tickmode='linear', dtick=3),
    yaxis_title='LRGEN Score',
    legend_title='Party',
    template='plotly_white'
)

fig.write_image('../../Figures/Sentiment_Analysis/CHES/LRGEN.png')
fig.show()

## LRECON Scores by Party across Years

In [6]:
lrecon = df.dropna(subset=["lrecon"])
fig = px.line(lrecon, x='year', y='lrecon', color='grouped_party', 
              markers=True, title='LRECON Scores by Parties Across Years',
              labels={'year': 'Year', 'lrecon': 'LRECON Score', 'grouped_party': 'Party'})

fig.update_layout(
    height=650,  
    width=1000,
    xaxis=dict(tickmode='linear', dtick=3),

    yaxis_title='LRECON Score',
    legend_title='Party',
    template='plotly_white'
)

fig.write_image('../../Figures/Sentiment_Analysis/CHES/LRECON.png')

fig.show()

## Redistribution Scores by Party across Years

In [7]:
redistr = df.dropna(subset=["redistribution"])

fig = px.line(redistr, x='year', y='redistribution', color='grouped_party', 
              markers=True, title='Redistribution Scores by Parties Across Years',
              labels={'year': 'Year', 'redistribution': 'Redistribution Score', 'grouped_party': 'Party'})


fig.update_layout(
    height=650,  
    width=1000,
    xaxis=dict(tickmode='linear', dtick=3),

    yaxis_title='Redistribution Score',
    legend_title='Party',
    template='plotly_white'
)

fig.write_image('../../Figures/Sentiment_Analysis/CHES/Redistribution.png')

fig.show()

## CIVLIB Scores by Party across Years

In [8]:
civlib = df.dropna(subset=["civlib_laworder"])

fig = px.line(civlib, x='year', y='civlib_laworder', color='grouped_party', 
              markers=True, title='CIVLIB Scores by Parties Across Years',
              labels={'year': 'Year', 'civlib_laworder': 'CIVLIB Score', 'grouped_party': 'Party'})


fig.update_layout(
    height=600,  
    width=1000,
    xaxis=dict(tickmode='linear', dtick=3),
    yaxis_title='CIVLIB Score',
    legend_title='Party',
    template='plotly_white'
)

fig.write_image('../../Figures/Sentiment_Analysis/CHES/CIVLIB.png')

fig.show()

# EU General Questions

## Overview of the EU-related variables

In [9]:
eu_columns = ['pm_id', 'year', 'chesversion', 'eu_position', 'eu_salience', 'eu_dissent', 'eu_ep', 'eu_intmark', 'eu_cohesion', 'eu_foreign', 'mip_one', 'mip_two', 'mip_three', 'grouped_party']
eu = df[eu_columns]
eu

,pm_id,year,chesversion,eu_position,eu_salience,eu_dissent,eu_ep,eu_intmark,eu_cohesion,eu_foreign,mip_one,mip_two,mip_three,grouped_party
2,DeSUS,2002.0,2020.1,5.00,6.00,2.44,2.50,3.00,4.33,2.75,NaN,NaN,NaN,DeSUS
30,SDS,2002.0,2020.1,6.40,8.00,0.89,4.60,4.75,5.67,5.50,NaN,NaN,NaN,SDS
17,NSi,2002.0,2020.1,6.00,8.67,1.33,4.60,4.00,5.33,4.50,NaN,NaN,NaN,NSi
38,SLS+SKD,2002.0,2020.1,4.80,6.00,3.56,3.60,2.50,4.67,4.25,NaN,NaN,NaN,SLS+SKD/SLS
25,SD,2002.0,2020.1,5.50,6.67,3.11,3.60,4.00,5.33,4.50,NaN,NaN,NaN,ZLSD/SD
42,SNS,2002.0,2020.1,2.40,2.67,2.67,1.60,1.60,2.33,2.25,NaN,NaN,NaN,SNS
41,SMS,2002.0,2020.1,5.20,5.33,2.22,3.25,3.50,4.67,5.00,NaN,NaN,NaN,SMS
9,LDS,2002.0,2020.1,6.60,8.67,2.67,5.00,5.50,6.00,5.50,NaN,NaN,NaN,LDS
47,ZLSD,2002.0,2020.1,5.50,6.67,3.11,3.60,4.00,5.33,4.50,NaN,NaN,NaN,ZLSD/SD
43,SNS,2006.0,2020.1,2.60,3.33,1.00,2.60,2.50,4.20,2.25,NaN,NaN,NaN,SNS
48,ZLSD,2006.0,2020.1,6.20,8.00,1.60,6.00,5.75,6.40,6.00,NaN,NaN,NaN,ZLSD/SD
18,NSi,2006.0,2020.1,6.25,6.67,1.60,6.00,5.75,6.20,5.25,NaN,NaN,NaN,NSi
36,SLS,2006.0,2020.1,5.00,4.67,3.20,4.80,4.25,5.60,4.50,NaN,NaN,NaN,SLS+SKD/SLS
31,SDS,2006.0,2020.1,6.40,8.67,1.00,5.33,5.20,5.50,6.00,NaN,NaN,NaN,SDS
3,DeSUS,2006.0,2020.1,5.40,5.33,2.00,5.20,4.50,5.40,4.75,NaN,NaN,NaN,DeSUS
10,LDS,2006.0,2020.1,6.40,8.00,3.40,5.17,5.20,4.83,5.50,NaN,NaN,NaN,LDS
26,SD,2006.0,2020.1,6.20,8.00,1.60,6.00,5.75,6.40,6.00,NaN,NaN,NaN,ZLSD/SD
44,SNS,2010.0,2020.1,3.00,4.00,1.70,3.33,3.44,4.00,2.25,NaN,NaN,NaN,SNS
32,SDS,2010.0,2020.1,5.82,6.67,1.60,5.40,5.40,5.89,5.14,NaN,NaN,NaN,SDS
27,SD,2010.0,2020.1,6.55,8.48,2.50,6.00,5.40,6.56,6.25,NaN,NaN,NaN,ZLSD/SD
51,Zares,2010.0,2020.1,6.36,7.27,2.30,5.70,5.60,6.11,5.38,NaN,NaN,NaN,Zares
4,DeSUS,2010.0,2020.1,4.90,3.33,1.75,5.00,4.33,5.38,4.57,NaN,NaN,NaN,DeSUS
19,NSi,2010.0,2020.1,4.90,5.45,1.56,5.78,5.44,6.29,4.86,NaN,NaN,NaN,NSi
11,LDS,2010.0,2020.1,6.55,7.88,2.44,5.80,6.00,6.22,5.12,NaN,NaN,NaN,LDS
28,SD,2014.0,2020.1,5.85,6.31,3.18,5.60,5.27,6.00,5.44,14.0,13.0,3.0,ZLSD/SD
49,ZaAB,2014.0,2020.1,6.58,7.23,2.55,6.30,6.00,6.30,6.11,17.0,3.0,8.0,ZaAB/ZaSLD/SAB
23,PS,2014.0,2020.1,6.08,6.15,3.00,5.44,5.45,5.90,5.33,42.0,29.0,5.0,PS
20,NSi,2014.0,2020.1,6.46,7.23,2.36,5.80,5.64,6.10,5.89,33.0,15.0,3.0,NSi
33,SDS,2014.0,2020.1,6.38,7.54,1.73,6.00,6.18,6.10,6.33,3.0,1.0,5.0,SDS
5,DeSUS,2014.0,2020.1,5.77,5.54,2.50,5.30,5.30,6.10,5.56,14.0,13.0,8.0,DeSUS
37,SLS,2014.0,2020.1,6.08,6.77,2.45,5.70,5.55,6.10,5.67,18.0,4.0,3.0,SLS+SKD/SLS
46,ZL,2014.0,2020.1,3.69,4.54,1.22,5.00,3.73,5.60,4.11,13.0,14.0,2.0,ZL/Levica
39,SMC,2014.0,2020.1,6.42,6.15,2.10,5.89,6.00,6.30,6.22,3.0,2.0,1.0,SMC/GAS/Konkretno
13,Levica,2014.0,2020.1,3.69,4.54,1.22,5.00,3.73,5.60,4.11,13.0,14.0,2.0,ZL/Levica
45,SNS,2019.0,2020.1,2.67,3.13,1.88,NaN,3.31,4.50,2.07,NaN,NaN,NaN,SNS
6,DeSUS,2019.0,2020.1,5.53,5.60,3.12,NaN,4.87,5.75,4.64,NaN,NaN,NaN,DeSUS
50,ZaSLD,2019.0,2020.1,6.36,6.80,2.29,NaN,5.67,6.25,5.07,NaN,NaN,NaN,ZaAB/ZaSLD/SAB
24,SAB,2019.0,2020.1,6.36,6.80,2.29,NaN,5.67,6.25,5.07,NaN,NaN,NaN,ZaAB/ZaSLD/SAB
14,Levica,2019.0,2020.1,4.13,5.27,3.29,NaN,3.33,5.31,2.93,NaN,NaN,NaN,ZL/Levica
34,SDS,2019.0,2020.1,5.13,6.87,2.12,NaN,5.93,6.00,4.20,NaN,NaN,NaN,SDS
21,NSi,2019.0,2020.1,6.00,7.20,2.12,NaN,6.27,6.00,5.00,NaN,NaN,NaN,NSi
29,SD,2019.0,2020.1,6.47,7.93,2.25,NaN,5.27,5.79,5.00,NaN,NaN,NaN,ZLSD/SD
12,LMŠ,2019.0,2020.1,6.00,6.87,2.67,NaN,5.53,5.79,4.73,NaN,NaN,NaN,LMŠ
40,SMC,2019.0,2020.1,6.53,7.43,2.25,NaN,5.87,5.79,5.13,NaN,NaN,NaN,SMC/GAS/Konkretno
0,DL,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DLGV/DL
1,DLGV,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DLGV/DL
7,GAS,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GAS
8,Konkretno,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SMC/GAS/Konkretno
15,Lipa,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lipa
16,NP,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NP
22,NeP,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NeP
35,SKD,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SKD

## EU Position
Overall orientation of the party leadership towards European integration in YEAR.

Scale: : 1 = Strongly opposed, 2 = Opposed, 3 = Somewhat opposed, 4 = Neutral, 5 = Somewhat in favor, 6 = In favor, 7 = Strongly in favor

In [10]:
eu_position = df.dropna(subset=["eu_position"])
fig = px.line(
    eu_position,
    x="year",
    y="eu_position",
    color="grouped_party",
    title="EU Position of Political Parties Over Time",
    markers=True,
    labels={"eu_position": "EU Position", "year": "Year"},
    hover_data=["grouped_party"],
    color_discrete_sequence=px.colors.qualitative.Vivid,

)

fig.update_layout(
    height=650,  
    width=1000,
)

fig.write_image('../../Figures/Sentiment_Analysis/CHES/EU_Position.png')

fig.show()

## EU Salience
Relative salience of European integration in the party’s public stance in YEAR [11-point scale]:

Scale: 0 = European Integration is of no importance, never mentioned ...
10 = European Integration is the most important issue.

In [11]:
eu_salience = df.dropna(subset=["eu_salience"])
fig = px.line(eu_salience, x='year', y='eu_salience', color='grouped_party', 
              markers=True, title='EU Salience Scores by Parties Across Years',
              labels={'year': 'Year', 'eu_salience': 'EU Salience', 'grouped_party': 'Party'}, color_discrete_sequence=px.colors.qualitative.Plotly,
)

fig.update_layout(
    xaxis=dict(tickmode='linear', dtick=3),
    yaxis_title='EU Salience Score',
    legend_title='Party',
    template='plotly_white'
)

fig.update_layout(
    height=650,  
    width=1000,
)

fig.write_image('../../Figures/Sentiment_Analysis/CHES/EU_Salience.png')

fig.show()

## EU dissent

Degree of dissent on European integration in YEAR [11-point scale]:

0 = Party was completely united. … 10 = Party was extremely divided.

In [12]:
eu_dissent = df.dropna(subset=["eu_dissent"])
fig = px.line(eu_dissent, x='year', y='eu_dissent', color='grouped_party', 
              markers=True, title='EU Dissent Scores by Parties Across Years',
              labels={'year': 'Year', 'eu_dissent': 'EU Dissent', 'grouped_party': 'Party'}, color_discrete_sequence=px.colors.qualitative.Plotly,
)

fig.update_layout(
    xaxis=dict(tickmode='linear', dtick=3),
    yaxis_title='EU Dissent Score',
    legend_title='Party',
    template='plotly_white'
)

fig.update_layout(
    height=650,  
    width=1000,
)
fig.write_image('../../Figures/Sentiment_Analysis/CHES/EU_Dissent.png')

fig.show()

# Specific EU Policy Questions

## EU EP
Position of the party leadership in YEAR on the (strengthening) powers of the European Parliament. 

Scale: 1 = Strongly opposed, 2 = Opposed, 3 = Somewhat opposed, 4 = Neutral, 5 = Somewhat in favor, 6 = In favor, 7 = Strongly in favor
Scale interpretation: 
- 1 = Strongly opposed → Party leadership is firmly against expanding EP powers.
- 2 = Opposed → Generally against giving more power to the EP.
- 3 = Somewhat opposed → Leans against EP empowerment but not strongly.
- 4 = Neutral → No clear stance or balanced view.
- 5 = Somewhat in favour → Mildly supports strengthening EP powers.
- 6 = In favour → Generally supports expanding the EP's role.
- 7 = Strongly in favour → Fully supports a stronger European Parliament.

In [13]:
eu_ep = df.dropna(subset=["eu_ep"])
fig = px.line(eu_ep, x='year', y='eu_ep', color='grouped_party', 
              markers=True, title='EU European Parliament Scores by Parties Across Years',
              labels={'year': 'Year', 'eu_ep': 'EU EP', 'grouped_party': 'Party'}, color_discrete_sequence=px.colors.qualitative.Plotly,
)

fig.update_layout(
    yaxis_title='EU European Parliament Score',
    legend_title='Party',
    template='plotly_white'
)

fig.update_layout(
    height=650,  
    width=1000,
)

fig.write_image('../../Figures/Sentiment_Analysis/CHES/EU_EP.png')

fig.show()

## EU Intmark
Position of the party leadership in YEAR on the internal market (i.e. free movement of goods, services, capital and labor). (Not asked in 1999)

Scale: 1 = Strongly opposes … 7 = Strongly favours

In [14]:
eu_intmark = df.dropna(subset=["eu_intmark"])
fig = px.line(eu_intmark, x='year', y='eu_intmark', color='grouped_party', 
              markers=True, title='EU Intmark Scores by Parties Across Years',
              labels={'year': 'Year', 'eu_intmark': 'EU INTMARK', 'grouped_party': 'Party'}, color_discrete_sequence=px.colors.qualitative.Plotly,
)

fig.update_layout(
    yaxis_title='EU Intmark Score',
    legend_title='Party',
    template='plotly_white'
)

fig.update_layout(
    height=650,  
    width=1000,
)

fig.write_image('../../Figures/Sentiment_Analysis/CHES/EU_Intmark.png')

fig.show()

## EU Cohesion
Position of the party leadership in YEAR on EU cohesion or regional policy (e.g. the structural funds)

Scale: 1 = Strongly opposes … 7 = Strongly favours

In [15]:
eu_cohesion = df.dropna(subset=["eu_cohesion"])
fig = px.line(eu_cohesion, x='year', y='eu_cohesion', color='grouped_party', 
              markers=True, title='EU Cohesion Scores by Parties Across Years',
              labels={'year': 'Year', 'eu_cohesion': 'EU Cohesion', 'grouped_party': 'Party'}, color_discrete_sequence=px.colors.qualitative.Bold,
)

fig.update_layout(
    yaxis_title='EU Cohesion Score',
    legend_title='Party',
    template='plotly_white'
)

fig.update_layout(
    height=700,  
    width=1000,
)

fig.write_image('../../Figures/Sentiment_Analysis/CHES/EU_Cohesion.png')

fig.show()

## EU Foreign

Position of the party leadership in YEAR on EU foreign and security policy (i.e., EU involvement in foreign and security policy).

Scale: 1 = Strongly opposes … 7 = Strongly favours

In [16]:
eu_foreign = df.dropna(subset=["eu_foreign"])
fig = px.line(eu_foreign, x='year', y='eu_foreign', color='grouped_party', 
              markers=True, title='EU Foreign Scores by Parties Across Years',
              labels={'year': 'Year', 'eu_foreign': 'EU Foreign', 'grouped_party': 'Party'}, color_discrete_sequence=px.colors.qualitative.Bold,
)

fig.update_layout(
    yaxis_title='EU Foreign Score',
    legend_title='Party',
    template='plotly_white'
)

fig.update_layout(
    height=700,  
    width=1000,
)

fig.write_image('../../Figures/Sentiment_Analysis/CHES/EU_Foreign.png')

fig.show()

## Most Important Issues
Three most important issues for the party over the course of the YEAR (Asked only in **2014**) - MIP_ONE, MIP_TWO, MIP_THREE

Numerical values in the data corespond to the topics available in the ***1999-2019 Chapel Hill Expert Survey (CHES) trend file Codebook*** (https://www.chesdata.eu/ches-europe)

In [17]:
mips = ['pm_id', 'grouped_party', 'mip_one', 'mip_two', 'mip_three']
mip = df[mips]
mip = mip.dropna(subset=['mip_one', 'mip_two', 'mip_three']).reset_index()
mip = mip.drop(columns='index')
mip[['mip_one', 'mip_two', 'mip_three']] = mip[['mip_one', 'mip_two', 'mip_three']].astype(int)
mip

    pm_id      grouped_party  mip_one  mip_two  mip_three
0      SD            ZLSD/SD       14       13          3
1    ZaAB     ZaAB/ZaSLD/SAB       17        3          8
2      PS                 PS       42       29          5
3     NSi                NSi       33       15          3
4     SDS                SDS        3        1          5
5   DeSUS              DeSUS       14       13          8
6     SLS        SLS+SKD/SLS       18        4          3
7      ZL          ZL/Levica       13       14          2
8     SMC  SMC/GAS/Konkretno        3        2          1
9  Levica          ZL/Levica       13       14          2

In [18]:
mip_mapping = {
    1: "Anti-elite rhetoric",
    2: 'Civil liberties',
    3: "Corruption",
    4 :'Decentralization',
    5: "Deregulation",
    6: 'Environment',
    7: "Ethnic minorities",
    8: 'EU integration',
    9: "Immigration",
    10: 'International security',
    11: "Multiculturalism",
    12: 'Nationalism',
    13: 'Public services vs taxes', 
    14: 'Redistribution',
    15: 'Religious principles',
    16: 'Social lifestyle',
    17: 'State intervention',
    18: 'Urban vs. rural',
    29: 'Tie: Corruption and Social lifestyle',
    33: 'Tie: Deregulation and Public services vs taxes',
    42: 'Tie: Public services vs taxes and State intervention'
}

In [19]:
mip["issues"] = mip.apply(lambda row: "; ".join(
    filter(None, [
        mip_mapping.get(row["mip_one"], ""),  
        mip_mapping.get(row["mip_two"], ""),
        mip_mapping.get(row["mip_three"], "")
    ])
), axis=1) 

mip

,pm_id,grouped_party,mip_one,mip_two,mip_three,issues
0,SD,ZLSD/SD,14,13,3,Redistribution; Public services vs taxes; Corr...
1,ZaAB,ZaAB/ZaSLD/SAB,17,3,8,State intervention; Corruption; EU integration
2,PS,PS,42,29,5,Tie: Public services vs taxes and State interv...
3,NSi,NSi,33,15,3,Tie: Deregulation and Public services vs taxes...
4,SDS,SDS,3,1,5,Corruption; Anti-elite rhetoric; Deregulation
5,DeSUS,DeSUS,14,13,8,Redistribution; Public services vs taxes; EU i...
6,SLS,SLS+SKD/SLS,18,4,3,Urban vs. rural; Decentralization; Corruption
7,ZL,ZL/Levica,13,14,2,Public services vs taxes; Redistribution; Civi...
8,SMC,SMC/GAS/Konkretno,3,2,1,Corruption; Civil liberties; Anti-elite rhetoric
9,Levica,ZL/Levica,13,14,2,Public services vs taxes; Redistribution; Civi...

In [20]:
mip[["mip_one", "mip_two", "mip_three"]] = mip[["mip_one", "mip_two", "mip_three"]].replace(mip_mapping)
mip = mip.drop(columns=['grouped_party', 'issues'])
mip

,pm_id,mip_one,mip_two,mip_three
0,SD,Redistribution,Public services vs taxes,Corruption
1,ZaAB,State intervention,Corruption,EU integration
2,PS,Tie: Public services vs taxes and State interv...,Tie: Corruption and Social lifestyle,Deregulation
3,NSi,Tie: Deregulation and Public services vs taxes,Religious principles,Corruption
4,SDS,Corruption,Anti-elite rhetoric,Deregulation
5,DeSUS,Redistribution,Public services vs taxes,EU integration
6,SLS,Urban vs. rural,Decentralization,Corruption
7,ZL,Public services vs taxes,Redistribution,Civil liberties
8,SMC,Corruption,Civil liberties,Anti-elite rhetoric
9,Levica,Public services vs taxes,Redistribution,Civil liberties

In [ ]:
#print(mip.to_latex(index=False))

\begin{tabular}{llll}
\toprule
pm_id & mip_one & mip_two & mip_three \\
\midrule
SD & Redistribution & Public services vs taxes & Corruption \\
ZaAB & State intervention & Corruption & EU integration \\
PS & Tie: Public services vs taxes and State intervention & Tie: Corruption and Social lifestyle & Deregulation \\
NSi & Tie: Deregulation and Public services vs taxes & Religious principles & Corruption \\
SDS & Corruption & Anti-elite rhetoric & Deregulation \\
DeSUS & Redistribution & Public services vs taxes & EU integration \\
SLS & Urban vs. rural & Decentralization & Corruption \\
ZL & Public services vs taxes & Redistribution & Civil liberties \\
SMC & Corruption & Civil liberties & Anti-elite rhetoric \\
Levica & Public services vs taxes & Redistribution & Civil liberties \\
\bottomrule
\end{tabular}